### ISSUE TITLE
Failed to install the retinanet through pip

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/retinanet-examples#100]
I pulled the image "nvcr.io/nvidia/pytorch:19.09-py3" and ran it.

However, it failed to install the retinanet through pip

The error messages are

![image](https://user-images.githubusercontent.com/13084622/71012498-359c4c00-212a-11ea-94a4-442d85a4e959.png)

Then I tried to build the image of my own. But it seems the build process terminated with authentication error 

![image](https://user-images.githubusercontent.com/13084622/71012765-9166d500-212a-11ea-829e-9a756dc80dba.png)

![image](https://user-images.githubusercontent.com/13084622/71012886-bfe4b000-212a-11ea-952f-37ac23f6e6d6.png)

Any help is appretiated!

**Comment by yashnv** [comment]
@KleinXin you'll need to create a [NGC account](https://ngc.nvidia.com/signup), and then go to `Setup >
API Key` and follow the steps to `docker login nvcr.io`. You can enter all the default values in `ngc config set`.

**Comment by KleinXin** [comment]
> @KleinXin you'll need to create a [NGC account](https://ngc.nvidia.com/signup), and then go to `Setup > API Key` and follow the steps to `docker login nvcr.io`. You can enter all the default values in `ngc config set`.

Thank you for you reply!

When I typed "ngc config set",  it seems I need to install ngc first

![image](https://user-images.githubusercontent.com/13084622/71046871-ab2d0a00-2174-11ea-9cbf-db63be0d63e4.png)

"docker login nvcr.io" command failed because of authentication error

![image](https://user-images.githubusercontent.com/13084622/71046919-ce57b980-2174-11ea-9fa1-8c8f2d916add.png)

**Comment by james-nvidia** [comment]
You need to log in with your username set to `$oauthtoken` and the password is your API key.

**Comment by KleinXin** [comment]
> You need to log in with your username set to `$oauthtoken` and the password is your API key.

Unfortunately, it failed again when I tried to login with my API Key

![image](https://user-images.githubusercontent.com/13084622/71048912-d2d3a080-217b-11ea-8170-24333c6e41af.png)

**Comment by yashnv** [comment]
Your username is not the NGC username! 
Docker login password needs to be generated through 
`Setup > API Key > Generate API Key (upper-right corner)`
```
Username: $oauthtoken
Password: <GENERATED_API_KEY>
````

**Comment by KleinXin** [comment]
> The username is not KleinXin
> `$oauthtoken` is the username.
> Docker login password needs to be generated through
> `Setup > API Key > Generate API Key (upper-right corner)`
> 
> ```
> Username: $oauthtoken
> Password: <GENERATED_API_KEY>
> ```

Thank you all! It works now.
