### ISSUE TITLE
Missing dynamic range for tensor input.1

### ISSUE THREAD

**Issue by kurff** [NVIDIA/retinanet-examples#101]
We use T4 for inference, the CUDA is 10.0, TensorRT version: 6.0.1.5
Missing dynamic range for tensor input.1, expect fall back to non-int8 implementation for any layer consuming or producing given tensor.

We get the following errors:
No non-int8 implementation of layer (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 2) [Activation] + (Unnamed Layer* 3) [Pooling] is supported. Please provide missing int8 scales to use available int8 implementation.
../builder/tacticOptimizer.cpp (3142) - Misc Error in getFormatRequirements: -1 (Unable to find valid implementation for layer (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 2) [Activation] + (Unnamed Layer* 3) [Pooling])
../builder/tacticOptimizer.cpp (3142) - Misc Error in getFormatRequirements: -1 (Unable to find valid implementation for layer (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 2) [Activation] + (Unnamed Layer* 3) [P?)
Segmentation fault

**Comment by yashnv** [comment]
@kurff Plaese provide more environment info, this could be a version mismatch problem. Are you running this inside NGC container?

**Comment by kurff** [comment]
We build this project from source file.
TensorRT version: 6.0.1.5
Pytorch version: 1.2.0
CUDA version: 10.0
As your mentioned, it is version mismatch problem. We have solved it. Thanks.

**Comment by duohaoxue** [comment]
> We build this project from source file.
> TensorRT version: 6.0.1.5
> Pytorch version: 1.2.0
> CUDA version: 10.0
> As your mentioned, it is version mismatch problem. We have solved it. Thanks.
  Hi，What is your version ？
