### ISSUE TITLE
Loading from retinanet_rn18fpn.pth  pretrained model failed

### ISSUE THREAD

**Issue by mhasa004** [NVIDIA/retinanet-examples#102]
I am using following command to fine tune retinanet_rn18fpn.pth to a two class detector with my own dataset.
`DATA_DIR=/data/mhasan/data/knife-med
retinanet train model_mydataset.pth \
    --fine-tune ./models/retinanet_rn18fpn.pth \
    --classes 2 --iters 10000 --val-iters 1000 --lr 0.0005 \
    --resize 512 --jitter 480 640 \
    --images ${DATA_DIR} \
    --annotations ./data/knife_detection_annotation_coco-ddg-ggl_train.json \
    --val-images ${DATA_DIR} \
    --val-annotations ./data/knife_detection_annotation_coco_val.json`

It failed with following runtime error:
`Initializing model...
Fine-tuning weights from retinanet_rn18fpn.pth...
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 176, in main
    model, state = load_model(args, verbose=True)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 86, in load_model
    model.initialize(args.fine_tune)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/model.py", line 71, in initialize
    self.load_state_dict(state_dict)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
        Unexpected key(s) in state_dict: "backbones.ResNet18FPN.features.conv1.weight", "backbones.ResNet18FPN.features.bn1.weight", "backbones.ResNet18FPN.features.bn1.bias", "backbones.ResNet18FPN.features.bn1.running_mean", "backbones.ResNet18FPN.features.bn1.running_var", "backbones.ResNet18FPN.features.layer1.0.conv1.weight", "backbones.ResNet18FPN.features.layer1.0.bn1.weight", "backbones.ResNet18FPN.features.layer1.0.bn1.bias", "backbones.ResNet18FPN.features.layer1.0.bn1.running_mean", "backbones.ResNet18FPN.features.layer1.0.bn1.running_var", "backbones.ResNet18FPN.features.layer1.0.conv2.weight", "backbones.ResNet18FPN.features.layer1.0.bn2.weight", "backbones.ResNet18FPN.features.layer1.0.bn2.bias", "backbones.ResNet18FPN.features.layer1.0.bn2.running_mean", "backbones.ResNet18FPN.features.layer1.0.bn2.running_var", "backbones.ResNet18FPN.features.layer1.1.conv1.weight", "backbones.ResNet18FPN.features.layer1.1.bn1.weight", "backbones.ResNet18FPN.features.layer1.1.bn1.bias", "backbones.ResNet18FPN.features.layer1.1.bn1.running_mean", "backbones.ResNet18FPN.features.layer1.1.bn1.running_var", "backbones.ResNet18FPN.features.layer1.1.conv2.weight", "backbones.ResNet18FPN.features.layer1.1.bn2.weight", "backbones.ResNet18FPN.features.layer1.1.bn2.bias", "backbones.ResNet18FPN.features.layer1.1.bn2.running_mean", "backbones.ResNet18FPN.features.layer1.1.bn2.running_var", "backbones.ResNet18FPN.features.layer2.0.conv1.weight", "backbones.ResNet18FPN.features.layer2.0.bn1.weight", "backbones.ResNet18FPN.features.layer2.0.bn1.bias", "backbones.ResNet18FPN.features.layer2.0.bn1.running_mean", ....`

However, training model from a backbone worked just fine.
Do you have any idea what is the problem?

**Comment by yashnv** [comment]
You have to describe the backbone during fine-tuning `--backbone ResNet18FPN`. Let me know how it goes.

**Comment by mhasa004** [comment]
Thanks for the quick reply. It worked. Readme file misses this argument for fine-tuning.

**Comment by yashnv** [comment]
Thanks, will update it soon.
