### ISSUE TITLE
Anyway to save intermediate models?

### ISSUE THREAD

**Issue by mhasa004** [NVIDIA/retinanet-examples#103]
Hi,
I can see only one model is saved at the end of training. Is there any strategy on how models are being saved or the old model is just replaced by the new one? Is there anyway to save all the intermediate models so that I can decide which one to use based on the validation MAP?

**Comment by james-nvidia** [comment]
You would need to modify `train.py` to save out intermediate models.
Alternatively, I often train a model in 10k chunks, iterating the model name each time.
