### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION'

### ISSUE THREAD

**Issue by zardadi** [NVIDIA/retinanet-examples#105]
I have pulled the image created a container, but got "ImportError: cannot import name 'PILLOW_VERSION' " error when started trainnig a model. I have also cloned the repository and built the image, but the same issue. 

I am using Docker version 19.03.5
NVIDIA-SMI 435.21 with GTX 1070 graphic card.

Below is the entire error trace back:
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 11, in <module>
    load_entry_point('retinanet', 'console_scripts', 'retinanet')()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/workspace/retinanet/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/workspace/retinanet/retinanet/infer.py", line 13, in <module>
    from .model import Model
  File "/workspace/retinanet/retinanet/model.py", line 7, in <module>
    from . import backbones as backbones_mod
  File "/workspace/retinanet/retinanet/backbones/__init__.py", line 3, in <module>
    from .resnet import *
  File "/workspace/retinanet/retinanet/backbones/resnet.py", line 1, in <module>
    import torchvision
  File "/opt/conda/lib/python3.6/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION'

**Comment by yashnv** [comment]
What is your Pytorch container version?

**Comment by zardadi** [comment]
> What is your Pytorch container version?

>>> print(torch.__version__)
1.2.0a0+afb7a16

**Comment by yashnv** [comment]
Sorry I should have said the Nvidia docker container version, not the pytorch version.
What container did you pull using docker pull command?

**Comment by zardadi** [comment]
> Sorry I should have said the Nvidia docker container version, not the pytorch version. 
> What container did you pull using docker pull command?
I pulled 19.09 version from the readme file " docker run --gpus all --rm --ipc=host -it nvcr.io/nvidia/pytorch:19.09-py3"

**Comment by yashnv** [comment]
This command just initializes the container. 
Are you inside the container before doing pip install? You can confirm this if you see 
```
root@<some-random-string>:/workspace#
```
Did you do `docker pull nvcr.io/nvidia/pytorch:19.09-py3` before `docker run`?

**Comment by zardadi** [comment]
> This command just initializes the container.
> Are you inside the container before doing pip install? You can confirm this if you see
> 
> ```
> root@<some-random-string>:/workspace#
> ```
> 
> Did you do `docker pull nvcr.io/nvidia/pytorch:19.09-py3` before `docker run`?

Yes, I am inside the container!

**Comment by yashnv** [comment]
In that case can you try downgrading pillow `pip install pillow==6.2.1`?

**Comment by hugovk** [comment]
In Pillow 7.0.0:

> `PILLOW_VERSION` has been removed. Use `__version__` instead.

https://pillow.readthedocs.io/en/stable/deprecations.html#pillow-version-constant

This has been fixed in torchvision (https://github.com/pytorch/vision/pull/1501) and a new release is due out early next week (https://github.com/pytorch/vision/issues/1712).

Until the new torchvision release is out, the workaround is either to use the master version of torchvision (eg. `pip install -U git+https://github.com/pytorch/vision`), or Pillow<7 (eg. `pip install "pillow<7"`).

**Comment by yashnv** [comment]
Please do not install torchvision over git. 
For now use `pip install pillow==6.2.2`

**Comment by yashnv** [comment]
Please do not install torchvision over git. 
For now use `pip install pillow==6.2.2`

**Comment by zardadi** [comment]
> In Pillow 7.0.0:
> 
> > `PILLOW_VERSION` has been removed. Use `__version__` instead.
> 
> https://pillow.readthedocs.io/en/stable/deprecations.html#pillow-version-constant
> 
> This has been fixed in torchvision ([pytorch/vision#1501](https://github.com/pytorch/vision/pull/1501)) and a new release is due out early next week ([pytorch/vision#1712](https://github.com/pytorch/vision/issues/1712)).
> 
> Until the new torchvision release is out, the workaround is ~either to use the master version of torchvision (eg. `pip install -U git+https://github.com/pytorch/vision`), or~ to use Pillow<7 (eg. `pip install "pillow<7"`).

Yes, that was the problem. Thanks!

**Comment by zardadi** [comment]
> Please do not install torchvision over git.
> For now use `pip install pillow==6.2.2`
> 
> Closing this now.

Pillow 6.2.2 works fine. 
Just inside the container downgrading Pillow:
pip uninstall pillow
pip install pillow=6.2.2

Thanks for your help!

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin

**Comment by yashnv** [comment]
@hugovk we can't update the torchvision to 0.5.0 right now because it requires Pytorch==1.4.0, installing which will lead to instability with the `torch.onnx` module (which we want to avoid until we have made sure that these changes are compatible with TensorRT 7).

Once we have a stable working solution of TensorRT 7 with this repository, then we will remove the pin for pillow, and upgrade to torchvision>=0.5.0.

Really excited about Quantized models and Deformable convolutions!

**Comment by yashnv** [comment]
[7c4c7c0](https://github.com/NVIDIA/retinanet-examples/commit/7c4c7c080fba5e478af9fc698f12619a0ffa90ed) removes `pillow==6.2.2` as torchvision is updated to `0.6.0a0`
