### ISSUE TITLE
Flagged function dosen't work

### ISSUE THREAD

**Issue by YellowOldOdd** [NVIDIA/retinanet-examples#111]
https://github.com/NVIDIA/retinanet-examples/blob/master/csrc/cuda/decode.cu#L96
This thrust::cuda_cub::cub::DeviceSelect::Flagged in my program always did nothing and return 0. 
when i turn on debug mode described in https://nvlabs.github.io/cub/structcub_1_1_device_select.html

it shows : 
Invoking scan_init_kernel
or nothing

which should be :
Invoking scan_init_kernel
Invoking select_if_kernel

It dosen't work in my program with this plugin, but works in a stand alone .cu file. And I can't find more information about this function from nv's doc ...
what are the possible reasons?

**Comment by yashnv** [comment]
@YellowOldOdd 
Does the `num_selected` give some garbage value or 0?
Does the `indices` retain the same values as before `flagged` call?

**Comment by yashnv** [comment]
@YellowOldOdd did you check the above device variables? I am closing this now, because it seems to be a question related to internal working.
