### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by FenryrMKIII** [NVIDIA/retinanet-examples#114]
Is this repository supposed to work on Windows ?

When trying to install using pip, I multiple errors message but I can't identify what is the issue.

**Comment by yashnv** [comment]
We don't have any immediate plans to support a Windows Conda install at the moment.

**Comment by FenryrMKIII** [comment]
> We don't have any immediate plans to support a Windows Conda install at the moment.

Thanks for the answer.
I am wondering then : How could I start using your library for training on my own dataset by e.g. using a cloud service like AWS ? 

Because locally on Windows, when starting using  a new framework, I usually encounter issues and I can use VScode to interactively debug and understand. But on AWS EC2 instances, I only get a CLI and therefore debugging becomes very painful. Or am I missing something ?

**Comment by yashnv** [comment]
@FenryrMKIII you need to get an instance with either a Nvidia T4 or V100 GPU. Then install docker container in the instance, and pull NGC pytorch container version 19.10, and finally you can proceed with the instructions on this repository.
Please make sure to run `nvidia-smi` within the container to verify if it is correctly up and running.
