### ISSUE TITLE
error: ‘unique_ptr’ is not a member of ‘std’

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#116]
in retinanet-examples/extras/cppapi
cmake version 3.9.1
cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++14" ..
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jliu/retinanet-examples/extras/cppapi/build
2 make

make
[  9%] Building CUDA object CMakeFiles/retinanet.dir/home/jliu/retinanet-examples/csrc/cuda/decode.cu.o
[ 18%] Building CUDA object CMakeFiles/retinanet.dir/home/jliu/retinanet-examples/csrc/cuda/nms.cu.o
[ 27%] Building CXX object CMakeFiles/retinanet.dir/home/jliu/retinanet-examples/csrc/engine.cpp.o
/home/jliu/retinanet-examples/csrc/engine.cpp: In constructor ‘retinanet::Engine::Engine(const char*, size_t, size_t, std::__cxx11::string, float, int, const std::vector<std::vector<float> >&, float, int, const std::vector<std::__cxx11::basic_string<char> >&, std::__cxx11::string, std::__cxx11::string, bool, size_t)’:
/home/jliu/retinanet-examples/csrc/engine.cpp:118:10: error: ‘unique_ptr’ is not a member of ‘std’
     std::unique_ptr<Int8EntropyCalibrator> calib;
          ^~~~~~~~~~
/home/jliu/retinanet-examples/csrc/engine.cpp:118:10: note: suggested alternative: ‘unique_copy’
     std::unique_ptr<Int8EntropyCalibrator> calib;
          ^~~~~~~~~~
          unique_copy
/home/jliu/retinanet-examples/csrc/engine.cpp:118:42: error: expected primary-expression before ‘>’ token
     std::unique_ptr<Int8EntropyCalibrator> calib;
                                          ^
/home/jliu/retinanet-examples/csrc/engine.cpp:118:44: error: ‘calib’ was not declared in this scope
     std::unique_ptr<Int8EntropyCalibrator> calib;
                                            ^~~~~
/home/jliu/retinanet-examples/csrc/engine.cpp:118:44: note: suggested alternative: ‘scalb’
     std::unique_ptr<Int8EntropyCalibrator> calib;
                                            ^~~~~
                                            scalb
/home/jliu/retinanet-examples/csrc/engine.cpp:122:22: error: ‘unique_ptr’ is not a member of ‘std’
         calib = std::unique_ptr<Int8EntropyCalibrator>(new Int8EntropyCalibrator(stream, model_name, calibration_table));
                      ^~~~~~~~~~
/home/jliu/retinanet-examples/csrc/engine.cpp:122:22: note: suggested alternative: ‘unique_copy’
         calib = std::unique_ptr<Int8EntropyCalibrator>(new Int8EntropyCalibrator(stream, model_name, calibration_table));
                      ^~~~~~~~~~
                      unique_copy
/home/jliu/retinanet-examples/csrc/engine.cpp:122:54: error: expected primary-expression before ‘>’ token
         calib = std::unique_ptr<Int8EntropyCalibrator>(new Int8EntropyCalibrator(stream, model_name, calibration_table));
                                                      ^
CMakeFiles/retinanet.dir/build.make:110: recipe for target 'CMakeFiles/retinanet.dir/home/jliu/retinanet-examples/csrc/engine.cpp.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/home/jliu/retinanet-examples/csrc/engine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/retinanet.dir/all' failed
make[1]: *** [CMakeFiles/retinanet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yashnv** [comment]
This wouldn't have happened outside NGC container.
Add a line in `csrc/engine.cpp`:
```
#include <memory>
```
and cmake, make again.

**Comment by azuryl** [comment]
I added #include <memory.h> as you said an d build is success

the tensorrt version is 7 in PC
but in tensorrt version 6 in Xavier need not add this line is build success
