### ISSUE TITLE
where is retinanet bin

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#117]
I have build succss in retinanet-examples-19.04/extras/cppapi/build

drwxr-xr-x 3 nvidia nvidia    4096 Jan 20 15:15 ./
drwxr-xr-x 3 nvidia nvidia    4096 Jan 20 15:09 ../
-rw-r--r-- 1 nvidia nvidia   22086 Jan 20 15:10 CMakeCache.txt
drwxr-xr-x 8 nvidia nvidia    4096 Jan 20 15:30 CMakeFiles/
-rw-r--r-- 1 nvidia nvidia    1554 Jan 20 15:10 cmake_install.cmake
-rwxr-xr-x 1 nvidia nvidia 1550888 Jan 20 15:15 export*
-rwxr-xr-x 1 nvidia nvidia 1553376 Jan 20 15:15 infer*
-rw-r--r-- 1 nvidia nvidia 1815244 Jan 20 15:15 libretinanet.a
-rw-r--r-- 1 nvidia nvidia   11137 Jan 20 15:10 Makefile

**Comment by azuryl** [comment]
gdb --args  ./export  ~/retinanet_rn50fpn.pth retinanet_rn50fpn.onnx
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./export...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/nvidia/retinanet-examples-19.04/extras/cppapi/build/export /home/nvidia/retinanet_rn50fpn.pth retinanet_rn50fpn.onnx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Building engine...
[New Thread 0x7f7489f1c0 (LWP 31987)]
[New Thread 0x7f7409e1c0 (LWP 31988)]
Building FP16 core model...

Thread 1 "export" received signal SIGSEGV, Segmentation fault.
0x00000055555652e0 in retinanet::Engine::Engine(char const*, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, int, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, float, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, unsigned long) ()
(gdb) bt
#0  0x00000055555652e0 in retinanet::Engine::Engine(char const*, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, int, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, float, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, unsigned long) ()
#1  0x0000005555563140 in main ()

**Comment by yashnv** [comment]
`retinanet` is a python interface. Please use this repo in NGC Pytorch 19.10 container and follow the instructions in the README. It can be installed in container through `pip install -e --no-cache-dir retinanet-examples/`

**Comment by azuryl** [comment]
you means docker pull nvcr.io/nvidia/pytorch:19.10-py3   ?

**Comment by yashnv** [comment]
yes, and then follow instructions on the README.

**Comment by azuryl** [comment]
why if I am not use docker and   compiled by myself  there just have "export" but no "retinanet"

**Comment by yashnv** [comment]
retinanet is a python interface. You have to install it through `pip instal -e --no-cache-dir retinanet-examples/`, where `retinanet-examples/` is the cloned directory.

**Comment by azuryl** [comment]
there is error 
pip3 install -e --no-cache-dir git+https://github.com/nvidia/retinanet-examples
--no-cache-dir should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+

**Comment by azuryl** [comment]
I use 
pip3 install --no-cache-dir git+https://github.com/nvidia/retinanet-examples  as guide 

pip3 install --no-cache-dir git+https://github.com/nvidia/retinanet-examples
Collecting git+https://github.com/nvidia/retinanet-examples
  Cloning https://github.com/nvidia/retinanet-examples to /tmp/pip-vx1u5deb-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-vx1u5deb-build/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'

**Comment by azuryl** [comment]
since this project run in Xavier  ,ubuntu18.04 and python 3.6.9 how install torch ? conda or pip?
thanks

**Comment by yashnv** [comment]
Please don't install this repo on Xavier. Export .pth to .onnx on host machine. Then copy ONNX model to Xavier and then export it to .plan file. Refer to these instructions: https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi

**Comment by azuryl** [comment]
I just tried in X86 PC the build is ok  
https://github.com/NVIDIA/retinanet-examples/issues/116

but finnaly I need run this example is Xavier not just convert to ONNX case.

**Comment by yashnv** [comment]
use your exported ONNX model in your Xavier. Export it to .plan using extras/csrc/export. Then use do inference on it. Until the ONNX model file is not system dependent. A .plan file is system dependent.

**Comment by azuryl** [comment]
now in X86
I watched https://github.com/NVIDIA/retinanet-examples/issues/15 installed opencv
then
retinanet export -h
Traceback (most recent call last):
  File "/home/jliu/anaconda3/envs/py374/bin/retinanet", line 11, in <module>
    load_entry_point('retinanet', 'console_scripts', 'retinanet')()
  File "/home/jliu/anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jliu/anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/jliu/anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/jliu/anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jliu/retinanet-examples_local/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/home/jliu/retinanet-examples_local/retinanet/infer.py", line 13, in <module>
    from .model import Model
  File "/home/jliu/retinanet-examples_local/retinanet/model.py", line 8, in <module>
    from ._C import Engine
ImportError: /home/jliu/retinanet-examples_local/retinanet/_C.so: undefined symbol: _ZN2cv8fastFreeEPv

**Comment by hcx1231** [comment]
> now in X86
> 1.I watched #15 installed opencv
> and extend the library in setup.py as follows:
> libraries=['nvinfer', 'nvinfer_plugin', 'nvonnxparser', 'opencv_core', 'opencv_highgui', 'opencv_imgproc', 'opencv_imgcodecs'])
> 
> 2 pip install --no-cache-dir -e retinanet-examples_local
> Obtaining file:///home/jliu/retinanet-examples_local
> Requirement already satisfied: torch>=1.0.0a0 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from retinanet==0.1) (1.4.0)
> Requirement already satisfied: torchvision in ./anaconda3/envs/py374/lib/python3.7/site-packages (from retinanet==0.1) (0.5.0)
> Requirement already satisfied: apex@ git+https://github.com/NVIDIA/apex from git+https://github.com/NVIDIA/apex in ./anaconda3/envs/py374/lib/python3.7/site-packages (from retinanet==0.1) (0.1)
> Requirement already satisfied: pycocotools@ git+https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI from git+https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI in ./anaconda3/envs/py374/lib/python3.7/site-packages (from retinanet==0.1) (2.0+nv0.3.1)
> Collecting pillow==6.2.2
> Downloading https://files.pythonhosted.org/packages/c3/3f/03375124676ab49ca6e6917c0f1f663afb8354d5d24e12f4fe4587a39ae2/Pillow-6.2.2-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
> |████████████████████████████████| 2.1MB 3.0MB/s
> Requirement already satisfied: requests in ./anaconda3/envs/py374/lib/python3.7/site-packages (from retinanet==0.1) (2.22.0)
> Requirement already satisfied: numpy in ./anaconda3/envs/py374/lib/python3.7/site-packages (from torchvision->retinanet==0.1) (1.18.1)
> Requirement already satisfied: six in ./anaconda3/envs/py374/lib/python3.7/site-packages (from torchvision->retinanet==0.1) (1.13.0)
> Requirement already satisfied: setuptools>=18.0 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (44.0.0.post20200106)
> Requirement already satisfied: cython>=0.27.3 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (0.29.14)
> Requirement already satisfied: matplotlib>=2.1.0 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (3.1.2)
> Requirement already satisfied: pybind11>=2.2 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (2.4.3)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from requests->retinanet==0.1) (1.25.7)
> Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from requests->retinanet==0.1) (2019.11.28)
> Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from requests->retinanet==0.1) (2.8)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from requests->retinanet==0.1) (3.0.4)
> Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from matplotlib>=2.1.0->pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (1.1.0)
> Requirement already satisfied: cycler>=0.10 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from matplotlib>=2.1.0->pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (0.10.0)
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from matplotlib>=2.1.0->pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (2.4.6)
> Requirement already satisfied: python-dateutil>=2.1 in ./anaconda3/envs/py374/lib/python3.7/site-packages (from matplotlib>=2.1.0->pycocotools@ git+[https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI->retinanet==0.1](https://github.com/nvidia/cocoapi.git#subdirectory=PythonAPI-%3Eretinanet==0.1)) (2.8.1)
> Installing collected packages: pillow, retinanet
> Found existing installation: Pillow 7.0.0
> Uninstalling Pillow-7.0.0:
> Successfully uninstalled Pillow-7.0.0
> Found existing installation: retinanet 0.1
> Uninstalling retinanet-0.1:
> Successfully uninstalled retinanet-0.1
> Running setup.py develop for retinanet
> Successfully installed pillow-6.2.2 retinanet
> 
> 3.then
> retinanet export -h
> retinanet export -h
> Traceback (most recent call last):
> File "/home/anaconda3/envs/py374/bin/retinanet", line 11, in
> load_entry_point('retinanet', 'console_scripts', 'retinanet')()
> File "/home/anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/**init**.py", line 489, in load_entry_point
> return get_distribution(dist).load_entry_point(group, name)
> File "/home/anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/**init**.py", line 2852, in load_entry_point
> return ep.load()
> File "/home/anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/**init**.py", line 2443, in load
> return self.resolve()
> File "/home//anaconda3/envs/py374/lib/python3.7/site-packages/pkg_resources/**init**.py", line 2449, in resolve
> module = **import**(self.module_name, fromlist=['**name**'], level=0)
> File "/home/retinanet-examples_local/retinanet/main.py", line 10, in
> from retinanet import infer, train, utils
> File "/home/retinanet-examples_local/retinanet/infer.py", line 13, in
> from .model import Model
> File "/home/retinanet-examples_local/retinanet/model.py", line 8, in
> from ._C import Engine
> ImportError: /home/retinanet-examples_local/retinanet/_C.so: undefined symbol: _ZN2cv6imreadERKSsi

I met the same problem.Have you solved it?
