### ISSUE TITLE
How to use after installation

### ISSUE THREAD

**Issue by FenryrMKIII** [NVIDIA/retinanet-examples#120]
I followed the recommended installation procedure i.e. executing : 

docker run --gpus all --rm --ipc=host -it nvcr.io/nvidia/pytorch:19.10-py3
pip install --no-cache-dir git+https://github.com/nvidia/retinanet-examples

on a Google Cloud VM. However, following successful termination, I don't have any directory in my workspace directory. So I created a directory named `retinanet` which holds the weights named `retinanet_rn50fpn.pth`. I launch the utility with the following command : 

`retinanet infer ~/../workspace/retinanet/retinanet_rn50fpn.pth --images /coco/images/val2017/ --annotations /coco/annotations/instances_val2017.json`

where the path to the weight file is the absolute path (checked - it's the correct one). However, the utility throws me an error `RuntimeError: Model file /root/../workspace/retinanet/retinanet_rn50fpn.pth does not exist!`. 

I assume it's because I don't understand the structure and where everything has been installed.

Any help ?

**Comment by yashnv** [comment]
You did not clone the repository.
```
cd /workspace
git clone https://github.com/NVIDIA/retinanet-examples.git
```
then
```
pip install --no-cache-dir -e /workspace/retinanet-examples/
```
