### ISSUE TITLE
fatal error: nvdsinfer_custom_impl.h: No such file or directory

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#122]
. (on Jetson) Make the RetinaNet plugin

cd extras/deepstream/deepstream-sample
mkdir build && cd build
cmake -DDeepStream_DIR=/opt/nvidia/deepstream/deepstream-4.0 .. && make -j

nvidia@nvidia-desktop:~/retinanet-examples/extras/deepstream/deepstream-sample/build$ make -j
[ 20%] Building CXX object CMakeFiles/nvdsparsebbox_retinanet.dir/nvdsparsebbox_retinanet.cpp.o
/home/nvidia/retinanet-examples/extras/deepstream/deepstream-sample/nvdsparsebbox_retinanet.cpp:14:10: fatal error: nvdsinfer_custom_impl.h: No such file or directory
 #include "nvdsinfer_custom_impl.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/nvdsparsebbox_retinanet.dir/build.make:1727: recipe for target 'CMakeFiles/nvdsparsebbox_retinanet.dir/nvdsparsebbox_retinanet.cpp.o' failed
make[2]: *** [CMakeFiles/nvdsparsebbox_retinanet.dir/nvdsparsebbox_retinanet.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nvdsparsebbox_retinanet.dir/all' failed
make[1]: *** [CMakeFiles/nvdsparsebbox_retinanet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yashnv** [comment]
What's the output of `ls -la /opt/nvidia/deepstream/deepstream-4.0/`?

**Comment by azuryl** [comment]
> What's the output of `ls -la /opt/nvidia/deepstream/deepstream-4.0/`?
> Also what is the Jetpack version? Was Deepstream installed with Jetpack?

 jetson_release
 - NVIDIA Jetson AGX Xavier
   * Jetpack 4.3 [L4T 32.3.1]
   * CUDA GPU architecture 7.2
   * NV Fan Mode:quiet - Type: NV Power Mode: MODE_15W
 - Libraries:
   * CUDA 10.0.326
   * cuDNN 7.6.3.28-1+cuda10.0
   * TensorRT 6.0.1.10-1+cuda10.0
   * Visionworks 1.6.0.500n
   * OpenCV 4.1.1 compiled CUDA: YES
 - Jetson Performance: inactive

**Comment by yashnv** [comment]
What's the output of `ls -la /opt/nvidia/deepstream/deepstream-4.0/`?

Was Deepstream installed with Jetpack?

**Comment by azuryl** [comment]
it was by  git clone in //home/nvidia/project/retinanet-examples/extras/deepstream/deepstream-sample

drwxr-xr-x 3 nvidia nvidia 4096 Jan 26 14:56 build
-rw-r--r-- 1 nvidia nvidia 1035 Jan 26 13:04 CMakeLists.txt
-rw-r--r-- 1 nvidia nvidia 1447 Jan 26 13:04 ds_config_1vid.txt
-rw-r--r-- 1 nvidia nvidia 1610 Jan 26 13:04 ds_config_8vid.txt
-rw-r--r-- 1 nvidia nvidia 2752 Jan 26 13:04 infer_config_batch1.txt
-rw-r--r-- 1 nvidia nvidia 2782 Jan 26 13:04 infer_config_batch8.txt
-rw-r--r-- 1 nvidia nvidia  699 Jan 26 13:04 labels_coco.txt
-rw-r--r-- 1 nvidia nvidia 3615 Jan 26 13:04 nvdsparsebbox_retinanet.cpp

**Comment by azuryl** [comment]
/project/retinanet-examples/extras$ ls -la /opt/nvidia/
total 24
drwxr-xr-x 6 root root 4096 Jan 26 12:08 .
drwxr-xr-x 7 root root 4096 Jan 26 14:25 ..
drwxrwxrwx 2 root root 4096 Jan 26 12:13 deb_repos
drwxr-xr-x 6 root root 4096 Jan 19 21:10 jetson-io
drwxr-xr-x 2 root root 4096 Jan 26 11:45 l4t-usb-device-mode
drwxr-xr-x 3 root root 4096 Jan 26 12:08 vpi

**Comment by yashnv** [comment]
You have to install DeepStream with the jetpack, for the deepstream featureds to work.

**Comment by azuryl** [comment]
how to  install DeepStream with the jetpack ?
I watched the README

5. (on Jetson) Make the RetinaNet plugin

```bash
cd extras/deepstream/deepstream-sample
mkdir build && cd build
cmake -DDeepStream_DIR=/opt/nvidia/deepstream/deepstream-4.0 .. && make -j
```

**Comment by azuryl** [comment]
and I watched there are no DeepStream folder in /opt/nvidia/  by ls -la
