### ISSUE TITLE
Good performance on Jetson TX2

### ISSUE THREAD

**Issue by aidonchuk** [NVIDIA/retinanet-examples#123]
Hi! Benchmark for resnet18fpn with 1 class on 320x256 image looks nice --- 0.02644181251525879 seconds ---

Do you have any ideas why resnet34fpn on 10 classes shows only --- 0.47 seconds?
 Huge difference looks suspiciously.

**Comment by yashnv** [comment]
Inference on Jetson TX2 with 10 classes is a heavy compute task involving Non Maximum Suppresion. This is not a big factor in case with a single class. So this amount of time is expected.
