### ISSUE TITLE
 need install pytorch in Xavier ?

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#125]
I watched  pytorch is installed in docker

but NVIDIA Jetson AGX Xavier have no  pytorch

 need install pytorch in Xavier ?

**Comment by james-nvidia** [comment]
We have used this repo on a machine with a Tesla GPU and then exported our model as an ONNX file. The Jetson Xavier only sees the ONNX model, so does not need Pytorch.

If will be possible for you to run this repo on a Jetson Xavier, but you will need to install nvidia-docker.

**Comment by azuryl** [comment]
@james-nvidia I  can not use nvidia-docker in Xavier because my program is just a part of the whole project

**Comment by james-nvidia** [comment]
I suggest you either run your entire programme in a docker container, or you produce your ONNX model on another machine (as we did) and use the TensorRT engine in your project. The TensorRT engine will give far superior inference performance.
Please open an issue with a specific problem if you are having a problem.

**Comment by BADAL244** [comment]
https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html
