### ISSUE TITLE
how to install DeepStream SDK

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#126]
there two guide 
**first one**
in https://github.com/NVIDIA/retinanet-examples/tree/master/extras/deepstream
    (on Jetson) Make the RetinaNet plugin

cd extras/deepstream/deepstream-sample
mkdir build && cd build
cmake -DDeepStream_DIR=/opt/nvidia/deepstream/deepstream-4.0 .. && make -j

**but there are another guide**
https://docs.nvidia.com/metropolis/deepstream/4.0/dev-guide/index.html
Copy the generated libraries to the deepstream directory:
$ sudo mkdir -p /opt/nvidia/deepstream/deepstream-4.0/lib 
$ sudo cp /usr/local/lib/librdkafka* /opt/nvidia/deepstream/deepstream-4.0/lib
To install the DeepStream SDK
• Method 1: Using the DeepStream Debian package
Download the DeepStream 4.0 dGPU Debian package, deepstream-4.0_4.0-1_amd64.deb, then enter the command:
$ sudo apt-get install ./deepstream-4.0_4.0-1_amd64.deb

which one I will use,the first have fatel error when   make
https://github.com/NVIDIA/retinanet-examples/issues/122

**Comment by james-nvidia** [comment]
Which Jetson are you using? When you flash the device, there's an option that you need to tick called "install DeepStream SDK". That is the easiest way of installing DeepStream.

I will be flashing my Xavier this week. I'll take a screenshot of this step.

**Comment by azuryl** [comment]
@james-nvidia 
jetson_release

    NVIDIA Jetson AGX Xavier
        Jetpack 4.3 [L4T 32.3.1]
        CUDA GPU architecture 7.2
        NV Fan Mode:quiet - Type: NV Power Mode: MODE_15W
    Libraries:
        CUDA 10.0.326
        cuDNN 7.6.3.28-1+cuda10.0
        TensorRT 6.0.1.10-1+cuda10.0
        Visionworks 1.6.0.500n
        OpenCV 4.1.1 compiled CUDA: YES
    Jetson Performance: inactive

**Comment by james-nvidia** [comment]
Did you get DeepStream installed?

**Comment by james-nvidia** [comment]
Closed due to inactivity.

**Comment by azuryl** [comment]
>  will be flashing m

I waited you take a screenshot of this step
