### ISSUE TITLE
where is INT8CalibrationTable file

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#127]
I download weights file from https://github.com/NVIDIA/retinanet-examples/releases/tag/19.04
but there is no https://github.com/NVIDIA/retinanet-examples/releases/tag/19.04

in https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi

"export the ONNX core model to an INT8 TensorRT engine if you have already done INT8 calibration:

export model.onnx engine.plan INT8CalibrationTable" this case need INT8CalibrationTable

**Comment by KNaudin** [comment]
From the README. [int8 inference with tensorrt](https://github.com/NVIDIA/retinanet-examples#int8-inference-with-tensorrt)
You create it during the export to ONNX.

**Comment by azuryl** [comment]
@KNaudin thank you help

retinanet export retinanet_rn50fpn.pth retinanet_rn50fpn_engine.plan --int8 --calibration-images /workspace/val2017
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Exporting to ONNX...
Building INT8 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
Writing to retinanet_rn50fpn_engine.plan...

 the output file: retinanet_rn50fpn_engine.plan is ONNX format?

**Comment by james-nvidia** [comment]
The `.plan` file is a TensorRT engine. It is an extremely efficient representation of your model. You can infer using the C++ API provided, or using one of the NVIDIA SDKs, such as DeepStream (for video).
Remember that you can only use the TensorRT engine on the device in which it was built, as it has been optimised for that exact architecture and batch size.

Since you have successfully exported your model in INT8 precision, I'll close this issue.

**Comment by azuryl** [comment]
@KNaudin  I according to  your guide
retinanet infer retinanet_rn50fpn_engine.plan --images val2017/   --annotations annotations/instances_val2017.json
Loading CUDA engine from retinanet_rn50fpn_engine.plan...
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
Preparing dataset...
    loader: pytorch
    resize: 800, max: 1280
   backend: tensorrt
    device: 2 gpus
     batch: 4, precision: unknown
Running inference...
[3256/5000] 0.074s/4-batch (fw: 0.054s), 54.3 im/s
[5000/5000] 0.071s/4-batch (fw: 0.055s), 56.6 im/s
Gathering results...

Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 183, in main
    torch.multiprocessing.spawn(worker, args=(args, world, model, state), nprocs=world)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 136, in worker
    is_master=(rank == 0), world=world, use_dali=args.with_dali, verbose=(rank == 0))
  File "/opt/conda/lib/python3.6/site-packages/retinanet/infer.py", line 89, in infer
    torch.distributed.all_gather(list(all_result), result)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1142, in all_gather
    work = _default_pg.allgather([tensor_list], [tensor])
RuntimeError: CUDA error: out of memory (initDeviceStreamState at ../c10/cuda/CUDAStream.cpp:236)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6c (0x7f66b420f28c in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xd288 (0x7f66b4435288 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0xf827 (0x7f66b9874827 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #3: c10::cuda::getStreamFromPool(bool, short) + 0x132 (0x7f66b4432b12 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #4: c10d::ProcessGroupNCCL::getNCCLComm(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<c10::Device, std::allocator<c10::Device> > const&) + 0x4c3 (0x7f66b5b02c73 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x7ecb31 (0x7f66b5b07b31 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: c10d::ProcessGroupNCCL::allgather(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >&, std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllgatherOptions const&) + 0x64 (0x7f66b5b08d94 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x76f982 (0x7f66b5a8a982 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x1d001c (0x7f66b54eb01c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: _PyCFunction_FastCallDict + 0x154 (0x564472c33c54 in /opt/conda/bin/python)
frame #10: <unknown function> + 0x199c0e (0x564472cbbc0e in /opt/conda/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x30a (0x564472cde75a in /opt/conda/bin/python)
frame #12: <unknown function> + 0x192e66 (0x564472cb4e66 in /opt/conda/bin/python)
frame #13: <unknown function> + 0x193e73 (0x564472cb5e73 in /opt/conda/bin/python)
frame #14: <unknown function> + 0x199b95 (0x564472cbbb95 in /opt/conda/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x30a (0x564472cde75a in /opt/conda/bin/python)
frame #16: <unknown function> + 0x19329e (0x564472cb529e in /opt/conda/bin/python)
frame #17: <unknown function> + 0x193ed6 (0x564472cb5ed6 in /opt/conda/bin/python)
frame #18: <unknown function> + 0x199b95 (0x564472cbbb95 in /opt/conda/bin/python)
frame #19: _PyEval_EvalFrameDefault + 0x10cc (0x564472cdf51c in /opt/conda/bin/python)
frame #20: PyEval_EvalCodeEx + 0x966 (0x564472cb6ff6 in /opt/conda/bin/python)
frame #21: <unknown function> + 0x1957d4 (0x564472cb77d4 in /opt/conda/bin/python)
frame #22: PyObject_Call + 0x3e (0x564472c33a5e in /opt/conda/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x19e7 (0x564472cdfe37 in /opt/conda/bin/python)
frame #24: PyEval_EvalCodeEx + 0x329 (0x564472cb69b9 in /opt/conda/bin/python)
frame #25: <unknown function> + 0x1958e6 (0x564472cb78e6 in /opt/conda/bin/python)
frame #26: PyObject_Call + 0x3e (0x564472c33a5e in /opt/conda/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x19e7 (0x564472cdfe37 in /opt/conda/bin/python)
frame #28: <unknown function> + 0x193c5b (0x564472cb5c5b in /opt/conda/bin/python)
frame #29: <unknown function> + 0x199b95 (0x564472cbbb95 in /opt/conda/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x30a (0x564472cde75a in /opt/conda/bin/python)
frame #31: <unknown function> + 0x193c5b (0x564472cb5c5b in /opt/conda/bin/python)
frame #32: <unknown function> + 0x199b95 (0x564472cbbb95 in /opt/conda/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x30a (0x564472cde75a in /opt/conda/bin/python)
frame #34: <unknown function> + 0x193c5b (0x564472cb5c5b in /opt/conda/bin/python)
frame #35: <unknown function> + 0x199b95 (0x564472cbbb95 in /opt/conda/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x30a (0x564472cde75a in /opt/conda/bin/python)
frame #37: <unknown function> + 0x192e66 (0x564472cb4e66 in /opt/conda/bin/python)
frame #38: <unknown function> + 0x193ed6 (0x564472cb5ed6 in /opt/conda/bin/python)
frame #39: <unknown function> + 0x199b95 (0x564472cbbb95 in /opt/conda/bin/python)
frame #40: _PyEval_EvalFrameDefault + 0x10cc (0x564472cdf51c in /opt/conda/bin/python)
frame #41: PyEval_EvalCodeEx + 0x329 (0x564472cb69b9 in /opt/conda/bin/python)
frame #42: PyEval_EvalCode + 0x1c (0x564472cb775c in /opt/conda/bin/python)
frame #43: <unknown function> + 0x215744 (0x564472d37744 in /opt/conda/bin/python)
frame #44: PyRun_StringFlags + 0x7d (0x564472d377dd in /opt/conda/bin/python)
frame #45: PyRun_SimpleStringFlags + 0x3f (0x564472d3783f in /opt/conda/bin/python)
frame #46: Py_Main + 0x423 (0x564472d3b643 in /opt/conda/bin/python)
frame #47: main + 0xee (0x564472c0588e in /opt/conda/bin/python)
frame #48: __libc_start_main + 0xe7 (0x7f66b9495b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #49: <unknown function> + 0x1c3160 (0x564472ce5160 in /opt/conda/bin/python)

**Comment by james-nvidia** [comment]
You have an out of memory error. Try inferring with a smaller batch size.

    CUDA error: out of memory (initDeviceStreamState at ../c10/cuda/CUDAStream.cpp:236)

**Comment by yashnv** [comment]
> Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.

You should also export the engine plan file on the same device on which you are inferring. **This is important.**

**Comment by azuryl** [comment]
@yashnv I export the engine plan file on the docker is same device

**Comment by azuryl** [comment]
@james-nvidia  I am not successfully exported your model in INT8 precision in Xavier, since it can't  run
"retinanet export retinanet_rn50fpn.pth retinanet_rn50fpn_engine.plan --int8 --calibration-images /workspace/val2017"  on Xavier

**Comment by azuryl** [comment]
@james-nvidia  can you tell me how to install retinanet example  outside docker in Xavier, if it insatll success I can run "retinanet export model.pth engine.plan --int8 --calibration-images /coco/images/val2017/"
