### ISSUE TITLE
in Xavier how to run "retinanet export ..."

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#128]
since   install retinanet-examples  is failed the issue is
https://github.com/NVIDIA/retinanet-examples/issues/119
in Xavier  I can just build  C++ in retinanet-examples/extras/cppapi
 https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi

there are just have export  model.onnx engine.plan INT8CalibrationTable  but there are no INT8CalibrationTable
and can not run "retinanet export model.pth engine.plan --int8 --calibration-images /coco/images/val2017/" like in docker
can you tell me how solve it

**Comment by yashnv** [comment]
Please don't open multiple issues related to a similar topic. You can continue to ask your questions in the other already existing issues opened by you. Closing this now.

**Comment by azuryl** [comment]
I am not successfully exported your model in INT8 precision in Xavier  https://github.com/NVIDIA/retinanet-examples/issues/127
but james-nvidia closed
