### ISSUE TITLE
Feature enhancement: Live video streaming? (prior to incorperating Deepstream)

### ISSUE THREAD

**Issue by mbufi** [NVIDIA/retinanet-examples#13]
Hi! 
Great work on the repo! It is done fantastically and I am learning lots from it. 

Is there any future enhancements to the project related to live feed? I know you mentioned incorporating Deep stream @ GTC but until that is accomplished, how do you think we could incorporate our own cameras to use the model?

**Comment by pkashinkunti** [comment]
Thanks for your feedback!

We are working on integrating retinanet models with deepstream, and will post an example to the repo when it is available. No ETA to share at this point.
