### ISSUE TITLE
there is no  /opt/conda/envs/pytorch-py35 in docker

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#131]
In the docker README said "This container has the PyTorch framework installed and ready to use. The pytorch python module is installed as part of a Python 3.5 Conda environment in
/opt/conda/envs/pytorch-py35."
but 
root@7052497e95e9:/workspace# ll /opt/conda/envs/pytorch-py35
ls: cannot access '/opt/conda/envs/pytorch-py35': No such file or directory
root@7052497e95e9:/workspace#

**Comment by yashnv** [comment]
@azuryl 

- What README are you referring to? 

- What container version is this?

Please be specific.

**Comment by azuryl** [comment]
nvcr.io/nvidia/pytorch:19.10-py3
in /workspace/README.md

**Comment by yashnv** [comment]
That README is not related to this project, and comes preconfigured from 19.10 container. Closing this now.

**Comment by azuryl** [comment]
I am  pre-configure the project outside the docker according to the 19.10 container README
