### ISSUE TITLE
An implementation issue of plugin components (c++)

### ISSUE THREAD

**Issue by kaishian** [NVIDIA/retinanet-examples#136]
Both **DecodePlugin** ([code](https://github.com/NVIDIA/retinanet-examples/blob/master/csrc/plugins/DecodePlugin.h#L141)) and **NMSPlugin** ([code](https://github.com/NVIDIA/retinanet-examples/blob/master/csrc/plugins/NMSPlugin.h#L113)) have a static variable in getWorkspaceSize() function.

When the application initialize more than one RetinaNet models (instance) in a process, this static variable may cause race condition issue. I suggest using "mutable member variable" instead of it. For example:

```
class DecodePlugin {
private:
    mutable int workspace_sz = 0;
};
```

**Comment by aidonchuk** [comment]
Hmm, I have problem initializing to model in same processes. Thx a lot I'll try this.

**Comment by yashnv** [comment]
@kaishian thanks for the foresight. Can you share an example of any problems you encountered while initializing more than 1 model? It would be helpful to investigate upon this.

**Comment by james-nvidia** [comment]
@kaishian or @aidonchuk Any update on this?

**Comment by aidonchuk** [comment]
@james-nvidia sorry I was on holidays) I'll check next week

**Comment by aidonchuk** [comment]
I can't compile pls provide working example.
`    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from csrc/engine.cpp:31:0:
    csrc/plugins/DecodePlugin.h: In member function ‘virtual size_t retinanet::DecodePlugin::getWorkspaceSize(int) const’:
    csrc/plugins/DecodePlugin.h:132:17: error: non-member ‘size’ cannot be declared ‘mutable’
         mutable int size = -1;
                     ^~~~
    In file included from csrc/engine.cpp:32:0:
    csrc/plugins/NMSPlugin.h: In member function ‘virtual size_t retinanet::NMSPlugin::getWorkspaceSize(int) const’:
    csrc/plugins/NMSPlugin.h:112:17: error: non-member ‘size’ cannot be declared ‘mutable’
         mutable int size = -1;
                     ^~~~
    csrc/engine.cpp: In member function ‘virtual void retinanet::Logger::log(nvinfer1::ILogger::Severity, const char*)’:
    csrc/engine.cpp:47:55: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
             if (_verbose || (severity != Severity::kINFO) && (severity != Severity::kVERBOSE))
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1
`

**Comment by james-nvidia** [comment]
Can you send us the exact commands you ran, including the container and hardware? Thanks

**Comment by aidonchuk** [comment]
git clone https://github.com/nvidia/retinanet-examples
docker build -t retinanet:latest retinanet-examples/
1080ti, AMD Ubuntu 18 latest docker and etc.

as @kaishian write I changed first and only one static var to mutable. 
I think @kaishian have to give working code

But it possible that i make mistake because I don't know cpp and don't have time smoke manuals =) sorry...

**Comment by yashnv** [comment]
You have to declare it as a private member for the plugin class and comment the line `static int size = -1;`

**Comment by kaishian** [comment]
the member variable  '_ws_size' have to initialize as -1 in constructor.
I hope following piece of code helps:

```
class DecodePlugin : public IPluginV2 {
  mutable int _ws_size;
  
public:
  DecodePlugin(float score_thresh, int top_n, std::vector<float> const& anchors, int scale)
	: _score_thresh(score_thresh), _top_n(top_n), _anchors(anchors), _scale(scale), _ws_size(-1)
	, _height(0), _width(0), _num_anchors(0), _num_classes(0) {}

  DecodePlugin(void const* data, size_t length)
	: _score_thresh(0), _top_n(0), _anchors(), _scale(0), _ws_size(-1)
	, _height(0), _width(0), _num_anchors(0), _num_classes(0) {
	  this->deserialize(data, length);
  }
  
  size_t getWorkspaceSize(int maxBatchSize) const override {
	if (_ws_size < 0) {
	  _ws_size = decode(maxBatchSize, nullptr, nullptr, _height, _width, _scale,
		_num_anchors, _num_classes, _anchors, _score_thresh, _top_n, 
		nullptr, 0, nullptr);
	}
	return _ws_size;
  }
};
```

**Comment by yashnv** [comment]
@kaishian can you please share an example of any race condition that you found while initializing multiple models?

**Comment by james-nvidia** [comment]
Is this still a problem?

**Comment by yashnv** [comment]
@kaishian @aidonchuk can one of you guys share an example of a before/after using `mutable` in your case of multiple models?

If this fixes the multiple models, single process issue, I'll update the repository.

**Comment by kaishian** [comment]
The answer is YES, please update it to respository.

Here is my case before changing "static variable":
1. We need to analyze 12+ video streaming with one process.
2. This process will need to load 4 different DNN models (RetinaNet) in the beginning.
3. This process will create 4 instance of <IExecutionContext>, which means it will create <DecodePlugin> and <NMSPlugin> multiple times.
3. The "static variable" will accummulate the size of workspace in these 4 models
4. Eventually, the TensorRT will complaint about the workspace is too large when creating <ExecutionContext> object.

My solution is simply change the static-variable to member-variable, it will avoid the workspace-accummulate problem happened again. BTW, "mutable" is needed if changed member variable in constant member function.

I hope these information is helpful to you.
