### ISSUE TITLE
Low mAP on custom dataset

### ISSUE THREAD

**Issue by jsn5** [NVIDIA/retinanet-examples#138]
Hi, 
I'm trying to fineture retinanet for a custom dataset. I have around 5000 annotated images. 
I'm using a single GTX 1080ti with a batch size of 5. 

Here is my mAP score after 50000 iterations.

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.00224                                                                                                                           
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.00437                                                                                                                           
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.00207                                                                                                                           
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.00000                                                                                                                          
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.00126                                                                                                                           
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.00276                                                                                                                           
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.01714                                                                                                                           
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.01969                                                                                                                           
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.01969                                                                                                                           
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.00000                                                                                                                          
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.01031                                                                                                                           
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.02279

I've been trying different backbones, learning rates, warmup steps etc. But the mAP score is not improving. Any suggestions?

**Comment by jsn5** [comment]
Never mind. Was an issue with the dataset. Working well now.

**Comment by spcrobocar** [comment]
I have the same problem. Can you share what issue you found in your dataset?
