### ISSUE TITLE
run models in TRTIS

### ISSUE THREAD

**Issue by ishantbansal** [NVIDIA/retinanet-examples#139]
i tried to run these generated models on TRTIS but not successful . 
is it possible to do so ?

**Comment by james-nvidia** [comment]
It certainly should be possible. Did you successfully build a TensorRT engine?
If you problem is with TRTIS itself, please ask a question here: https://devtalk.nvidia.com/default/board/262/container-inference-server/

**Comment by ishantbansal** [comment]
yes .plan files are successfully generated but while loading into TRTIS , i need plugin .so file to load . where i can find that file ? in retinanet installation

**Comment by james-nvidia** [comment]
Build the C++ API and it will create the `.so` plugin you need
https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi#linux

Please let me know how this goes.

**Comment by yashnv** [comment]
@ishantbansal make sure to change [this](https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/CMakeLists.txt#L15) to ` add_library(retinanet SHARED` for shared, PIC library.

**Comment by ishantbansal** [comment]
I built library & it successfully loaded in TRTIS .
but is there no way i can enable batching with this model ? as tensort7 is not supporting and for TRT 6 i tried building from 19.10 docker but this error 
" (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input "
is there

**Comment by yashnv** [comment]
Use branch 19.10 for TRT6

**Comment by ishantbansal** [comment]
thanks .. 
was able to run on TRTIS 
& got benchmarks which i wanted

**Comment by ishantbansal** [comment]
solution - 
build .so file as instructed above by yash
get model from pytorch docker ( make sure to have tensorrt version same as TRTIS docker you want to run on ) 
to load use this command - 
LD_PRELOAD=libretinanet.so trtserver --model-repository=/models/retinanet50int8/ --strict-model-config=false
