### ISSUE TITLE
Misunderstanding: How to run ONNX model on the Xavier

### ISSUE THREAD

**Issue by mbufi** [NVIDIA/retinanet-examples#14]
I have successfully trained a full resnet50 model from scratch, along with exporting and inferring with all different precision. This works great on my host Linux computer but I am failing to use my resnet50.onnx model on my Xavier. 

Could you elaborate how I can use my onnx model on my Jetson? 
`mkdir build && cd build
cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++11" ..
make`

Is all it mentions about getting the cppapi to work. If i clone the repo on my xavier and run these commands it does not work because there is no CMakelists.txt available.

Perhaps I am going at this all wrong. Could you please let me know how you managed to get it to run on the Xavier? Thanks!

**Comment by pkashinkunti** [comment]
Hey mbufi, glad to hear things are working well for you so far!

It sounds like you already have your ONNX model on your Xavier and have cloned the repo there as well, which are the correct first steps.

The code you will need to build to build the TensorRT engine on Xavier is here: https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi

Navigate to this path in your cloned repo on Xavier (this is where the `CMakeLists.txt` file you need resides) then run the `mkdir build && ....` commands you show above to compile the `export` and `infer` applications.

Export your ONNX model to TensorRT by running `./export model.onnx model.plan`. After that you can try running inference with the produced engine by running `./infer model.plan some_image.jpg`

**Comment by mbufi** [comment]
@pkashinkunti Thanks for the great information! 

I got it compiled and exported my model. I only run into one issue which is using `./infer`:

> nvidia@jetson-0423418004106:~/ai/retinanet-examples/extras/cppapi/build$ ./infer retinanet_50.plan huskies.jpg
> Loading engine...
> Preparing data...
> OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /home/ubuntu/opencvbuild/opencv/modules/imgproc/src/resize.cpp, line 3289
> terminate called after throwing an instance of 'cv::Exception'
>   what():  /home/ubuntu/opencvbuild/opencv/modules/imgproc/src/resize.cpp:3289: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
> 
> Aborted (core dumped)
> 

The image I am providing it is the typical huskies image that is available in the other repos of Nvidia. It is 640x480 dimensions. 

Please let me know why this may be happing.

Again, thank you for the great repo and help :)

**Comment by pkashinkunti** [comment]
I don't have access to my Jetson Xavier at the moment, but I was able to run this on my V100 system:

```
root@356d0bc00fd8:/workspace/retinanet-examples/extras/cppapi/build# ./infer model.plan crab.jpg 
Loading engine...
Preparing data...
Running inference...
Took 0.0210572 seconds per inference.
```

Can you confirm the path to the huskies image is correct? (Based on your cmd above, it should be in `~/ai/retinanet-examples/extras/cppapi/build`?) Or you can try providing the full image path instead.

**Comment by mbufi** [comment]
@pkashinkunti  It was in the wrong folder :disappointed: 

It works now! 

> nvidia@jetson-0423418004106:~/ai/retinanet-examples/extras/cppapi/build$ ./infer retinanet_50.plan huskies.jpg 
> Loading engine...
> Preparing data...
> Running inference...
> Took 0.0758116 seconds per inference.

Do you have plans to include live webcam/video stream into the code?

**Comment by mbufi** [comment]
@pkashinkunti Along with my question for live webcam streaming, I am actually having some more difficulties with inference on images :cry: 

When I run my model on an image it is not detecting anything. See below:
![detections](https://user-images.githubusercontent.com/7716574/57139538-8ae64180-6d83-11e9-9276-b22ab14bebb4.png)

Additionally, It resized it to 800x1280 and saved the image with no detections. Do you know why this may be happening? 

it would be nice to have it not save the resized image but actually the original image with the bounding boxes. If not,  the image comes out all distorted with improper proportions.

**Comment by pkashinkunti** [comment]
The results you’ll get highly depend on the model used and how/what dataset it was trained on. For this specific image, note that there is no “crab” category in the COCO dataset, so you won’t have a relevant detection if you’re using a model trained on COCO. Please make sure you train with relevant model/data and feel free to open a new issue if you think a bug is present in the codebase with clear reproduction steps and relevant data.

Regarding the resizing, the cppapi code is more of an example to adapt to your own needs so feel free to play with it to make it behave the way you want!

**Comment by mbufi** [comment]
@pkashinkunti  I actually tested it with a picture of a chair and still faced the same issue. Would you like me to open a new issue or just continue with this thread?

**Comment by florischabert** [comment]
As you can imagine, this is not easy for us to debug with the information given.

Here are a few potential causes for this issue that you can verify:
1. The model has not been trained well enough: check that you get the expected mAP when running `retinanet infer` with annotations on COCO val2017 if you trained on COCO. Note that we will offer pre-trained models very soon.
2. The specific model isn't good enough on the specific image: try to run the image trough `retinanet infer` and double check that you have the right detection. If not you might want to tweak the model, use a different backbone, etc.
3. A potential bug in the cppapi example: If 1. and 2. work but you still don't get any detection from the cppapi example, please open a specific issue mentioning this with the images, model, etc.
