### ISSUE TITLE
Pytorch docker container fails to run on Jetson Nano 

### ISSUE THREAD

**Issue by Sushil-Thapa** [NVIDIA/retinanet-examples#140]
- Flashed with the latest Jetpack
- Downloaded the container by
`docker run --gpus all --rm --ipc=host -it nvcr.io/nvidia/pytorch:19.10-py3
`
or 
`
docker run --gpus all --rm --ipc=host -it nvcr.io/nvidia/pytorch:20.01-py3
`
- Failed to run the container showing this message:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Can run other docker images and nvidia cuda sample containers though.

**Comment by yashnv** [comment]
Hello, the docker is not meant to be run on a Nano. You want to use Nano only for export to TensorRT engine plan from the ONNX model. You can export the ONNX model from trained Pytorch model on your (preferably Volta architecture-based) discrete GPU.

**Comment by Sushil-Thapa** [comment]
I am trying to use docker to export ONNX to TensorRT and do inference on the Nano..
Been facing Installation issues with Apex and this project while installing it without docker with latest Jetpack on a Nano.
Were u able to run it on nano with TensorRT? what was the best latency/fps you got with deepstream?

**Comment by james-nvidia** [comment]
You just need to build the C++ API on the nano, which will convert your ONNX model into a TensorRT engine, which you can run natively on the Nano. Follow the instructions for Jetson Xavier, although you need to change the architecture `sm` number.
I got very flow frame rate (1fps) on a nano at 800p. You should get closer to 10fps if you can shrink your model input size down to 320p. We hope this will go up again when we have implemented the EfficientNet backbone.
Does that answer your questions?
