### ISSUE TITLE
Export to TensorRT engine on a Jetson Nano gives 'Killed'

### ISSUE THREAD

**Issue by lafius** [NVIDIA/retinanet-examples#144]
Hi,
When I tried to export to the tensorrt .plan engine file on my nano, it gives:
```
Building engine... 
Building FP16 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...

Killed
```
Here are the things I did:
- I cloned the 19.10 branch.
- I retrieved one of the pretrained models from [here](https://github.com/NVIDIA/retinanet-examples/releases).
- I exported it to onnx via `retinanet export` commands on my docker container. I double-checked that the model is valid by running the commands on my dev computer (which has a Geforce RTX 2070) and it gave very good results (and it's suuper fast, good job guys!!)
- I followed the instructions for the [Jetson xavier](https://github.com/NVIDIA/retinanet-examples/blob/19.10/extras/cppapi/README.md) but on my nano.

Everything worked so far but it failed on the export command at the end to generate the .plan engine
Is it due to the architecture of the nano that's different from the xavier? or a memory issue? (Should I decrease `workspace_size`?)
I saw in #140 that you succeeded to make it run on the nano and you mentionned a `sm` number.. 
What are the changes to make in order to make it run on nano? (even if it's slow)

**Comment by yashnv** [comment]
What's your Jetpack version? 4.3? Use this: `cat /etc/nv_tegra_release`

What model are you using?

The `sm` architecture is for DeepStream CMakelists.txt file, but for your case the export step is failing for which you don't need to change any variables.

**Comment by lafius** [comment]
I get this:
`# R32 (release), REVISION: 3.1, GCID: 18186506, BOARD: t210ref, EABI: aarch64, DATE: Tue Dec 10 06:58:34 UTC 2019`

**Comment by yashnv** [comment]
`19.10` should work fine for this, make sure that the branch being used on the Nano and 2070 is 19.10. Try to use ResNet18/34

**Comment by lafius** [comment]
I double checked everything and actually used your trained retinanet18 model for conversion... I don't see what's wrong it just killed when running the c++ `export` command... Didn't you change anything to make it work on the nano? looks like there is a memory issue Idk because when I ran the onnx2trt and I decreased the workspace it succeeds but gives wrong results.. What do you suggest me to do?

**Comment by yashnv** [comment]
Let's try to debug this:

- Add this `set(CMAKE_CUDA_FLAGS "-g -G")` [here](https://github.com/NVIDIA/retinanet-examples/blob/19.10/extras/cppapi/CMakeLists.txt#L8)

- cmake and make -j again

- `sudo apt install gdb valgrind` on Nano

- Run `gdb ./export`

- Inside GDB: `r model.onnx engine.plan` (model.onnx should be in same directory as export executable)

- Wait for it to fail, and when it fails enter `backtrace`

Paste the output of backtrace here

**Comment by Sushil-Thapa** [comment]
Not sure if that'll help but did you select max performance option on Nano and/or add swap memory?

**Comment by lafius** [comment]
@yashnv, I followed the steps above so when I insert `set(CMAKE_CUDA_FLAGS "-g -G")` as you mentionned [here](https://github.com/NVIDIA/retinanet-examples/blob/19.10/extras/cppapi/CMakeLists.txt#L8) and run `cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++14" ..` and `make -j` it throws me an error like:
`error: __host__ or __device__ annotation on lambda requires --expt-extended-lambda nvcc flag`
sorry, I don't know much with c++.. I don't understand why the flag was not passed successfully

I tried to run the gdb without your instructions and it gives:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Building engine...
[New Thread 0x7f83b671c0 (LWP 11580)]
Building FP16 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
[New Thread 0x7f5cc351c0 (LWP 11629)]
[Thread 0x7f5cc351c0 (LWP 11629) exited]
[Thread 0x7f83b671c0 (LWP 11580) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) backtrace
No stack.
```

@Sushil-Thapa is there a way to select the performance on Nano? does that affect memory? Idk about adding swap mem... @yashnv did you guys add swap memory to make it work?

**Comment by yashnv** [comment]
change `set(CMAKE_CUDA_FLAGS "-g -G")` to `set(CMAKE_CUDA_FLAGS "--expt-extended-lambda -std=c++14 -g -G")`, and try again.

**Comment by lafius** [comment]
Actually, I managed to export it, just needed to reboot the nano. Mem issues.. Closing it. Thank you very much!

**Comment by Sushil-Thapa** [comment]
I was talking about this option. (details [here](https://www.jetsonhacks.com/2017/03/25/nvpmodel-nvidia-jetson-tx2-development-kit/))
`$ sudo nvpmodel -m [mode]`

Great that you got it solved with the reboot. 
I managed to export it but didn't see much improvement with the TensorRT in terms of speed.

@lafius What was the max speed(fps) that you were able to achieve in your detection on the nano?

**Comment by twmht** [comment]
I had the same problem, I just found out that converting engine would cost about 50% of memory. so this might be the memory issue.

after decreasing the workspace size, the issue solved.

btw, is anyone know how to configure nano to use much more memory until it kills the process? I believe using about 50% of memory is very common in applications.
