### ISSUE TITLE
Dynamic shape support for onnx parser

### ISSUE THREAD

**Issue by ArtificialNotImbecile** [NVIDIA/retinanet-examples#147]
[Tensorrt supports dynamic shapes in version 7.x](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes). Will this repo support  this feature in future update?

**Comment by yashnv** [comment]
Hello, what dimensions are you referring as dynamic here(eg - N in NCHW)? 
Are there any particular use cases that you have?

**Comment by ArtificialNotImbecile** [comment]
> Hello, what dimensions are you referring as dynamic here(eg - N in NCHW)?

`HW`

> Are there any particular use cases that you have?

"Input image size: TensorRT engines only support a fixed input size", so tensorrt will resize the input to `model.input_size` automatically right? But this is not ideal if my inputs have very different aspect ratios.

**Comment by yashnv** [comment]
This complicates the engine execution context due to multiple optimization profiles supporting various ranges of aspect ratios. This will lead to an extended runtime.
