### ISSUE TITLE
core dump by using cppapi 

### ISSUE THREAD

**Issue by dengjianbo3** [NVIDIA/retinanet-examples#148]
hello, I using cppai and compiled as the readme provide. I use model engine transfer by the main project (retinanet export model.pth model.plan --full-precsison).
I could run the inference in the way main project provide, but when I using the same engine file in the same enviorment with compiled cppapi than went wrong like this :

root@c15df4e0eedb:/workspace/hostfiles/Documents/retinanet/extras/cppapi/build# ./infer ../tensorrt.plan ../imgs/
Loading engine...
file size is 424613019
Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
Preparing data...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 140) > this->size() (which is 0)
Aborted (core dumped)

**Comment by dengjianbo3** [comment]
and also when exporting .plan engine from .onnx model I got error like this, which it is fine in python api

root@c15df4e0eedb:/workspace/hostfiles/Documents/retinanet/extras/cppapi/build# ./export ../20200229_model.pth ../test_model.onnx
Building engine...
Building FP16 core model...
Segmentation fault (core dumped)

**Comment by dengjianbo3** [comment]
Also I using the lastest docker image nvcr.io/nvidia/pytorch:20.02-py3

**Comment by dengjianbo3** [comment]
this is the result when I run the same engine file in python api and it works fine

root@c15df4e0eedb:/workspace/hostfiles/Documents/retinanet/extras/cppapi/build# retinanet infer ../tensorrt.plan --images ../imgs
Loading CUDA engine from tensorrt.plan...
Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
Preparing dataset...
    loader: pytorch
    resize: 800, max: 1280
   backend: tensorrt
    device: 1 gpu
     batch: 1, precision: unknown
Running inference...
[1/1] 0.708s/1-batch (fw: 0.144s), 1.4 im/s
Gathering results...
Writing detections.json...
[E ProcessGroupNCCL.cpp:284] NCCL watchdog thread terminated

**Comment by dengjianbo3** [comment]
sorry for the issue, I ran the inference with correctly command but it also got this

root@c15df4e0eedb:/workspace/hostfiles/Documents/retinanet/extras/cppapi/build# ./infer ../tensorrt.plan ../imgs/frame0000.jpg 
Loading engine...
file size is 424613019
Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
Preparing data...
Running inference...
Segmentation fault (core dumped)

**Comment by deep-practice** [comment]
I use the TRT5 branch .Same error when exporting onnx file to trt engine.
The program core dumped when executing _engine.serialize().I check the _engine object,it's not nullptr.
The onnx file I generated by "python main.py" with pytorch1.2.

**Comment by dengjianbo3** [comment]
> I use the TRT5 branch .Same error when exporting onnx file to trt engine.
> The program core dumped when executing _engine.serialize().I check the _engine object,it's not nullptr.
> The onnx file I generated by "python main.py" with pytorch1.2.

But I train inside the lastest docker image and run inference with retinanet -infer like command work fine, just cppapi couldn't work

**Comment by yashnv** [comment]
@dengjianbo3 Please list all the commands and their outputs clearly. 

The C++ API is an example of how to do inference via C++, not intended to be a replica of the same steps taken for python. We encourage users to take the base example given in C++ and extend to match their use case. 
C++ export is for `ONNX -> Plan` export, not `pth -> ONNX`, to generate the onnx model, use `retinanet export model.pth model.onnx`
C++ infer can only do inference on a single image at a time.

**Comment by dengjianbo3** [comment]
@yashnv  Thanks,  I could run the inference correctly

**Comment by deep-practice** [comment]
@yashnv @dengjianbo3 Can u guys provide a exported onnx file?I want to check which part is  problematic.the cpp code or  the onnx file.

**Comment by yashnv** [comment]
@deep-practice download a trained model [here](https://github.com/NVIDIA/retinanet-examples/releases)
then convert using `retinanet export model.pth model.onnx`
