### ISSUE TITLE
code path

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#149]
I run the setup.py to install retinanet ,where is the code be install ?

**Comment by yashnv** [comment]
If you are using the NGC container, the installed directory for python API depends on whether you used the `-e` flag or not in `pip install` 

I f you didn't use it, the location should be in `/opt/conda/lib/python3.6/site-packages/retinanet`

If you used the `-e` flag the install directory is the `/workspace/retinanet-examples`

**Comment by alicera** [comment]
I don't see the code in the /opt/conda/lib/python3.6/site-packages/retinanet
