### ISSUE TITLE
Deployment on Jetson Nano

### ISSUE THREAD

**Issue by yuvalg1987** [NVIDIA/retinanet-examples#150]
Hi, 

We are trying to deploy RetinaNet on the Jetson Nano but encountered several difficulties. We have performed the following instructions on the host computer (running with Nvidia GTX2080) :
1. We installed the Docker container and verified that it is working as expected.
2. We exported the 19.04 pre-trained model (found in the git release) to ONNX using the following command _retinanet-examples export model.pth model.onnx --size 800 1280_

On the Jetson Nano we tried to convert the ONNX to TensorRT according to the cppapi example (we compiled the example successfully) using the following command _export model.onnx engine.plan code_ ,
**but encountered the following error:**
Building engine...
Building FP16 core model...
Building accelerated plugins...
Parameter check failed at: ../builder/Network.cpp::addConcatenation::308, condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS
Segmentation fault (core dumped)

As far as I understand there is no need to use the docker on the Jetson (if it's even possible) that's why we chose to use the cppapi. I saw several similar posts regarding the same error but it seems that all the suggested solutions are no longer supported (version 19.9 no longer exist). 

We use the following configuration for the host computer and Jeston:
**Jetson Nano: branch 19.10** 
Cuda:  10.0, V10.0.326
TensorRT: 6.0.1-1+cuda10.0            
OpenCV: 4.2
cudNN: 7.63

Host Computer (GTX2080) : from master**
Cuda: 10.2
TensorRT: 7
OpenCV: 3.4
cudNN: 7.6.5

Any help will be much appreciated.
Yuval

**Comment by yashnv** [comment]
This is a failure from the TRT ONNX parser. 
Use the same `19.10` branch on host computer too with 19.10 container.

**Comment by yuvalg1987** [comment]
Hi, the master branch is 19.10 too no? I noticed that the pre-trained models are from branch 19.4, can that be the cause. Is there a 19.10 pre-trained models available. Ideally, I would like to test the whole pipe-line (from pyTorch to TensorRT) before spending time training my network. Thanks for the help!

**Comment by yashnv** [comment]
> Hi, the master branch is 19.10 too no?

No.
The trained models are not unique for every other branch.

**Comment by yuvalg1987** [comment]
Ok I didn't notice the difference in versions between master and 19.10. Using 19.10 container on both the host and Nano works great. Thanks a lot for the help!
