### ISSUE TITLE
resume weight

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#155]
can it resume the weight?
how to do?

**Comment by james-nvidia** [comment]
You can keep training from a model.

`odtk train model.pth --iters 10000` trains a new model for 10k iterations.
`odtk train model.pth --iters 15000` trains the same model for an additional 5k iterations, 15k total.

Does that answer your question?

**Comment by alicera** [comment]
thanks

**Comment by alicera** [comment]
--rotated-bbox 
what does it mean

**Comment by james-nvidia** [comment]
To keep the issues section tidy, please open a new issue for each new question / problem.
See here for info on rotated detections. 
https://github.com/NVIDIA/retinanet-examples/blob/master/TRAINING.md#rotated-detections

We will post an example in a future release.
