### ISSUE TITLE
output json 

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#157]
the images should have height and width  ?
{
    "images": [{
        "id" : int,
        "file_name" : str
    }],
    "annotations": [{
        "id" : int,
        "image_id" : int, 
        "category_id" : int,
        "bbox" : [x, y, w, h]   # all floats
        "area": float           # w * h. Required for validation scores
        "iscrowd": 0            # Required for validation scores
    }],
    "categories": [{
        "id" : int
    ]}
}

**Comment by james-nvidia** [comment]
The repo only requires the annotation keys shown in your question
However, you can use the full COCO object detection if you wish. It is available here:
http://cocodataset.org/#format-data

**Comment by alicera** [comment]
why?
your retinanet  in  TRT6 have the   height and width
but retinanet in TRT7  have not

**Comment by yashnv** [comment]
What are you referring to? Where is the height and width not specified? This has nothing to do with TRT.

Please provide more details.

**Comment by alicera** [comment]
in the TRT6,
{
"images": [{
"id" : int,
"file_name" : str
"height":1920,
"width":1920
}],
"annotations": [{
"id" : int,
"image_id" : int,
"category_id" : int,
"bbox" : [x, y, w, h] # all floats
"area": float # w * h. Required for validation scores
"iscrowd": 0 # Required for validation scores
}],
"categories": [{
"id" : int
]}
}



in the TRT7 
{
"images": [{
"id" : int,
"file_name" : str
}],
"annotations": [{
"id" : int,
"image_id" : int,
"category_id" : int,
"bbox" : [x, y, w, h] # all floats
"area": float # w * h. Required for validation scores
"iscrowd": 0 # Required for validation scores
}],
"categories": [{
"id" : int
]}
}
