### ISSUE TITLE
Jetson TX2: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by mfruhner** [NVIDIA/retinanet-examples#159]
Hello,
I am currently trying to follow [this](https://devblogs.nvidia.com/real-time-redaction-app-nvidia-deepstream-part-2-deployment/) Nvidia tutorial to deploy a RetinaNet on my Jetson TX2 with DeepStream. As the tutorial is written for the Xavier, many of the steps don't work out of the box, though.

I trained a custom detector as described with my own data on a DGX-Station with the Pytorch Docker-Image 19.10. Then I exported it with the export function of this repo to an onnx-file and copied it to the Jetson. There I converted it to a TRT .plan file with the extras/cppapi export function. (Everything on branch 19.10)

Currently I am at the step to start the default deepstream-app with my own config to load my model, but i keep getting this error:

```
**PERF: FPS 0 (Avg)	
**PERF: 0.00 (0.00)	
** INFO: <bus_callback:189>: Pipeline ready

Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 260 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 260 
** INFO: <bus_callback:175>: Pipeline running

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: no kernel image is available for execution on the device
Aborted (core dumped)
```

I already found help for many earlier problems with google, but for this one, I can't find a solution. Even the two issues in this repo about this error could not fix it.

I am really new to DeepStream, so it could be some easy fix, but I don't know where to start looking. When googling the error message, many threads state that the compute capacity is not sufficiant, but I don't think this is the case for the Jetson, right?

Has anyone an idea?

Thanks,
Maik

**Comment by mfruhner** [comment]
For anyone in the future having the same problem, I found my solution [in this issue](https://github.com/NVIDIA/retinanet-examples/issues/109). I had to change the ARCH in the CMake file for the parser lib.

**Comment by james-nvidia** [comment]
@mfruhner Thanks for pointing that out for other users.
@jin-nvidia and I wrote that tutorial -- please let us know if you use it for anything interesting.

**Comment by WhaSukGO** [comment]
@james-nvidia I'm having the same problem with Jetson Nano. Could you share the tutorial, please?
