### ISSUE TITLE
Engine output cleaning up bug?

### ISSUE THREAD

**Issue by jzhang-magna** [NVIDIA/retinanet-examples#160]
Seems only cleaning up the first output for multiple times? 
https://github.com/NVIDIA/retinanet-examples/blob/6d52c501a8ed5fcd1958d96f9bdd776eb2f1e291/csrc/engine.cpp#L147

**Comment by yashnv** [comment]
After each unmark, that layer is not an output tensor anymore, so the outputs keep moving towards 0th index. Kind of like dequeueing in a queue.

**Comment by jzhang-magna** [comment]
Ah ic, thx for clarification @yashnv
