### ISSUE TITLE
Where to find retinanet_rn50fpn.pth?

### ISSUE THREAD

**Issue by abhaydoke09** [NVIDIA/retinanet-examples#161]
I am trying to use this repo. Where to find retinanet_rn50fpn.pth ?

**Comment by yashnv** [comment]
https://github.com/NVIDIA/retinanet-examples/releases/tag/19.04

**Comment by abhaydoke09** [comment]
Got it!! Thanks. I am trying to prepare my training dataset. I know I have to convert it into the coco format. It would be helpful to add a sample annotation format. Thank in advance!!

**Comment by yashnv** [comment]
This is the [format](https://github.com/NVIDIA/retinanet-examples#datasets)
