### ISSUE TITLE
JSON Annotation like not availabel.

### ISSUE THREAD

**Issue by abhaydoke09** [NVIDIA/retinanet-examples#162]
For this link https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip

I am getting 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to coco-dataset/external/PASCAL_VOC.zip.
</Details>
</Error>

**Comment by yashnv** [comment]
That link looks broken, try https://pjreddie.com/projects/pascal-voc-dataset-mirror/

**Comment by abhaydoke09** [comment]
I am not able to download from this link.

**Comment by james-nvidia** [comment]
You cannot download from which link?
We give Pascal VOC as an example dataset. I suggest you use COCO or your own dataset.

**Comment by d5a5ny** [comment]
https://www.kaggle.com/zaraks/pascal-voc-2007
