### ISSUE TITLE
RuntimeError: CUDA error: out of memory on V100

### ISSUE THREAD

**Issue by abhaydoke09** [NVIDIA/retinanet-examples#163]
![Screen Shot 2020-03-24 at 11 30 20 PM](https://user-images.githubusercontent.com/13537462/77499070-7b526a00-6e27-11ea-9cc1-8a80bfb9b51f.png)

**Comment by yashnv** [comment]
It shouldn't happen in normal condition for a V100, check if your GPU memory is occupied through `nvidia-smi`, then kill those processes, and start training again.

If that doesn't help reduce the batch size.

**Comment by abhaydoke09** [comment]
It's interesting. It suddenly fails while model is being loaded. I have trained retinanet in pytorch on the same machine. Is there a way to restrict training on a single GPU?

**Comment by abhaydoke09** [comment]
CUDA_VISIBLE_DEVICES=0 odtk train retinanet_rn50fpn.pth --backbone ResNet50FPN \
    --images /coco/images/train2017/ --annotations /coco/annotations/instances_train2017.json \
    --val-images /coco/images/val2017/ --val-annotations /coco/annotations/instances_val2017.json

Worked!!

This means this code is forcefully using all available GPUs on a machine. This is not good for shared GPU machines where multiple people are using the same machine. 

You might want to add a flag to select a GPU id/number from available GPUs

**Comment by james-nvidia** [comment]
You can also specify the devices when starting the container.
