### ISSUE TITLE
Error at larger batch sizes with TensorRT (FP16 and INT8)

### ISSUE THREAD

**Issue by revilokeb** [NVIDIA/retinanet-examples#17]
I have trained a Retinanet Resnet18 and Resnet152 for 90k / 40k iterations on Coco on 4xV100 with mixed precision (up to ~27mAP) and created TennsorRT execution plans with FP16 and INT8. Accuracy and inference time for batch 1 inference is in line with your table for V100 and T4 for FP16 and INT8, also for mixed- / full-precision seems reasonable.

For mixed- / full-precision inference I can go up to batch size ~33 on single V100 (16GB) for Retinanet Resnet 18. However using backend TensorRT I can only inference with up to batch size 2(!) before getting the following error when using batch size 3:

> Loading CUDA engine from retinanet_rn18fpn_V100_singleGPU.plan...
Preparing dataset
    loader: pytorch
    resize: 800, max: 1280
   backend: tensorrt
    device: 1 gpu
     batch: 3, precision: unknown
Running inference...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 455, in accept
    deliver_challenge(c, self._authkey)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 722, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

Same is true for inferencing with FP16 / INT8 on T4, I can only go up to batch size 2. At batch size 2 nvidia-smi is showing GPU memory usage of ~1500 MiB.

On the other hand https://docs.nvidia.com/deeplearning/sdk/tensorrt-best-practices/index.html clearly advises to use larger batch sizes for inferencing when using TensorRT.

Would you have got any idea / explanation how that is coming about?

**Comment by florischabert** [comment]
When running `retinanet export` did you specify `--batch n`? The default max batch size is 2 I believe.

**Comment by revilokeb** [comment]
I had not set batch size during export, I was not aware that TensorRT requires batch size at export time. But you are right, it is already there https://github.com/NVIDIA/retinanet-examples/blob/26dd6dfcb32ce265217a18fc2513e351bdf4c47a/retinanet/main.py#L64

I also tested it now and it works. Many thanks for your quick and helpful reply.
