### ISSUE TITLE
docker pull nvcr.io/nvidia/pytorch:20.03-py3: unauthorized: authentication required

### ISSUE THREAD

**Issue by bestaar** [NVIDIA/retinanet-examples#171]
Hi,

I am trying and failing to complete the installation of retinanet for almost 2 days.
The problem occurs when pulling the Pytorch image. This is the terminal output:

**input**
docker build -t odtk:latest retinanet-examples/

**output**
Sending build context to Docker daemon  317.4kB
Step 1/3 : FROM nvcr.io/nvidia/pytorch:20.02-py3
20.02-py3: Pulling from nvidia/pytorch
5c939e3a4d10: Pulling fs layer 
c63719cdbe7a: Pulling fs layer 
19a861ea6baf: Pulling fs layer 
651c9d2d6c4f: Waiting 
ec1ff02470e4: Waiting 
b0cf94422843: Waiting 
24634a544ff3: Waiting 
08eeefc4f275: Waiting 
8bd0daba03d4: Waiting 
0de885550a64: Waiting 
0c7d3841bbb7: Waiting 
13713568c4cc: Waiting 
f36b0f5c6c1c: Waiting 
08da6a17fb56: Waiting 
1ec1ed31e758: Waiting 
29169720b35e: Pulling fs layer 
36a4f3849bb4: Waiting 
88dcd4bbe90f: Waiting 
1f108f08952d: Waiting 
62c9fe9ae41e: Waiting 
46374b58e34d: Waiting 
0ac28443ad48: Waiting 
f2f12dc9b694: Waiting 
da836b63eaa0: Waiting 
a28eeadef187: Waiting 
df84073bdb15: Waiting 
f09fa03c35e8: Waiting 
a5bb8177b834: Waiting 
60471e520b9d: Waiting 
aca1a4fb0e23: Waiting 
f3024e6fcaec: Pulling fs layer 
3b34bf8c6910: Waiting 
a36b54164c8f: Waiting 
bd6aff42455b: Waiting 
d7d361edb369: Waiting 
f36b0f5c6c1c: Download complete 
79575863b55f: Waiting 
141c1414dd9a: Waiting 
8a7f4aaa1fff: Waiting 
453c287d9583: Waiting 
fee4ee3c75db: Waiting 
34664123664c: Waiting 
105ce33d8d88: Waiting 
52d23f791d96: Waiting 
8190d1efd1a4: Waiting 
d91b50828af4: Waiting 
844c29960870: Waiting 
8b4e3a59661e: Waiting 
f8aae7a7c775: Waiting 
cae8a4b0bbce: Waiting 
610de3c77e01: Waiting 
1ab04d840ec7: Waiting 
95e497723ed5: Waiting 
031bb90d0c83: Waiting 
bc6f3305ab9a: Waiting 
299f3d8fedc3: Waiting 
9c7bab99491c: Waiting 
28c44c82ed9a: Waiting 
unauthorized: authentication required

I have re-tried multiple times, thinking it might be due to my slow internet connection. I also tried to download the Pytorch image separately which runs into the same error.

Pointers to solving this issue would be greatly appreciated :)

Best

Benjamin

**Comment by yashnv** [comment]
You need to do `docker login nvcr.io` as mentioned in https://ngc.nvidia.com/setup/api-key by generating your API key.

Also please use container version 20.02, not 20.03
