### ISSUE TITLE
loss_scale = 128.0 even in full precision mode

### ISSUE THREAD

**Issue by xiedidan** [NVIDIA/retinanet-examples#173]
[here](https://github.com/NVIDIA/retinanet-examples/blob/4fc447353f7a3f25e73d840063b448a293134d40/retinanet/train.py#L36), loss_scale is set to 128.0 even in full precision model. Is this setting automatically disabled for O0?
[apex doc](https://nvidia.github.io/apex/amp.html#module-apex.amp) is not clear on loss_scale.

**Comment by yashnv** [comment]
Loss scaling is not automatically disabled for `O0`, but there is mechanism in place to scale and unscale loss for fp32.
Learn more about this process here: https://github.com/NVIDIA/apex/blob/master/apex/amp/_initialize.py
