### ISSUE TITLE
decode.cu error

### ISSUE THREAD

**Issue by liwandong** [NVIDIA/retinanet-examples#175]
when i run in my retinanet onnx from mmdetection
i meet error like this:

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  trivial_device_copy D->H failed: cudaErrorIllegalAddress: an illegal memory access was encountered

in decode.cu line" int num_detections = *thrust::device_pointer_cast(num_selected);"

**Comment by yashnv** [comment]
This repository does not support mmdetection. Closing this now.

**Comment by liwandong** [comment]
I think it doesn't matter with mmdetection,because the network work well and get featuremap result,can you tell me, in that case this error will occur



At 2020-04-07 15:52:20, "Yash Vardhan" <notifications@github.com> wrote:

This repository does not support mmdetection. Closing this now.

**Comment by liwandong** [comment]
> This repository does not support mmdetection. Closing this now.



> This repository does not support mmdetection. Closing this now.

I think it doesn't matter with mmdetection,because the network work well and get featuremap result,can you tell me, in that case this error will occur
