### ISSUE TITLE
condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#178]
version  remotes/origin/19.10

root@44759db0979f:/workspace/retinanet-examples# retinanet export  ../retinanet_rn50fpn.pth  retinanet_rn50fpn.plan  --full-precision
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Exporting to ONNX...
Building FP32 core model...
(Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
Building accelerated plugins...
Parameter check failed at: ../builder/Network.cpp::addConcatenation::308, condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS
Segmentation fault (core dumped)

**Comment by james-nvidia** [comment]
Which container are you using? PyTorch 19.10? Which version of ODTK?

I have just tried that command on PyTorch 20.02 using v0.2.2 of ODTK and it works.
Could you try using the same?

On a side note, are you seeing any accuracy difference between FP32 an FP16? I would expect there to be almost no change in mAP, but FP16 should run considerably faster.

**Comment by azuryl** [comment]
contianer is  ocker run --gpus all --rm --ipc=host -it nvcr.io/nvidia/pytorch:19.10-py3

**Comment by james-nvidia** [comment]
I just ran the same command on PyTorch:19.10-py3 using 19.10 branch and it worked.
Has your model file been corrupted? Can you download it again and try again?

```
root@7018012686d4:/src# retinanet export /data/retinanet_pretrained/retinanet_rn50fpn.pth test.plan --full-precision
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Exporting to ONNX...
Building FP32 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Writing to test.plan...
```

**Comment by yashnv** [comment]
@azuryl did you change the code to use explicit batch? Or was it something else? I can't see this error occurring by running the code as is.
```
(Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
```
This error during export came up from the use of explicit batch in 19.10 container when we were changing the code to be TRT7 compatible.

**Comment by james-nvidia** [comment]
Can you elaborate on this?

> my customer's all software run on old version not support PyTorch 20.02

Do you mean their driver won't run PyTorch 20.02?

**Comment by azuryl** [comment]
> I just ran the same command on PyTorch:19.10-py3 using 19.10 branch and it worked.
> Has your model file been corrupted? Can you download it again and try again?
> 
> ```
> root@7018012686d4:/src# retinanet export /data/retinanet_pretrained/retinanet_rn50fpn.pth test.plan --full-precision
> Loading model from retinanet_rn50fpn.pth...
>      model: RetinaNet
>   backbone: ResNet50FPN
>    classes: 80, anchors: 9
> Exporting to ONNX...
> Building FP32 core model...
> Building accelerated plugins...
> Applying optimizations and building TRT CUDA engine...
> Writing to test.plan...
> ```
root@44759db0979f:/workspace/retinanet-examples# git branch
* 19.10
  master

**Comment by azuryl** [comment]
> @azuryl did you change the code to use explicit batch? Or was it something else? I can't see this error occurring by running the code as is.
> 
> ```
> (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
> ```
> 
> This error during export came up from the use of explicit batch in 19.10 container when we were changing the code to be TRT7 compatible.

I changed nothing , I just git clone https://github.com/nvidia/retinanet-examples and git checkout to 19.10

**Comment by azuryl** [comment]
> Can you elaborate on this?
> 
> > my customer's all software run on old version not support PyTorch 20.02
> 
> Do you mean their driver won't run PyTorch 20.02?

they just use TRT 5.1 and 6.1

**Comment by james-nvidia** [comment]
Are you sure that you are using a clean version of the code? Can you delete your current copy and then pull it again?
If that doesn't work, then please provide details of your hardware. Which GPU are you using?

**Comment by azuryl** [comment]
> I just ran the same command on PyTorch:19.10-py3 using 19.10 branch and it worked.
> Has your model file been corrupted? Can you download it again and try again?
> 
> ```
> root@7018012686d4:/src# retinanet export /data/retinanet_pretrained/retinanet_rn50fpn.pth test.plan --full-precision
> Loading model from retinanet_rn50fpn.pth...
>      model: RetinaNet
>   backbone: ResNet50FPN
>    classes: 80, anchors: 9
> Exporting to ONNX...
> Building FP32 core model...
> Building accelerated plugins...
> Applying optimizations and building TRT CUDA engine...
> Writing to test.plan...
> ```
infer is ok 
root@44759db0979f:/workspace/retinanet-examples# CUDA_VISIBLE_DEVICES=0 retinanet infer retinanet_rn50fpn.pth --images coco/val2017 --annotations coco/annotations/instances_val2017.json
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Preparing dataset...
    loader: pytorch
    resize: 800, max: 1333
   backend: pytorch
    device: 1 GPU
     batch: 2, precision: mixed
 BBOX type: axis aligned
Running inference...
[ 384/5000] 0.313s/2-batch (fw: 0.308s), 6.4 im/s
[1102/5000] 0.168s/2-batch (fw: 0.167s), 11.9 im/s
[1858/5000] 0.159s/2-batch (fw: 0.158s), 12.6 im/s

**Comment by james-nvidia** [comment]
Please delete the code, re-pull, and try the export command again.

**Comment by yashnv** [comment]
> BBOX type: axis aligned
> Running inference...

@azuryl you shouldn't be able to see `BBOX type: axis aligned`, because it is a change we introduced after 19.10. Are you sure you have the right branch, because it doesn't seem so.

**Comment by azuryl** [comment]
> > BBOX type: axis aligned
> > Running inference...
> 
> @azuryl you shouldn't be able to see `BBOX type: axis aligned`, because it is a change we introduced after 19.10. Are you sure you have the right branch, because it doesn't seem so.

root@44759db0979f:/workspace/retinanet-examples# git branch --all
* 19.10
  master
  remotes/origin/19.10
  remotes/origin/HEAD -> origin/master
  remotes/origin/TRT5
  remotes/origin/master
root@44759db0979f:/workspace/retinanet-examples#

**Comment by azuryl** [comment]
> Please delete the code, re-pull, and try the export command again.

I will re pull it

**Comment by azuryl** [comment]
> Please delete the code, re-pull, and try the export command again.

I had repull and build  it is the same error

retinanet  export  ../retinanet_rn50fpn.pth  retinanet_rn50fpn.plan  --full-precision
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Exporting to ONNX...
Building FP32 core model...
(Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
Building accelerated plugins...
Parameter check failed at: ../builder/Network.cpp::addConcatenation::308, condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS
Segmentation fault (core dumped)

**Comment by azuryl** [comment]
@james-nvidia 
root@44759db0979f:/workspace/retinanet-examples# git branch -a
  master
* remotes/origin/19.10
  remotes/origin/19.10
  remotes/origin/HEAD -> origin/master
  remotes/origin/TRT5
  remotes/origin/master

CUDA_VISIBLE_DEVICES=0 retinanet export  ../retinanet_rn50fpn.pth  retinanet_rn50fpn.plan  --full-precision
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Exporting to ONNX...
Building FP32 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Writing to retinanet_rn50fpn.plan...

it seems ok 

and I want to know the resaon "Parameter check failed at: ../builder/Network.cpp::addConcatenation::308, condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS"
because  I have another model which I ported to TRT have the same error

Thank you

**Comment by james-nvidia** [comment]
We're glad your problem got resolved.
For your other model, play close attention to the TensorRT version. There were some crucial changes between TRT6 and 7.

**Comment by azuryl** [comment]
@james-nvidia  dear  james  can you tell me what is the crucial changes. we plan porting our model to TRT, TRT7 is more easy to pass ONNX?

**Comment by yashnv** [comment]
@azuryl take a look at this commit: https://github.com/NVIDIA/retinanet-examples/commit/91d558dd70d7835516e83ae951203d2ecda1f6e9

For transition to 20.01 PyTorch container, which comes preconfigured with TRT7, we needed to switch to explicit batch from implicit batch, and IPluginV2Ext from IPluginV2 for the custom decode and NMS plugins.

**Comment by azuryl** [comment]
> For transition to 20.01 PyTorch container, which comes preconfigured with TRT7, we needed to switch to explicit batch from implicit batch, and IPluginV2Ext from IPluginV2 for the custom decode and NMS plugins.

@yashnv thank you reply. do we need update CUDA, now my CUDA version is 10.0

**Comment by yashnv** [comment]
It is recommended that you have CUDA 10.2 with driver version 440 for TRT7.
