### ISSUE TITLE
MobileNetV2 capability in 19.10 branch

### ISSUE THREAD

**Issue by geyyer** [NVIDIA/retinanet-examples#185]
Hi,

could you please merge MobileNetV2 updates to 19.10 branch?

Thanks!

Rosty

**Comment by yashnv** [comment]
Hello, thanks for raising this issue.

We have pushed MobileNetV2FPN backbone to 19.10. Check it out. Closing this now.

**Comment by geyyer** [comment]
Thanks, you are the best!
