### ISSUE TITLE
Need examples for benchmarking

### ISSUE THREAD

**Issue by changtimwu** [NVIDIA/retinanet-examples#186]
Hi! 

We're evaluating the performance of Tesla T4.  `ODTK`  seems not designed for hardware benchmarking.   The FPS numbers listed in README.md are way too low. I expect to see fps figures near the offical announcment 
https://developer.nvidia.com/deep-learning-performance-training-inference

Can you add some `odtk infer` usage examples for benchmarking scenario?
 
Thanks

**Comment by yashnv** [comment]
We already provide numbers for benchmarking in the `odtk infer`. What hardware benchmarking are you referring to?

The link that you provide and the results in that page are completely different from what this repository provides. RetinaNet is different object detection framework as compared to any SSD-MobileNet network in that page. Moreover, please check out the input size used in inference, large inputs have lower inference throughputs.
