### ISSUE TITLE
missing file when building an image for deepstream

### ISSUE THREAD

**Issue by bl6594** [NVIDIA/retinanet-examples#187]
I was trying to build an image for deepstream by running the command below:

 docker build -f Dockerfile.deepstream -t deepstream:latest .

and received the error below:

Step 6/13 : RUN tar -xvf binaries.tbz2 -C / &&     ./install.sh
 ---> Running in 125474bb7556
tar: binaries.tbz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

I had no problem building the odtk image, which works perfectly on images, but I want to work on video using the deepstream.

Please let me know how to solve this problem.  Thanks.

**Comment by james-nvidia** [comment]
You need to download the DeepStream binaries from https://developer.nvidia.com/deepstream-sdk

Please let me know if this works.

**Comment by bl6594** [comment]
yes. after downloading the DeepStream binaries, the installation went smoothly.  Thank you for your help!
