### ISSUE TITLE
tx2 inference

### ISSUE THREAD

**Issue by sezarxray** [NVIDIA/retinanet-examples#189]
Hi,
I ran your 19.10 branch on tx2. I used retina(resnet50fpn) . model successfully worked but frame rate is slow (9fps for 640*640).
I saw nvidia deepstream samples with very high frame rate. so I expect higher fps.
is my result acceptable? how can I get higher speed like nvidia sample???

**Comment by yashnv** [comment]
Hello, TX2 doesn't have native INT8 tensor cores, our samples with Jetson platform were performed on Xavier AGX.

I would suggest you either lower your input resolution and/or skip frames during deepstream inference by changing [this line](https://github.com/NVIDIA/retinanet-examples/blob/master/extras/deepstream/deepstream-sample/infer_config_batch1.txt#L55).
