### ISSUE TITLE
pytorch NGC 19.04 error

### ISSUE THREAD

**Issue by BowieHsu** [NVIDIA/retinanet-examples#19]
Hi, When I tried to execute training process, it meets problem when evaluation at 8000 iters:
 
 File "/opt/conda/lib/python3.6/site-packages/retinanet-0.1-py3.6-linux-x86_64.egg/retinanet/box.py", line 110, in decode
    anchors.view(-1).tolist(), stride, threshold, top_n)
RuntimeError: parallel_for failed: cudaErrorInvalidValue: invalid argument

Env:CUDA10.1 + 19.04 pytorch NGC container
I check the code and found the reason maybe that decode.cu is not suit for CUDA10.1 or something like that, Can you show me some Hints to debug this extension?

**Comment by BowieHsu** [comment]
I fixed it, the default NVCC compile setting of extension is "sm60" but for Tesla V100, it shoud be "**sm70**", after i modified this param, everything runs perfect.

**Comment by pkashinkunti** [comment]
Thanks for raising this issue. I have just merged #20 which should resolve this error.
