### ISSUE TITLE
High GPU Usage in Inference 

### ISSUE THREAD

**Issue by FeiZhuNiU** [NVIDIA/retinanet-examples#191]
branch: 19.10
Inference time: 250ms  
GPU usage: **60%**
GPU:  Tesla T4
input size (1280, 1280)
concurrency: 1

why.. 60% so high

**Comment by james-nvidia** [comment]
Are you running using a TensorRT engine?

**Comment by yashnv** [comment]
Closing this, seems to be a non-issue. @FeiZhuNiU please comment or feel free to reopen if you have more issues with this.
