### ISSUE TITLE
patching in config

### ISSUE THREAD

**Issue by sezarxray** [NVIDIA/retinanet-examples#192]
Dear sir,
Is there a way in deepstream to patch HD video to 640 * 640 parts and run your model (exported with 640*640) ?
regards

**Comment by james-nvidia** [comment]
I'm don't fully understand what you are asking. Are you asking to split your incoming video into several streams, and then run inference on each stream?
DeepStream can resize videos, but any cropping will have to be done using gstreamer, which integrates nicely with DeepStream.

Please ask any DeepStream questions here: https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/deepstream-sdk/15

**Comment by ai-vip2020** [comment]
> I'm don't fully understand what you are asking. Are you asking to split your incoming video into several streams, and then run inference on each stream?
> DeepStream can resize videos, but any cropping will have to be done using gstreamer, which integrates nicely with DeepStream.
> 
> Please ask any DeepStream questions here: https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/deepstream-sdk/15

thanks for your advice!
