### ISSUE TITLE
Export to ONNX

### ISSUE THREAD

**Issue by VincentDuf** [NVIDIA/retinanet-examples#193]
Hi,
I just wanted to know if the "retinanet export" command could be used to export a .pth file to an ONNX file.

I saw in the model.py the possibility but in the comment of the export command it only refers to TensorRT... Can I just apply "retinanet export model.pth model.onnx" ? 

Thanks

**Comment by james-nvidia** [comment]
Yes, you can do exactly that.
For an example, see the instructions for moving your network onto an embedded device here https://github.com/NVIDIA/retinanet-examples/tree/master/extras/deepstream
