### ISSUE TITLE
Support for Rotated Bounding Boxes on Jetson

### ISSUE THREAD

**Issue by mw3155** [NVIDIA/retinanet-examples#194]
Hi,

I noticed that the 19.10 branch is missing the rotated bounding box detection feature.
So I guess it is impossible to predict rotated bouding boxes on a Jetson device?

Are you planing to implement rotated bounding boxes for Jetson in the near future (~6 months)?

**Comment by james-nvidia** [comment]
Using rotated detection on Jetson requires the following:
1. A new bbox parser, so that DeepStream understands the new output of retinanet.
2. Using the new DeepStream 5 OSD module to display the rotated boxes.

**Comment by mw3155** [comment]
Hi James,

I don't use DeepStream right now, only the C++ API.
Does that mean I only have to wait for JetPack 4.4 and then it should work?
Sounds great!

**Comment by yashnv** [comment]
Closing this, looks resolved.
