### ISSUE TITLE
INT8 seems no speed up

### ISSUE THREAD

**Issue by lcytzk** [NVIDIA/retinanet-examples#195]
Thank you for this project, it really helps me a lot.

First I clone this project and using the docker image which recommended from readme to ensure that I will achieve the best performance.

ENV:
docker image: nvcr.io/nvidia/pytorch
code: master branch
graphic card: v100
model: resnet18fpn

And with things above, I got ~70 imgs/s by using resnet18fpn, which is same as the speed provided by this project.
1. odtk export retina_rn18fpn.pth test.plan
2. odtk infer test.plan --images cocodata --anotations cocoano --resize 800 --with-dali

And then I try to apply int8 and wish to have a better performance.
1. odtk export retina_rn18fpn.pth test_int8.plan --int8 --calibration-images cocodata
2. odtk infer test_int8.plan --images cocodata --anotations cocoano --resize 800 --with-dali

But I only got ~70 imgs/s same as fp16(without --int8 flag)

1. I am pretty sure that int8 is enabled, because I got int8table file and the log shows that I was using int8 for export.
2. GPU usage around 95%, GPU mem  is 21xxMiB.

And this is nvcc --version:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

Did I miss something or resnet18fpn is not a good example for int8?
Could you add int8 for comparison by using same hardware sometime in the future?

**Comment by yashnv** [comment]
Hello, V100 doesn't have native INT8 tensor cores, so seeing a performance boost on v100 over fp16 is not expected.
Remember the benchmarks we show for INT8 are performed on T4 or on AGX Xavier, which are based on Turing architecture with native INT8 tensor cores.
