### ISSUE TITLE
why inputSize can't be changed in Xavier

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#196]
In Xavier 
extras/cppapi/infer.c
auto inputSize = engine.getInputSize();   print the inputSize:
inputSize[0]=1280, inputSize[1]=1280
if change the inputSize[0]=800, inputSize[1]=1280
pragramme is crashed

the inputsize must be 1280 x 1280?

**Comment by yashnv** [comment]
That is because the size is set during export process(specifically during PyT -> ONNX export), not infer.

**Comment by azuryl** [comment]
do you have  example for 2 batch in infer.cpp
