### ISSUE TITLE
 parallel_for failed: invalid argument

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#197]
since we need  input  two picture in same time so I modified
in export.c
// Define default RetinaNet parameters to use for TRT export
        int batch = 2;
and build a plan file: 800x1280_NV_R50fpn_half_Xvifer_b2.plan
in  infer.cpp_
int batch =2
 for(int i =0 ; i< batch; i++){  //input two same  image just for test
        int offset = i * channels * inputSize[0] * inputSize[1];
        for (int c = 0; c < channels; c++) {
                for (int j = 0, hw = inputSize[0] * inputSize[1]; j < hw; j++) {
                        data[offset + c * hw + j] = (img[channels * j + 2 - c] - mean[c]) / std[c];
}
        // Create device buffers   
        void *data_d,  *scores_d, *boxes_d, *classes_d;
        
        auto num_det = engine.getMaxDetections();
        cudaMalloc(&data_d, 3 * inputSize[0] * inputSize[1] * sizeof(float) * batch);
        cudaMalloc(&scores_d, num_det * sizeof(float) * batch);
        cudaMalloc(&boxes_d, num_det * 4 * sizeof(float) * batch);
        cudaMalloc(&classes_d, num_det * sizeof(float) * batch);
        
        size_t dataSize = data.size() * sizeof(float) * batch;
        cudaMemcpy(data_d, data.data(), dataSize, cudaMemcpyHostToDevice);

        cout << "Running inference..." << endl;
        const int count = 100;
        auto start = chrono::steady_clock::now();
        vector<void *> buffers={data_d, scores_d, boxes_d, classes_d};

        for (int i = 0; i < count; i++) {
                engine.infer(buffers, batch );
         }
        auto stop = chrono::steady_clock::now();
        auto timing = chrono::duration_cast<chrono::duration<double>>(stop - start);
        cout << "Took " << timing.count() / count << " seconds per inference." << endl;
        ............

 ./infer 800x1280_NV_R50fpn_half_Xvifer_b2.plan 75039.png
Loading engine...
Preparing data...
1280,800
Running inference...
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid argument
Aborted (core dumped)

**Comment by yashnv** [comment]
Hello, the C++ API is an example of how to do inference via C++, not intended to be a replica of the same steps taken for python. We encourage users to take the base example given in C++ and extend to match their use case. 

You can't multiply batch in cudaMalloc for batch size 2, it doesn't work that way. Why not just use the Python interface, get the similar topn, and parse the json results for the same?

**Comment by kevinjoseph1995** [comment]
What is the best way to do batch inference in C++?
Would adding multiple images into a single data buffer(allocating _3 * inputSize[0] * inputSize[1] * sizeof(float) * batch_) bytes) and follow a row major order (N C H W ) in filling up the buffer from multiple images work?
