### ISSUE TITLE
about NMS

### ISSUE THREAD

**Issue by passion3394** [NVIDIA/retinanet-examples#200]
thanks for this great repo.
 Now I am working on Xavier with the 19.10 branch, and use the exported tensorRT plan files to do inference. there are some overlapped boxes in the detection result. So the question is:

vector<void *> buffers = { data_d, scores_d, boxes_d, classes_d };
engine.infer(buffers, 1);

the engine.infer does NMS or not?

**Comment by yashnv** [comment]
Yes it does, you can try to experiment with `nms_thresh` and `score_thresh` in export.cpp to observe a different output.

**Comment by passion3394** [comment]
thanks, I will try some different nms_thresh and score_thresh.
