### ISSUE TITLE
condition: nbInputs> 0 && nbInputs <MAX_CONCAT_INPUTS

### ISSUE THREAD

**Issue by manhongnie** [NVIDIA/retinanet-examples#205]
I trained my model using tensorflow, then I converted the pb model to onnx, and then used ./export model.onnx model.plan to generate my engine, but this error occurred during the process
"Parameter check failed at: ../builder/Network.cpp::addConcatenation::457, condition: nbInputs> 0 && nbInputs <MAX_CONCAT_INPUTS".

Then I tried to print some values "nbOutputs: 0"
"Scores.size: 0"
"boxes.size: 0"
"classes.size: 0"
can you help me?

**Comment by yashnv** [comment]
Hello, the C++ API doesn't work with any ONNX models . You need a model generated from this repository.

**Comment by manhongnie** [comment]
> Hello, the C++ API doesn't work with any ONNX models . You need a model generated from this repository.

What if I want to use my own onnx.

**Comment by yashnv** [comment]
Checkout https://github.com/onnx/onnx-tensorrt
and https://github.com/NVIDIA/TensorRT

**Comment by manhongnie** [comment]
> Checkout https://github.com/onnx/onnx-tensorrt
> and https://github.com/NVIDIA/TensorRT

If I use the uff model, how can I verify that the uff model is available, can you tell me? I am a novice
