### ISSUE TITLE
Jetson TX2 / TX2i support

### ISSUE THREAD

**Issue by matthaeusheer** [NVIDIA/retinanet-examples#206]
Hello! Has this been tested on the Jetson TX2 / TX2i (Jetpack 4.3)? I'd like to deploy Retinanet with a Resnet50 Backbone on a TX2 and TX2i and wonder if it is worth investing the time looking into this work. Thank you very much!

**Comment by james-nvidia** [comment]
We have not tested it on TX2, but other customers have used it successfully on TX2 with ResNet50 backbone. You may need to use the deepstream `interval` tag to increase frame rate, and also train with `--jitter` and `--resize` to decrease the input resolution a little.
Please let use know how you get on.
