### ISSUE TITLE
nvcc fatal   : redefinition of argument 'std'

### ISSUE THREAD

**Issue by hcx1231** [NVIDIA/retinanet-examples#208]
as in https://github.com/NVIDIA/retinanet-examples/issues/207 ,
I also want to integrate the TensorRT model to Triton.
Then I went to extras -> cppapi and followed build steps(cmake and make -j) as readme,but it showed errors:

[ 18%] Building CUDA object CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/nms.cu.o
[ 18%] Building CUDA object CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/nms_iou.cu.o
[ 36%] Building CUDA object CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/decode_rotate.cu.o
[ 36%] Building CUDA object CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/decode.cu.o
nvcc fatal   : redefinition of argument 'std'
nvcc fatal   : redefinition of argument 'std'
nvcc fatal   : redefinition of argument 'std'
nvcc fatal   : redefinition of argument 'std'
CMakeFiles/retinanet.dir/build.make:92: recipe for target 'CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/nms.cu.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/nms.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/retinanet.dir/build.make:118: recipe for target 'CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/nms_iou.cu.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/nms_iou.cu.o] Error 1
CMakeFiles/retinanet.dir/build.make:79: recipe for target 'CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/decode.cu.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/decode.cu.o] Error 1
CMakeFiles/retinanet.dir/build.make:105: recipe for target 'CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/decode_rotate.cu.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/decode_rotate.cu.o] Error 1
CMakeFiles/Makefile2:123: recipe for target 'CMakeFiles/retinanet.dir/all' failed
make[1]: *** [CMakeFiles/retinanet.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2

how to solve it?

**Comment by jalola** [comment]
Hi,
The complete commands to build are from here:
https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi#linux

You may try it again

**Comment by hcx1231** [comment]
> Hi,
> The complete commands to build are from here:
> https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi#linux
> 
> You may try it again

Thank you for your reply.I did try this :
mkdir build && cd build
cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++14" ..
make

But it came out the error.

**Comment by hcx1231** [comment]
I try make --trace and found std was defined twice:
/usr/local/cuda/bin/nvcc  -DOPENCV_TRAITS_ENABLE_DEPRECATED -Dretinanet_EXPORTS -isystem=/usr/local/include/opencv  --expt-extended-lambda -std=c++14 -Xcompiler=-fPIC   -std=c++14 -x cu -c /host/retinanet-examples/csrc/cuda/decode.cu -o CMakeFiles/retinanet.dir/host/retinanet-examples/csrc/cuda/decode.cu.o

maybe one in Cmakelist.txt: set(CMAKE_CXX_STANDARD 14) line 4,
another in : cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++14" 
but how to solve it?

**Comment by jalola** [comment]
It is weird, I did same thing and built without any error.

Which docker image that you used to build?
I used this nvcr.io/nvidia/pytorch:20.02-py3

**Comment by yashnv** [comment]
Try cmake with `cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda"`

**Comment by hcx1231** [comment]
> It is weird, I did same thing and built without any error.
> 
> Which docker image that you used to build?
> I used this nvcr.io/nvidia/pytorch:20.02-py3

Downloading the docker image was very slow  in my lab,so I built the environment myself.
CUDA 10.0,cudnn7.4.2 ，opencv 3.4.0,TensorRT 7.0
Comparing with the readme,maybe the TensorRT version is too high?

**Comment by hcx1231** [comment]
> Try cmake with `cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda"`

It showed argument 1 is needed

**Comment by yashnv** [comment]
Sorry forgot the ..
`cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda" ..`

**Comment by hcx1231** [comment]
I solved this problem by editing /build.make,thank you guys!
