### ISSUE TITLE
Python API on Xavier with Jetpack 4.3

### ISSUE THREAD

**Issue by batrlatom** [NVIDIA/retinanet-examples#209]
I am unable to compile python api on xavier. 
I have tried build docker container, but getting error related to aarch64 architecture. 
I also tried simply install python packages by using `sudo pip3 install --no-cache-dir git+https://github.com/nvidia/retinanet-examples` and `python3 setup.py install`, but I am getting error related to cryptacular package. 

Are there some other ways how to make the python api work?

**Comment by batrlatom** [comment]
ok, so I ws able to solve it by installing cryptacular myself from git by using `sudo pip3 install git+ https://github.com/QPYPI/cryptacular`

**Comment by batrlatom** [comment]
Ok, no luck ... 

By using  `sudo pip3 install --no-cache-dir git+https://github.com/nvidia/retinanet-examples` I am still getting errors, now related to opencv. Jetpack 4.3 has opencv 4 installed. Is the other version of opencv needed?



    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pekat/.local/lib/python3.6/site-packages/torch/include -I/home/pekat/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/pekat/.local/lib/python3.6/site-packages/torch/include/TH -I/home/pekat/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c csrc/engine.cpp -o build/temp.linux-aarch64-3.6/csrc/engine.o -std=c++14 -O2 -Wall -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1
    In file included from csrc/engine.cpp:35:0:
    csrc/calibrator.h:25:10: fatal error: opencv2/opencv.hpp: No such file or directory
     #include <opencv2/opencv.hpp>
              ^~~~~~~~~~~~~~~~~~~~

**Comment by Maxfashko** [comment]
@batrlatom try installing the version of OpenCV that comes with the package. You can find the source packages in the folder after downloading all the components via sdkmanager

**Comment by yashnv** [comment]
This error results from setuptools not being configured to find opencv include directories and libraries.

Check the libraries field in setup.py here: https://github.com/NVIDIA/retinanet-examples/issues/64#issuecomment-578383304
