### ISSUE TITLE
Change batch size of trained network

### ISSUE THREAD

**Issue by VincentDuf** [NVIDIA/retinanet-examples#212]
Hey,
I'm trying to use a network I trained on my host computer (trained with batch size = 1). I converted to onnx format using the export command, I precised the batch size to be 64.

Unfortunately when I check the size using the onnx library the batch size still is 1... is there a way to modify the batch size of the model to do inference with higher speed ?

Thanks

**Comment by yashnv** [comment]
@VincentDuf can you try with recent changes? Just pushed updates for dynamic batches.

**Comment by VincentDuf** [comment]
Hey, 
I finally managed using the export command, don't know why it didn't work first time. 

Thanks
