### ISSUE TITLE
problem about input size

### ISSUE THREAD

**Issue by hcx1231** [NVIDIA/retinanet-examples#213]
In the data preprocess ,the size is  resized to [800,1280] (shorter length not shorter than 800,and longer length not longer than 1280).
"Input image size: TensorRT engines only support a fixed input size", so tensorrt will resize the input to model.input_size (1280,1280) automatically, right?
However,when i  integrated the TensorRT model to Triton (https://github.com/NVIDIA/triton-inference-server),the size had to be changed to (1280,1280) ,or it would showed error.
The problem is,whichever  method I used,resize or padding,the result computed in trt server differed from the trt model infered directly.So I wondered what is the automatically size changing method?

**Comment by yashnv** [comment]
Try commenting this line out: https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/infer.py#L36

**Comment by hcx1231** [comment]
> Try commenting this line out: https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/infer.py#L36

Sorry,maybe I did not make the problem clear.I mean the result  differs from "odtk infer *.plan  --images  xxxx "  and starting  *.plan by a trt  server.

**Comment by jalola** [comment]
How much results are different? Probably the 2 inputs are different
How did you do preprocess the image for Triton?
To make it fixed size, I need to pad on the right and bottom, I follow this one https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/data.py#L420

**Comment by yashnv** [comment]
It is true that our interface does a different set of preprocessing than the Triton inference server, so the results are bound to differ.

**Comment by hcx1231** [comment]
> How much results are different? Probably the 2 inputs are different
> How did you do preprocess the image for Triton?
> To make it fixed size, I need to pad on the right and bottom, I follow this one https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/data.py#L420

Using this method,the difference was very small.Thank you.

> It is true that our interface does a different set of preprocessing than the Triton inference server, so the results are bound to differ.

OK
