### ISSUE TITLE
no retinanet binary

### ISSUE THREAD

**Issue by arrow53** [NVIDIA/retinanet-examples#214]
I've followed these instructions to build

https://github.com/NVIDIA/retinanet-examples#installation

In various places I see references to a `retinanet` binary but I can't find it in the container 

https://github.com/NVIDIA/retinanet-examples/tree/master/extras/deepstream#jetson-agx-xavier

How do I build the `retinanet` binary?

**Comment by yashnv** [comment]
Hello, the `retinanet` binary is the old API(19.10), the new binary is `odtk`

**Comment by arrow53** [comment]
ah thanks!
