### ISSUE TITLE
Unexpected behavior: Cuda IoU implementation returns score 0 if (xmin, ymin) coincide between anchor and box

### ISSUE THREAD

**Issue by petersvenningsson** [NVIDIA/retinanet-examples#216]
I have encountered that the cuda iou implementation returns score 0 if the xmin, y_min coincide. 
Is this intended behavior?

A minimal example:
https://gist.github.com/petersvenningsson/d0007b596455ffb27cd4c18241435f60

Thank you!

**Comment by yashnv** [comment]
@jhowenvidia can you please take a look at this?

**Comment by jhowenvidia** [comment]
Yep, going to look at it this week. Sorry for the delay.

**Comment by yashnv** [comment]
@petersvenningsson can you try these changes: https://github.com/NVIDIA/retinanet-examples/commit/3d64221bde4ae59743af43b07dd1d0d42ab47744 and confirm if this commit fixes this issue?

**Comment by petersvenningsson** [comment]
@yashnv This solves the problem I was experiencing. Thanks!
