### ISSUE TITLE
I think tag v0.2.3 was overwritten by tag v0.2.5

### ISSUE THREAD

**Issue by jascase901** [NVIDIA/retinanet-examples#218]
The branches don't seem different to me. 
Also the changelog for v0.2.3 contains info from v0.2.5
https://github.com/NVIDIA/retinanet-examples/blob/v0.2.3/CHANGELOG.md

**Comment by yashnv** [comment]
Yup, looks like there was unresolved draft that was overwritten with recent changes. `Branch 20.03` is essentially what v0.2.3 was supposed to be plus recent updates.
