### ISSUE TITLE
Detections COCO Format JSON

### ISSUE THREAD

**Issue by ttamyurek** [NVIDIA/retinanet-examples#221]
https://github.com/NVIDIA/retinanet-examples/blob/a7fbb3de52bb0febcef95d0bfa069cae6e591a79/retinanet/infer.py#L152

Is there a reason to put the categories list into another list like that? I had problems parsing the detection results and realized this small issue. Just wanted to point out in case it was a mistake. You can close the issue. Thanks.

**Comment by yashnv** [comment]
I guess it would remove the need to always access it as `detections['categories'][0]`, which is reasonable, ok will change that.
