### ISSUE TITLE
map is very low

### ISSUE THREAD

**Issue by manhongnie** [NVIDIA/retinanet-examples#224]
Why do you want to take half of the onnx? Can't this model be converted and then analyzed? If you operate this way, I am not very at ease with the results of the entire training, because I cannot observe my network structure. If I use my own retinanaet, is it impossible to use tensorrt? This is very bad. I measured that your training result map is very low, which is not the result I want. Even your retinanet has incorrect results in the coco data set. Your method of handling this is not good.

**Comment by yashnv** [comment]
Please be clear in stating your issue. What method we are not handling well? What incorrect results are you referring to?

What do mean by half of the onnx? What are you trying to analyze? You can use netron to observe your onnx model. This repository only works well with ONNX model generated from this repository. You can't use your own retinanet model and expect that it will work fine.
