### ISSUE TITLE
how to use epoch for this code?

### ISSUE THREAD

**Issue by ShirleyLoveGIS** [NVIDIA/retinanet-examples#225]
In other codes I see the number of iteration is often defined by epoch.
I wonder why you use a user-defined iterations in this project.
:)

**Comment by yashnv** [comment]
Using iterations allows for a more precise control over setting the LR decay, fine-tuning, with varying batch-sizes. On the other hand, you don't always want this to be governed by how many times are you going over the whole dataset.

It wouldn't be wrong to say that in many projects, epochs are converted internally to iterations.

**Comment by ShirleyLoveGIS** [comment]
If  I want to reproduce the training process in someone else's paper.

For example, if the training set has _n_ pics and the author has trained for 20 epoch.
I shall set the _iteration_  = n * 20 and _val-iters_ = n. 
Is this setting right?

**Comment by james-nvidia** [comment]
An iteration is an update of one batch. So to get iterations from data size and epochs you need to do:

iterations = (data size * epochs) / batch size

**Comment by james-nvidia** [comment]
You could of course use the inverse of this to print out your epoch number in `train.py`. Something like this:

`epoch_no = iterations * batch_size / len(data_loader)`

I'll close this issue, but please reopen if you have a problem implementing either of these solutions.

**Comment by Egorundel** [comment]
@james-nvidia Hello! 
And where can I find the *data_loader* in the code?
