### ISSUE TITLE
Export to Xavier with JetPack 4.3 not working (Cudnn Error in initializeCommonContext)

### ISSUE THREAD

**Issue by mw3155** [NVIDIA/retinanet-examples#226]
Hello,

I trained a model with a 19.10 docker and exported it to a .onnx file.
Then I copied it to my Jetson Xavier where I compiled the cppapi (19.10 branch).
When I try to export it to a .plan file, I get the following error:
"""
Building engine...
Building FP16 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
Segmentation fault (core dumped)
"""

Here are the libraries of my Xavier:
 - NVIDIA Jetson AGX Xavier [16GB]
   * Jetpack 4.3 [L4T 32.3.1]
   * NV Power Mode: MAXN - Type: 0
   * jetson_stats.service: active
 - Libraries:
   * CUDA: 10.0.326
   * cuDNN: 7.6.3.28
   * TensorRT: 6.0.1.10
   * Visionworks: 1.6.0.500n
   * OpenCV: 4.1.1 compiled CUDA: NO
   * VPI: 0.1.0
   * Vulkan: 1.1.70

What can be the cause of this?
It is very strange, because if I go the same for my Jetson TX2, It works!

**Comment by yashnv** [comment]
Hmm looks like Xavier might not have CUDA libs in environment variables. What was the output of cmake? can you delete the build directory and past e the results of cmake?

**Comment by mw3155** [comment]
First I tried to compile with the -std=c++14 argument:

nvidia@nvidia-desktop:~ /retinanet-1910/extras/cppapi/build$ cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++14" ..
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0") 
-- The CUDA compiler identification is NVIDIA 10.0.326
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found OpenCV: /usr (found version "4.1.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/retinanet-1910/extras/cppapi/build
nvidia@nvidia-desktop:~/retinanet-1910/extras/cppapi/build$ make -j2
Scanning dependencies of target retinanet
[  9%] Building CUDA object CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/decode.cu.o
[ 18%] Building CUDA object CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/nms.cu.o
nvcc fatal   : redefinition of argument 'std'
nvcc fatal   : redefinition of argument 'std'
CMakeFiles/retinanet.dir/build.make:79: recipe for target 'CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/decode.cu.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/decode.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/retinanet.dir/build.make:92: recipe for target 'CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/nms.cu.o' failed
make[2]: *** [CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/nms.cu.o] Error 1
CMakeFiles/Makefile2:152: recipe for target 'CMakeFiles/retinanet.dir/all' failed
make[1]: *** [CMakeFiles/retinanet.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2


###################################################################################

Then I removed the -std=c++14 argument

nvidia@nvidia-desktop:~ /retinanet-1910/extras/cppapi/build$ rm -rf ./*
nvidia@nvidia-desktop:~ /retinanet-1910/extras/cppapi/build$ cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda" ..
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0") 
-- The CUDA compiler identification is NVIDIA 10.0.326
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found OpenCV: /usr (found version "4.1.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/retinanet-1910/extras/cppapi/build
nvidia@nvidia-desktop:~ /retinanet-1910/extras/cppapi/build$ make -j2
Scanning dependencies of target retinanet
[  9%] Building CUDA object CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/decode.cu.o
[ 18%] Building CUDA object CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/cuda/nms.cu.o
[ 27%] Building CXX object CMakeFiles/retinanet.dir/home/nvidia/retinanet-1910/csrc/engine.cpp.o
[ 36%] Linking CUDA device code CMakeFiles/retinanet.dir/cmake_device_link.o
[ 45%] Linking CXX static library libretinanet.a
[ 45%] Built target retinanet
Scanning dependencies of target infervideo
Scanning dependencies of target infer
[ 54%] Building CXX object CMakeFiles/infer.dir/infer.cpp.o
[ 63%] Building CXX object CMakeFiles/infervideo.dir/infervideo.cpp.o
[ 72%] Linking CXX executable infervideo
[ 81%] Linking CXX executable infer
[ 81%] Built target infer
Scanning dependencies of target export
[ 90%] Building CXX object CMakeFiles/export.dir/export.cpp.o
[ 90%] Built target infervideo
[100%] Linking CXX executable export
[100%] Built target export

nvidia@nvidia-desktop:~/retinanet-1910/extras/cppapi/build$ ./export ~/models/r1910.onnx test.plan
Building engine...
Building FP16 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
Segmentation fault (core dumped)

##################################################################################

I will try again with a fresh JetPack 4.3 or 4.4 install and report back.

**Comment by mw3155** [comment]
Update:
I reinstalled JetPack 4.3 and tried it again. This time I can compile with the "-std=c++14" argument without any problems.
However, I still get "Cudnn Error in initializeCommonContext" when I try to export the model.

nvidia@nvidia-desktop:~ /retinanet-examples/extras/cppapi/build$ cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++14" ..
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0") 
-- The CUDA compiler identification is NVIDIA 10.0.326
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found OpenCV: /usr (found version "4.1.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/retinanet-examples/extras/cppapi/build
nvidia@nvidia-desktop:~ /retinanet-examples/extras/cppapi/build$ make -j2
Scanning dependencies of target retinanet
[  7%] Building CUDA object CMakeFiles/retinanet.dir/home/nvidia/retinanet-examples/csrc/cuda/decode.cu.o
[ 14%] Building CUDA object CMakeFiles/retinanet.dir/home/nvidia/retinanet-examples/csrc/cuda/nms.cu.o
[ 21%] Building CXX object CMakeFiles/retinanet.dir/home/nvidia/retinanet-examples/csrc/engine.cpp.o
[ 28%] Linking CUDA device code CMakeFiles/retinanet.dir/cmake_device_link.o
[ 35%] Linking CXX static library libretinanet.a
[ 35%] Built target retinanet
Scanning dependencies of target infer
Scanning dependencies of target infervideo
[ 50%] Building CXX object CMakeFiles/infer.dir/infer.cpp.o
[ 50%] Building CXX object CMakeFiles/infervideo.dir/infervideo.cpp.o
[ 57%] Linking CUDA device code CMakeFiles/infervideo.dir/cmake_device_link.o
[ 64%] Linking CUDA device code CMakeFiles/infer.dir/cmake_device_link.o
[ 71%] Linking CXX executable infervideo
[ 78%] Linking CXX executable infer
[ 78%] Built target infer
Scanning dependencies of target export
[ 85%] Building CXX object CMakeFiles/export.dir/export.cpp.o
[ 85%] Built target infervideo
[ 92%] Linking CUDA device code CMakeFiles/export.dir/cmake_device_link.o
[100%] Linking CXX executable export
[100%] Built target export
nvidia@nvidia-desktop:~ /retinanet-examples/extras/cppapi/build$ ./export ~/r1910.onnx ttt.plan
Building engine...
Building FP16 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
Segmentation fault (core dumped)

**Comment by mw3155** [comment]
I updated our Xavier to Jetpack 4.4.
Now I can compile models trained on the 20.03 branch.
I got 50ms inference time for a ResNet50 backbone model (only 1 class).
Very nice!

I guess, this can be closed.
