### ISSUE TITLE
Visualizing rotated-boxes json

### ISSUE THREAD

**Issue by xonobo** [NVIDIA/retinanet-examples#233]
I have trained a rotated-box detector and by calling "odtk infer" script I got a inference output json file for the verification dataset. I want to visualize the detection results. What shall I do?

**Comment by james-nvidia** [comment]
Two steps:
1. Convert the bbox [xmin, ymin, w, h, theta] into the coordinates of the corners. You can do this by rotating the axis-aligned bounding box about the centre of that box.
```python
    centre = np.array([xmin + w / 2.0, ymin + h / 2.0])
    original_points = np.array([[xmin, ymin],                # This would be the box if theta = 0
                               [xmin + w, ymin],
                               [xmin + w, ymin + h],
                               [xmin, ymin + h]])
    rotation = np.array([[np.cos(theta), np.sin(theta)], [-np.sin(theta), np.cos(theta)]])
    corners = np.matmul(original_points - centre, rotation) + centre
```
2. Plot those on an image. I use `Pillow`, but you could also use `matplotlib`, `cv2` or others.

```python
    from PIL import Image, ImageDraw
    
    image = Image.open(filepath).convert("RGB")
    draw = ImageDraw.Draw(image)
    
    # For each annotation:
    corners.append(corners[0])                           # You need this to close the box
    draw.line(corners, fill=colour, width=width)
    image.save(output_path, quality=95)
```

Let me know how you get on.

**Comment by yashnv** [comment]
@xonobo did you try this? It would be great to have feedback from your end on visualizing these results.

**Comment by james-nvidia** [comment]
Closing, as we haven't heard anything for a week.
