### ISSUE TITLE
Imgae size when exporting to ONNX

### ISSUE THREAD

**Issue by saeedda** [NVIDIA/retinanet-examples#234]
I want to export ONNX model for a custom image size, I am working with branch 19.10 and use the following commands:

```
sudo docker run --gpus all --rm --ipc=host -it -v /path/to/some/folder:/model retinanet:latest
retinanet export /model/mymodel.pth /model/mymodel.onnx --size imheight imwidth
```

Which values are acceptable for  _imheight_ and _imwidth_?

**Comment by yashnv** [comment]
These values are use-case dependent, lower values means faster inference.
