### ISSUE TITLE
COCO 2017 training hyper parameter

### ISSUE THREAD

**Issue by 372046933** [NVIDIA/retinanet-examples#236]
I want to reproduce the MAP on https://github.com/NVIDIA/retinanet-examples#performance. But can't find the hyper-parameter for training.
Is `odtk train retinanet_rn50fpn.pth --backbone ResNet50FPN \
    --images /coco/images/train2017/ --annotations /coco/annotations/instances_train2017.json \
    --val-images /coco/images/val2017/ --val-annotations /coco/annotations/instances_val2017.json` enough to reproduce `Backbone: ResNet18FPN mAP @[IoU=0.50:0.95]: 0.318` on the site?

**Comment by james-nvidia** [comment]
We used these options:
    --with-dali --max-size=1280 --lr 0.02 --batch 32 --val-iters 4000 --milestones 50000 --iters 60000 --jitter 800 800

However you will need to tweak some of these (eg batch) for your system.

**Comment by 372046933** [comment]
@james-nvidia Thanks a million. BTW, how many cards did you have? I found that only `--batch 4` can fit on a single GPU

**Comment by james-nvidia** [comment]
That command ran on 8 x V100, so your batch is about right. I'll close this issue, if that's ok.
