### ISSUE TITLE
difference in  results for .pth and tensorrt engine plan

### ISSUE THREAD

**Issue by bipulkumar22** [NVIDIA/retinanet-examples#239]
while converting to engine.plan for tensorrt and comparing to .pth the bboxes are slightly bigger, an average deviation of  2.5 pixels. I tested this on v0.23 and v0.19 releases. It would great if you can confirm that is an expected behavior

**Comment by yashnv** [comment]
The model conversion to FP16 for optimization with TRT leads to slightly different weights, a average deviation of 2.5 pixels for large object maybe insignificant but significant for small and tiny objects.
This is expected.
