### ISSUE TITLE
Instance segmentation

### ISSUE THREAD

**Issue by nakul3112** [NVIDIA/retinanet-examples#241]
@james-nvidia Thanks for giving the resource to understand the metrics. However, when I trained the model, I got mAP of 0.53 at maximum for (second number). 

Now, I have another query if you could resolve:
1) Even with this metrics, I was able to visualize the results of bounding box detection on the test images, and it was looking pretty good. Now, I wanna extend it further to do instance segmentation.
2) I would be glad if you could guide me to proceed with the instance segmentation pipeline, provided that I have trained model `model.pth`, and bounding box detections in json format after running odtk inference. 

Thanks in advance. Looking forward to hearing from you soon.

_Originally posted by @nakul3112 in https://github.com/NVIDIA/retinanet-examples/issues/219#issuecomment-686843118_

**Comment by nakul3112** [comment]
@james-nvidia 1) while using Nvidia ODTK, I changed the NMS factor, so my concern is the NMS factor would be just helpful during inference , right?
2) Where would I do padding, after training or during inference?
Little more elaboration on this would be appreciated, so that atleast I can be sure of my bounding box detection before proceeding with the instance segmentation.

Thanks,

**Comment by james-nvidia** [comment]
1. NMS is applied during inference, not during training.
2. padding was just a suggestion. If you are feeding chips to a segmentation model, then you might want to provide more than just the bounding box, as there will be no context to the detection.
`xmin, ymin, w, h` could be modified to `xmin - w/4.0, ymin -h/4.0, w * 3 / 2.0, h * 3 / 2.0`, as a first suggestion.
