### ISSUE TITLE
Segmentation fault (core dumped) when calling function "infer" at extensions.cpp

### ISSUE THREAD

**Issue by saeedda** [NVIDIA/retinanet-examples#244]
I am working on branch 19.1 and deploying on Xavier AGX. I successfully (without any error) import retinanet module to python and can load an engine (.plan) file and everything looks correct. However, when calling "infer" at extensions.cpp (through pybind11), I am getting this error "Segmentation fault (core dumped)". Any idea?

    import torch
    import retinanet_infer as net
    import os
    import cv2
    import numpy as np

    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
    print("Device: {}".format(device))

    eng = net.Engine('nn.plan')
    input_size = eng.input_size
    print("input_size: {}".format(input_size))

    img = cv2.imread('img1.jpg')
    img = cv2.resize(img, (input_size[0], input_size[1]))
    data = np.moveaxis(img, -1, 0)
    data = np.expand_dims(data, axis=0)

    data = torch.Tensor(data)
    data_d = data.to(device)
    print("data_d: {}".format(data_d.shape))

    res = eng(data_d)

Output is:
    
    Device: cuda
    input_size: [320, 704]
    data_d: torch.Size([1, 3, 704, 320])
    Segmentation fault (core dumped)

**Comment by oukohou** [comment]
2020-09-17 14:44:10：
encountered similar error，any hint？

**Comment by yashnv** [comment]
How are you loading the library for plugins? I don't see any reference to that.

Here's an example how I am doing this: https://github.com/yashnv/RetinaNet-TensorRT

**Comment by saeedda** [comment]
@yashnv Thanks for your reply. I got your code and with small modifications, as you suggested, it works. However, I am getting out of memory sometimes:
    Traceback (most recent call last):
      File "trt_infer.py", line 150, in <module>
        infer(args)
      File "trt_infer.py", line 81, in infer
        img = cuda.register_host_memory(np.ascontiguousarray(im.ravel()))
    pycuda._driver.MemoryError: cuMemHostRegister failed: out of memory

This is about host memory (not device). Images are of size 1080x1920x3 and considering Xavier AGX memory, it should be fine. It looks like a random behavior!

**Comment by yashnv** [comment]
It's not random, register_host_memory maps host pages to GPU's address space, for which the first step is some amount of resource allocation. It can fail due to some processes taking up most of the resources.

Also the image dimension(1080x1920) seems too large for Xavier, don't you think so? Can you compress the image and see if it helps in any way?

**Comment by saeedda** [comment]
@yashnv Image dimensions should be fine because I tried several times with cppapi and never got out of memory error.

Is this necessary to call register_host_memory? I have commented this line and it works without any error. Do you see any consequences of that which are hidden to me right now?

**Comment by yashnv** [comment]
If things are fine w/o register_host_memory, I would suggest to not use it? ¯\_(ツ)_/¯
