### ISSUE TITLE
no cub/device/device_radix_sort.cub

### ISSUE THREAD

**Issue by syn66** [NVIDIA/retinanet-examples#246]
i got a problem when i executed the “make” command on the nano, the error is " no cub/device/device_radix_sort.cub", how to fix it.

**Comment by yashnv** [comment]
Hello, please use 20.03 branch for Nano or any Jetson device.

**Comment by syn66** [comment]
thanks for your reply, did that mean i must have a PyTorch container 20.03  in the nano. sorrry, i am beginner.
