### ISSUE TITLE
Jetson TX2 - Jetpack 4.3 Install issue

### ISSUE THREAD

**Issue by VincentDuf** [NVIDIA/retinanet-examples#247]
Hi,
I'm trying to install retinanet-example (branch 19.10 as recommanded) on my Jetson TX2 (Jetpack 4.3).

PyTorch, Apex and all requirements are correctly installed in a virtualenv but when I execute `python setup.py install` , I face this issue:

```
/usr/local/cuda-10.0/bin/nvcc -I/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/torch/include -I/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/torch/include/TH -I/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/nvidia/.virtualenvs/cv/include -I/usr/include/python3.6m -c csrc/cuda/decode_rotate.cu -o build/temp.linux-aarch64-3.6/csrc/cuda/decode_rotate.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++14 --expt-extended-lambda --use_fast_math -Xcompiler -Wall -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_62,code=compute_62 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1
gcc: error: csrc/cuda/decode_rotate.cu: No such file or directory
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
error: command '/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1
```

I've already spent some hours looking for an answer but none of them really helped me, do you have some ideas ? 

Thank you

**Comment by james-nvidia** [comment]
We have not tested the installation of the odtk repo on a TX2 -- we use the odtk code on a workstation to train a network, and then deploy it to a Jetson device for inference.
You appear to be missing a file. Is that file present?
    gcc: error: csrc/cuda/decode_rotate.cu: No such file or directory

**Comment by VincentDuf** [comment]
I do the same, I trained it on a work station but would like to use the retinanet command to infer and check the performance. 
I can't see how I can do otherwise, as there are some file needed to decode the output of the network. How would you deploy it without the repo ? 

Finally, I don't have the file and my question is why ? I have CUDA10.0 correctly installed 

Thanks

**Comment by VincentDuf** [comment]
Ok so I found the reason.

In the 19.10 branch that you recommend to install on Jetson with Jetpack4.3, the decode_rotate.cu and other files are missing that's why I have the error. 

Should I clone both repo and transfer the missing file to use the 19.10 version, or is it possible to install the master branch directly ?

Thanks

**Comment by yashnv** [comment]
I don't think there is a nvidia-dali package for Jetson, just remove that line from setup.py and proceed.

**Comment by VincentDuf** [comment]
Hey,
I misexplained the last edit, I've been able to correctly install the repository using the 20.03 branch. 

The problem with dali package is when I call "retinanet infer" for example. I don't get why you mentionned the setup.py as there is no mention of dali in it... 

Is the line you're talking about in another file maybe ? like main.py or other ?

Thanks

**Comment by yashnv** [comment]
Oh I am sorry, I meant remove all instances of dali `from .dali ...` from train.py and infer.py

**Comment by VincentDuf** [comment]
Hey,
thank you for the answer it does solve the issue, but now I'm facing a pytorch issue.

I have used the pre-built wheel for Jetpack4.3 to install pytorch 1.4 but when I call the retinanet command I have this occuring:

 File "/home/nvidia/.virtualenvs/cv/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 480, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in

Do you have any idea how to solve this ?

Thanks

**Comment by yashnv** [comment]
hmm it's slightly complicated to get NCCL backend working for Jetson. I can't guarantee if it would work.

Can you try to build the pytorch L4T container from source? 
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-6-0-now-available/72048

Check out the build from source section, and change USE_NCCL and USE_DISTRIBUTED to 1

**Comment by james-nvidia** [comment]
@VincentDuf did you get this to work?
