### ISSUE TITLE
docker build problem: 'failed to solve with frontend dockerfile.v0: failed to build LLB: failed to copy: httpReaderSeeker: failed open: failed to fetch anonymous token: unexpected status: 401 Unauthorized'

### ISSUE THREAD

**Issue by xggyh** [NVIDIA/retinanet-examples#252]
Thanks very much for your job, and when I used docker build to create a container, I encountered this problem, I don't know why this happens:
the problem is:'failed to solve with frontend dockerfile.v0: failed to build LLB: failed to copy: httpReaderSeeker: failed open: failed to fetch anonymous token: unexpected status: 401 Unauthorized'

**Comment by yashnv** [comment]
Can you try `docker pull nvcr.io/nvidia/pytorch:20.03-py3`?
