### ISSUE TITLE
Int8 inference significantly reduces the accuracy

### ISSUE THREAD

**Issue by xjtuljy** [NVIDIA/retinanet-examples#255]
Hi,

I adapted this repo for my own application, by slightly changing the detection head layers/depth. 

I found int8 inference significantly reduces the detection accuracy, especially the score for the detection:
![fp16_vs_int8](https://user-images.githubusercontent.com/8555939/97040078-4e337a80-1522-11eb-8985-264ca9c61c6d.png)

During int8 calibration I didn't see any warning/error notice. I tried using 640, 5000, and 10000 images for calibration, the inference results are basically the same. My work was based on "19.04"

Could anyone please provide some suggestions?
Thanks!
Jianyu

**Comment by yashnv** [comment]
Can you try the 20.03 branch with 20.03 PyT docker? Also the calibration images need to be similar to the inference images in terms of resolution.

**Comment by james-nvidia** [comment]
@xjtuljy Has this been resolved?

**Comment by xjtuljy** [comment]
@yashnv Sorry I missed your message. 
@james-nvidia Yes, by using 20.03 the accuracy loss was minimized. There might be some int8 calibration improvement from TRT5 to TRT7. It is resolved now.
