### ISSUE TITLE
RuntimeError: Loss is diverging! Try lowering the learning rate.

### ISSUE THREAD

**Issue by zhoujinxing01** [NVIDIA/retinanet-examples#256]
root@f295b698e3f1:/workspace/data# nvidia-smi
Tue Nov  3 01:23:43 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1660    Off  | 00000000:01:00.0  On |                  N/A |
| 31%   33C    P8    10W / 130W |    261MiB /  5943MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
root@f295b698e3f1:/workspace/data# odtk train retinanet_rn50fpn.pth  --backbone ResNet50FPN  --images /workspace/data/train2017/   --annotations /workspace/data/instances_train2017.json       --val-images /workspace/data/val2017/    --val-annotations /workspace/data/instances_val2017.json --batch 1 --warmup 125 --lr 0.00125
Initializing model...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : 128.0
Preparing dataset...
    loader: pytorch
    resize: [640, 1024], max: 1333
    device: 1 GPU
     batch: 1, precision: mixed
 BBOX type: axis aligned
Training model for 90000 iterations...
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/workspace/retinanet/retinanet/main.py", line 243, in main
    worker(0, args, 1, model, state)
  File "/workspace/retinanet/retinanet/main.py", line 180, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angle)
  File "/workspace/retinanet/retinanet/train.py", line 123, in train
    'Try lowering the learning rate.'))
RuntimeError: Loss is diverging!
Try lowering the learning rate.

**Comment by zhoujinxing01** [comment]
I try to train on 1 GPU(GeForce GTX 1660)，how to fix the problem：**RuntimeError: Loss is diverging!Try lowering the learning** rate.Thank you!

**Comment by zhoujinxing01** [comment]
the train command is:
odtk train retinanet_rn50fpn.pth  --backbone ResNet50FPN  --images /workspace/data/train2017/   --annotations /workspace/data/instances_train2017.json       --val-images /workspace/data/val2017/    --val-annotations /workspace/data/instances_val2017.json --batch 1 --warmup 125 --lr 0.00125

**Comment by dketterer** [comment]
Try increasing the batch size or actually using a lower learning rate. You are using a small warmup time. Increase it! Especially with batch size 1.

If you are sure of what you are doing, you can try to restart the training again with the same parameters. The training will resume  from the last saved checkpoint and with a bit of luck you have a different order of images that result in a better loss progression. But most likely you will encounter the same problem.

**Comment by yashnv** [comment]
@zhoujinxing01 is this still an issue?

**Comment by zhouyingchaoAI** [comment]
the same error

**Comment by yashnv** [comment]
Duplicate issue, closing.
