### ISSUE TITLE
TensorRT Calibration Cache Samples

### ISSUE THREAD

**Issue by Hassan313** [NVIDIA/retinanet-examples#261]
Hi Yash,

I am interested in the TensorRT Calibration Cache files of the below models:

ResNet18FPN
ResNet34FPN
ResNet101FPN
ResNet152FPN

Do you have their calibration cache file?

Thank you very much,

Best Regards
Hassan

**Comment by yashnv** [comment]
Hello, much like the TensorRT engine, the calibration caches are also machine specific. You have to generate them yourself on your GPU.

**Comment by Hassan313** [comment]
So I do not understand your point. TensortRT quantize the model from floating point to int8. Why the calibration cache should be different?

**Comment by yashnv** [comment]
So the calibration cache contains version hex for the the TensorRT version used, and dynamic scales depending upon the calibration batch used. There are lots of combinations, so it's better for the user to generate this on their own. The first generation time is long, but after that the cache can be reused.

**Comment by Hassan313** [comment]
Ok. Now I understand your point.  If I know the number of your batch size
and the images you used, can I use your calibration cache? Am I right?

Thanks.
