### ISSUE TITLE
Exporting onnx to Tensorrt failing on Jetson

### ISSUE THREAD

**Issue by thanujpilli** [NVIDIA/retinanet-examples#264]
Hi,

I am using 19.10 branch both on host and nano device. I have created onnx file on host machine and 
while trying to convert onnx to trt file on jetson nano I am getting below error
```
thanuj@jarvis:~/projs/retinanet-examples/extras/cppapi/build$ ./export /home/thanuj/projs/trt_models/thanuj.onnx /home/thanuj/projs/trt_models/thanuj.plan
Building engine...
Building FP16 core model...
Segmentation fault (core dumped)
```
We use the following configuration for the host computer and Jeston:
deepstream: 5.0
Jetpack: 4.4.1
Cuda: 10.2.89
TensorRT: 7.1.3
OpenCV: 4.1
cudNN: 8.0.0

Host Computer (GTX1080) : from master**
Cuda: 10.1
Torch: 1.6

**Comment by yashnv** [comment]
This looks like an incompatibility issue in packages. Please use docker on host.

**Comment by daynauth** [comment]
I'm using Docker on the host machine and I'm having the exact issue. Any help would be greatly appreciated.

**Comment by daynauth** [comment]
My bad. Looks like I needed to use the 20.03 repo for both the host and the jetson device.
