### ISSUE TITLE
Pascal VOC Json annotations broken link

### ISSUE THREAD

**Issue by rboca** [NVIDIA/retinanet-examples#266]
The link in Readme.md for the Pascal VOC JSON annotations is not working:
https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip

Can it be updated please? Or add the PASCAL_VOC.zip to this repository 

Thank you,

**Comment by yashnv** [comment]
Try this: https://pjreddie.com/projects/pascal-voc-dataset-mirror/

**Comment by rboca** [comment]
The PASCAL JSON is still missing from the link https://pjreddie.com/projects/pascal-voc-dataset-mirror/

See the missing link on the main page at "FINE TUNING" / "JSON annotations" 
https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip

Thanks,
