### ISSUE TITLE
cuda11.1 ----> condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS

### ISSUE THREAD

**Issue by batrlatom** [NVIDIA/retinanet-examples#267]
Hi,
I have a question regarding the tensorrt export for retinanet.

I am getting an error ```condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS```
in case I change the Docker file to the newest version. 
```
FROM nvcr.io/nvidia/pytorch:20.12-py3
COPY . retinanet/
RUN pip install --no-cache-dir -e retinanet/
```
my setup.py have little change to reflect RTX compute capability
```
                '-gencode=arch=compute_86,code=sm_86', '-gencode=arch=compute_86,code=compute_86'
```

The problem is, that I need to make the code running on RTX cards, which are supported only on Cuda 11.1 and later.
If I use older card like gtx1080ti with cuda 11 for example, it works well.

Could you please help me to make it work on the newest architecture and cuda 11.1 ?

**Comment by hoangnt2601** [comment]
> Hi,
> I have a question regarding the tensorrt export for retinanet.
> 
> I am getting an error `condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS`
> in case I change the Docker file to the newest version.
> 
> ```
> FROM nvcr.io/nvidia/pytorch:20.12-py3
> COPY . retinanet/
> RUN pip install --no-cache-dir -e retinanet/
> ```
> 
> my setup.py have little change to reflect RTX compute capability
> 
> ```
>                 '-gencode=arch=compute_86,code=sm_86', '-gencode=arch=compute_86,code=compute_86'
> ```
> 
> The problem is, that I need to make the code running on RTX cards, which are supported only on Cuda 11.1 and later.
> If I use older card like gtx1080ti with cuda 11 for example, it works well.
> 
> Could you please help me to make it work on the newest architecture and cuda 11.1 ?

probably because of opset_version's version

**Comment by batrlatom** [comment]
@hoangnt2601 I have tried to change the opset versions and recompile, but the outcome is the same.
export to onnx works ok, but the later stage do not.

I have tried to change opset to 9, 10, 11, 12 without any luck

model.py
```
  def export(self, size, dynamic_batch_opts, precision, calibration_files, calibration_table, verbose, onnx_only=False):

        import torch.onnx.symbolic_opset11 as onnx_symbolic
        def upsample_nearest2d(g, input, output_size, *args):
            # Currently, TRT 7.1 ONNX Parser does not support all ONNX ops
            # needed to support dynamic upsampling ONNX forumlation
            # Here we hardcode scale=2 as a temporary workaround
            scales = g.op("Constant", value_t=torch.tensor([1., 1., 2., 2.]))
            empty_tensor = g.op("Constant", value_t=torch.tensor([], dtype=torch.float32))
            return g.op("Resize", input, empty_tensor, scales, mode_s="nearest", nearest_mode_s="floor")

        onnx_symbolic.upsample_nearest2d = upsample_nearest2d

        # Export to ONNX
        print('Exporting to ONNX... ---- opset11')
        self.exporting = True
        onnx_bytes = io.BytesIO()
        zero_input = torch.zeros([1, 3, *size]).cuda()
        input_names = ['input_1']
        output_names = ['score_1', 'score_2', 'score_3', 'score_4', 'score_5',
                        'box_1', 'box_2', 'box_3', 'box_4', 'box_5']
        dynamic_axes = {input_names[0]: {0:'batch'}}
        for _, name in enumerate(output_names):
            dynamic_axes[name] = dynamic_axes[input_names[0]]
        extra_args = {'opset_version': 11, 'verbose': verbose,
                      'input_names': input_names, 'output_names': output_names,
                      'dynamic_axes': dynamic_axes}
        torch.onnx.export(self.cuda(), zero_input, onnx_bytes, **extra_args)
        self.exporting = False
...
...
...

```

**Comment by MartinBrazdil** [comment]
Hello,

I have the same problem, trying out some fixes without success yet.

It would be greatly appreciated if this repository gets at least compatibility support because network quality is great!

Best regards,
Martin :-)

**Comment by yashnv** [comment]
@batrlatom can you try recent update, haven't added RTX support yet, so add that line `'-gencode=arch=compute_86,code=sm_86', '-gencode=arch=compute_86,code=compute_86'` and let me know if this works in the new 20.11 based master branch.
