### ISSUE TITLE
RuntimeError: Loss is diverging!

### ISSUE THREAD

**Issue by zhouyingchaoAI** [NVIDIA/retinanet-examples#270]
GeForce GTX 1660ti
CUDA Version: 11.1
nvcr.io/nvidia/pytorch:20.06-py3
barnch20.03

odtk train model.pth --images val2017/ --annotations instances_val2017.json  --backbone ResNet50FPN --warmup 125000 --lr 0.00001 --val-images val2017/ --val-annotations instances_val2017.json --classes 80 --jitter 688 848 --resize 768 --augment-rotate --augment-brightness 0.01 --augment-contrast 0.01 --augment-hue 0.002 --augment-saturation 0.01 --batch 2 --regularization-l2 0.00001  --val-iters 20000

No matter how it changes lr/warmup  it's still  error

**Comment by yashnv** [comment]
Can you try recent changes based on 20.11 master branch?
