### ISSUE TITLE
Future of RetinaNet (this repository)

### ISSUE THREAD

**Issue by MartinBrazdil** [NVIDIA/retinanet-examples#271]
Hi!

I really use and enjoy this RetinaNet repository because of actually great precision, learning and speed!

However I am considered about future because it seems almost dead.

I would be grateful for at least support for new NGC images with new TRT, ONNX and PyTorch versions.

I have managed to make sufficient changes myself but what is the plan for the future?

Best regards,
Martin

**Comment by batrlatom** [comment]
Hello Martin, 
did you succeed to make this repo run with those newest NGC images? Would you be able to share the changes?
Thanks.

**Comment by MartinBrazdil** [comment]
Hi batrlatom,

in Dockerfile try replacing base image with:

nvcr.io/nvidia/tensorrt:20.10-py3

Hope this helps,
Martin

**Comment by yashnv** [comment]
Hello, this repository acts as a medium to run some experiments done internally. We try to update it as often as needed, but this is not in active development. The latest updates have been put in with container 20.11.

**Comment by MartinBrazdil** [comment]
I would like ask complementary question - is RetinaNet from NVidia Transfer Learning Toolkit basically continuation of this experimental repository?
