### ISSUE TITLE
Int8 Calibration  table creation for onnx model

### ISSUE THREAD

**Issue by nahap** [NVIDIA/retinanet-examples#274]
Hi,

Is there a way to create the int8 calibration table with an onnx file as input instead of a .pth file?

That would be really usefull. or is there a simple workaround to this?

**Comment by yashnv** [comment]
Hi, the C++ API does have this support: https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/export.cpp#L88:

- Uncomment 89
- Comment 90
- Add model name to 91 (like ResNet50FPN)
- Set COCO_PATH in 10 correctly
- make the executable again
- Run as `./export model.onnx engine.plan <CALIBRATION_TABLE_NAME>`
