### ISSUE TITLE
Rotation Matrix Inconsistent in utils.py 

### ISSUE THREAD

**Issue by dilpreetsingh** [NVIDIA/retinanet-examples#275]
Hey,

The [rotate_boxes](https://github.com/NVIDIA/retinanet-examples/blob/f1671353cb657126354543e9e94ecb6b65c5ddfd/retinanet/utils.py#L32) method has a clockwise rotation matrix (notice negative sign in bottom row):

```python
u = torch.stack([torch.cos(boxes[:,4]), torch.sin(boxes[:,4])], dim=1)
l = torch.stack([-torch.sin(boxes[:,4]), torch.cos(boxes[:,4])], dim=1)
```

where as the singular [rotate_box](https://github.com/NVIDIA/retinanet-examples/blob/f1671353cb657126354543e9e94ecb6b65c5ddfd/retinanet/utils.py#L83) method has a counter-clockwise rotation matrix (notice negative sign in top row):

```python
u = np.stack([np.cos(theta), -np.sin(theta)])
l = np.stack([np.sin(theta), np.cos(theta)])
```

I'm assuming this is an error? The training scripts uses `rotated_boxes` whilst the inference script uses the singular `rotate_box` method.

Thanks

**Comment by yashnv** [comment]
We have double-checked and verified the results, so we know this is definitely not an issue.
