### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by ConnorMcShane** [NVIDIA/retinanet-examples#284]
Hi, and sorry if this is a stupid question but I'm having some issues getting started here. I am very interested in using this repo especially for its rotated bounding box detection. 

My setup:
Windows 10
1080ti GPU

I am new to docker, I installed it for windows and pulled the image (docker pull nvcr.io/nvidia/pytorch:21.04-py3).

I then cloned the repo and tried to build with: docker build -t odtk:latest retinanet-examples/

I then get this error:

ERROR: failed to copy: httpReadSeeker: failed open: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized
------
 > [1/3] FROM nvcr.io/nvidia/pytorch:20.11-py3@sha256:4c62764ccbd321e6848571eb5d3d1b67539ad4646cae11be403c8ae7f6d12888:
------
failed to copy: httpReadSeeker: failed open: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized

Now I may be making a major mistake that I am unaware of so please let me know if so. I am assuming I can run this within a docker container using my local hardware and on a Windows system. Are these assumptions incorrect? Is there some resource I can use to get started with using NVIDIA repos in docker containers? or is there a simple fix for this error?

I also created an account and an auth key but when I try: docker login nvcr.io, I get this: Error: Cannot perform an interactive login from a non TTY device. 

Any help would be great thanks.

**Comment by yashnv** [comment]
Hi, Windows is not supported by this repo. Ideally you would need a Ubuntu 18.04/20.04 OS installation.

**Comment by ConnorMcShane** [comment]
Thank you for the quick reply. I will install Ubuntu on a VM and try again. Are there any other requirements I should be aware of? can this run on my 1080ti?

**Comment by yashnv** [comment]
1080Ti doesn't have any support for mixed precision. So, functionality of this repo will be limited.
