### ISSUE TITLE
what does resize do with annotations ?

### ISSUE THREAD

**Issue by Alloooshe** [NVIDIA/retinanet-examples#287]
Hi, I have my annotations in absolute coordinate values in the original image, I am sure that max-size is coming to effect in my case, so my question, should I modify the annotations to be in absolute coordinate of the resized image? or should I use relative values for object dimensions.  or maybe the code do that itself ?!

**Comment by alnah005** [comment]
I think what you're looking for should be found here: https://github.com/NVIDIA/retinanet-examples/blob/8f69c390a3009cca74a1a876c17703fcfb13c300/odtk/data.py#L291

**Comment by Alloooshe** [comment]
thank you for your response, if I understand this correctly then the code will recalculate the bbox of objects depending on the resize factor
