### ISSUE TITLE
Location of model file

### ISSUE THREAD

**Issue by sundans** [NVIDIA/retinanet-examples#290]
Hi,
I am new to the use of docker for training/inference. When you train/inference a model using odtk, where should I locate model file (.pth), localhost or inside docker? Also after training finished, where the model is located?
Thanks.

**Comment by yashnv** [comment]
During training, you provide the location of the model, please check the examples. We have pretrained models that can be downloaded for inference/finetuning here: https://github.com/NVIDIA/retinanet-examples#performance
