### ISSUE TITLE
Change in Architecture in comparison with original Pytorch RetinaNet Implementation

### ISSUE THREAD

**Issue by Darshcg** [NVIDIA/retinanet-examples#291]
Hi Nvidia Team,

I wanted to know the change in Architecture made in this repo in comparison with the original Pytorch RetinaNet Implementation(https://github.com/yhenon/pytorch-retinanet). The reason being I have converted Pytorch model(from original Pytorch RetinaNet Implementation) to the ONNX model. But when I am converting from ONNX model to TensorRT,  I am facing issue with Clip, Gather, Cast, ScatterND Ops. So what are the changes made in your RetinaNet code Implementation in order to support TRT conversion successfully?

Thanks,
Darshan

**Comment by yashnv** [comment]
Hello, we have not taken any reference to the above implementation. This code is a research work based directly from the paper.

All of the export to ONNX is the standard torchvision backbone model, plus the head architecture. Rest of the code relating to NMS and Decoding of the model outputs after the convolutions are dealt in the plugins for TensorRT.
