### ISSUE TITLE
Install without docker

### ISSUE THREAD

**Issue by Zumbalamambo** [NVIDIA/retinanet-examples#292]
How to train and infer without having to use the docker container?

**Comment by yashnv** [comment]
We don't want to provide instructions because it gets difficult to manage all the dependencies outside docker, but there are some users who have done this.

**Comment by hungnv21292** [comment]
Hi @Zumbalamambo ,
Could you give me your contact (email or other)?
I want to discuss with you about some problem.
Thanks you
