### ISSUE TITLE
Diverging loss with rotated bbox, how to debug?

### ISSUE THREAD

**Issue by MathijsNL** [NVIDIA/retinanet-examples#294]
Hi There,

I am trying to use a custom dataset with rotated-bbox. Unfortunately this error keeps popping up after a few seconds, no matter what I change.

**What command you ran:**
```
odtk train model.pth --images /workspace/dataset/dataset_train --annotations /workspace/dataset/dataset_train/coco.json  --backbone ResNet50FPN \
    --warmup 12500 --lr 0.00001 \
    --val-images /workspace/dataset/dataset_val --val-annotations /workspace/dataset/dataset_val/coco.json --classes 1 \
    --resize 768 \
    --augment-brightness 0.01 --augment-contrast 0.01 --augment-hue 0.002 \
    --augment-saturation 0.01 --batch 2 --val-iters 2000 --rotated-bbox

```

**The hardware and container that you are using:**
GTX1080 using this repo at 8f69c39

**What was the result you observed:**
`RuntimeError: Loss is diverging!
Try lowering the learning rate.
`

**What was the result you expected:**
Training should start! My biggest issue is that I don't know how to debug this problem. It would be helpfull to get pointed in the right direction on that. Also if someone has a working dataset with rotated bbox I would have something to compare with.

If there is any additional information I can provide please let me know.

**Comment by CliveKBinu** [comment]
I also have the same problem when using --rotated-bbox

**Comment by alnah005** [comment]
You could also restart training and/or retrain from a previous epoch

**Comment by yashnv** [comment]
Using full-precision early on can help proof-read your code, and avoid any infinite loss problems, and is easy to debug if there's some error in converted labelling.
