### ISSUE TITLE
install Isssues on jetson nano 

### ISSUE THREAD

**Issue by SokPhanith** [NVIDIA/retinanet-examples#297]
I run command line like : sudo docker build -t odtk:latest /home/phanith/retinanet-examples/ on jetson nano
got : 
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c pip install --no-cache-dir -e odtk/' returned a non-zero code: 1

**Comment by yashnv** [comment]
Python modules of this repo are not meant to be run on Jetson. Only for exporting and running inference on TensorRT is Jetson recommended.
