### ISSUE TITLE
Leveraging Trained Models in Triton Inference Server

### ISSUE THREAD

**Issue by dlindenbaum** [NVIDIA/retinanet-examples#298]
Hello, 

Thank you for the hard work on this package.

I'm looking to deploy trained models from this library as tensorRT plans in Triton Inference Server.

I believe I need to build some custom plugin layers for Triton Inference Server to read.    

Are there any instructions on how to build the extra layers into a plugin library to support model deployment?

Thank you,

**Comment by yashnv** [comment]
The instructions here show how you can create a dynamic library: https://github.com/NVIDIA/retinanet-examples/tree/main/extras/cppapi
