### ISSUE TITLE
running without docker?

### ISSUE THREAD

**Issue by whoisibooo** [NVIDIA/retinanet-examples#299]
Hi guys, 

it is possible to use this repository without docker? I need it for my research at my university but they don't allow to use docker for permissions reasons etc. 

thanks in advance :) 

best regards, 
whoisibooo

**Comment by bharatsau** [comment]
Yes.. you have to remove the nvidia specific packages, which are used for faster inference.

**Comment by whoisibooo** [comment]
Hi @bharatsau, how can I do that? I have no clue about docker etc. Can you help me?

**Comment by yashnv** [comment]
Using this repo without docker makes it difficult to use many dependencies, so it is not generally recommended.
