### ISSUE TITLE
logdir arg error

### ISSUE THREAD

**Issue by Maxfashko** [NVIDIA/retinanet-examples#30]
Hey. There is a problem using the logging argument. The latest TensorboardX update has changed something: https://github.com/pytorch/ignite/issues/534

https://github.com/NVIDIA/retinanet-examples/blob/f7536930c10ba31146643b7e406f92db73528931/retinanet/train.py#L68

`writer = SummaryWriter(logdir=logdir)`

**Comment by florischabert** [comment]
Fixed in https://github.com/NVIDIA/retinanet-examples/pull/32
Thank you!
