### ISSUE TITLE
rotated bounding box clarification

### ISSUE THREAD

**Issue by alnah005** [NVIDIA/retinanet-examples#300]
I'm currently working on a rotated bounding box task and I was wondering what the `--absolute-angle` flag really does. Specifically, I'm wondering whether -180 and 180 is equivalent to setting the `--absolute-angle` flag.

Additionally, what is the role of having a zero between -45 and 45 [here](https://github.com/NVIDIA/retinanet-examples/blob/c56b7a85c8e4c314b60bfc6d6fea973d6fce059b/odtk/model.py#L44)?

**Comment by yashnv** [comment]
`--absolute-angle` is used for rotating image for data augmentation.

The second angle is used for generating the anchor in feature pyramid levels.

**Comment by alnah005** [comment]
If `--absolute-angle` is used for rotating images for augmentation, then what about `--augment-rotate` and `--augment-free-rotate`?

**Comment by alnah005** [comment]
> `--absolute-angle` is used for rotating image for data augmentation.
> 
> The second angle is used for generating the anchor in feature pyramid levels.

If `--absolute-angle` is used for rotating images for augmentation, then what about` --augment-rotate` and `--augment-free-rotate`?

**Comment by yashnv** [comment]
https://github.com/NVIDIA/retinanet-examples/blob/main/odtk/data.py#L295
Please check this part of the code.

`--augment-free-rotate` was added as an option but never used.

main.py contains descriptions for these arguments. Do check it out.

**Comment by alnah005** [comment]
I've checked main.py and it wasn't clear to me what the difference was. I was hoping I can get a sentence or two that explain the exact difference, but if you think the difference is obvious I'll keep digging. Thank you for your help.
