### ISSUE TITLE
different output python/c++ nms

### ISSUE THREAD

**Issue by natxopedreira** [NVIDIA/retinanet-examples#304]
Hello

I have trained a model and doing inference on python i get a cleaner result than in c++, seems like c++ do not apply same nms even i see same 0.5 threshold value, in fact seems like c++ set no nms at all judging the output result
[https://github.com/NVIDIA/retinanet-examples/blob/213d7ddb9ffb6b97c23af4e1514d20aeba11ea86/extras/cppapi/export.cpp#L62](
https://github.com/NVIDIA/retinanet-examples/blob/213d7ddb9ffb6b97c23af4e1514d20aeba11ea86/extras/cppapi/export.cpp#L62)

[https://github.com/NVIDIA/retinanet-examples/blob/213d7ddb9ffb6b97c23af4e1514d20aeba11ea86/odtk/model.py#L51](https://github.com/NVIDIA/retinanet-examples/blob/213d7ddb9ffb6b97c23af4e1514d20aeba11ea86/odtk/model.py#L51)

Is that the expected behavior?

Thanks

**Comment by yashnv** [comment]
What commands are you using in python and C++? Please list all the commands to reproduce this issue.

**Comment by natxopedreira** [comment]
I found the problem, is on my side. I did not notice i was using a different model in c++ where i changed the scales for training..... sorry for the confusion. With the same models results are the same in c++ and python

If i change scales to train i need to use generate_anchors.py to "generate" those anchors that are hardcoded in export.cpp?

Thanks

**Comment by yashnv** [comment]
Yes
