### ISSUE TITLE
odtk cli

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#316]
When install odtk, the linux have the odtk command.
and it install in /opt/conda/lib/python/site-package/odtk.
How to hide the code ?

**Comment by ghost** [comment]
How do you want to hide the code?

**Comment by alicera** [comment]
Hide the main.py, model.py ....
Let user cant see the main.py code and can use odtk.

**Comment by ghost** [comment]
Just remove the `-e` from pip install step, and delete the code.

**Comment by alicera** [comment]
Thanks you. But
I try to pip install .
The odtk will be install at /opt/conda/lib/python/site-package/odtk/
It will have the main.py, model.py ...

**Comment by ghost** [comment]
Umm, I don't think you can hide that.
