### ISSUE TITLE
Pretrained models rotation detection

### ISSUE THREAD

**Issue by Testbild** [NVIDIA/retinanet-examples#317]
Hello,

is there any place where I can find pretrained models for rotation detection? So that I can do fine tuning with my (rather small) dataset?

EDIT: I just found in this issue: https://github.com/NVIDIA/retinanet-examples/issues/269#issuecomment-819170523 That there has been no pretrained model available. Did that change lately?

Thanks and best regards

**Comment by ghost** [comment]
No, we don't have one.
