### ISSUE TITLE
need to train on master version, but infer on the 19.10

### ISSUE THREAD

**Issue by batrlatom** [NVIDIA/retinanet-examples#320]
I have tried export from main to onnx on master and then try to convert from onnx to tensorrt on 19.10. But it is not compatible. is it possible to make it running somehow?

**Comment by ghost** [comment]
Not really, why do you want to run on older version?

**Comment by batrlatom** [comment]
because version 19.10 works on cuda 10.2, which is not compatible with rtx30xx cards. You need to use cuda 11+ to work with those cards. Then I wanted to deploy the trained model on xavier which in turn has only cuda 10.2. But nevermind, I solved by converting via torch_tensorrt
