### ISSUE TITLE
Jetpack 4.5 + Jetson Xavier NX - Installation

### ISSUE THREAD

**Issue by mpafit02** [NVIDIA/retinanet-examples#322]
Hello, I am using a Jetson Xavier NX, with Jetpack 4.5. I have tried to run the docker build command on my Jetson of the 20.30 branch, and I am getting the following error. Any ideas what's the problem?
@yashnv 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/36662322/145223568-f8c7441b-2dd0-45d0-b359-e869f2dc386d.png)

**Comment by ghost** [comment]
You should only use the inference app on Xavier, not entirely recommended to install the whole repo on Xavier.

**Comment by mpafit02** [comment]
Thank you for your response! What do you mean by saying the inference app?

**Comment by ghost** [comment]
This can be handy if you have an ONNX model exported from host x86 device: https://github.com/NVIDIA/retinanet-examples/tree/main/extras/cppapi

**Comment by mpafit02** [comment]
Thank you very much! Have a nice day!
