### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#323]
```
FROM nvcr.io/nvidia/pytorch:21.09-py3
```
Do you know what is the pytorch:21.09-py3 compose ?
How to check it?
like 
RUN xxx1
RUN xxx2

**Comment by ghost** [comment]
`/opt/pytorch/pytorch/Dockerfile`

**Comment by alicera** [comment]
https://github.com/pytorch/pytorch/blob/master/docker/pytorch/ubuntu_cpu_gpu/Dockerfile
