### ISSUE TITLE
How to configure for running outside of Docker container? (undefined symbol: _ZN2cv8fastFreeEPv)

### ISSUE THREAD

**Issue by monocongo** [NVIDIA/retinanet-examples#38]
I am developing an application based upon the code in this repository and in order to easily debug my code using PyCharm I am running outside of the provided Docker container. I am seeing the same error as is described in issue #15:
```
Traceback (most recent call last):
  File "/home/james/miniconda3/envs/pytorch_retinanet/bin/retinanet", line 6, in <module>
    from retinanet.main import main
  File "/home/james/miniconda3/envs/pytorch_retinanet/lib/python3.7/site-packages/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/home/james/miniconda3/envs/pytorch_retinanet/lib/python3.7/site-packages/retinanet/infer.py", line 13, in <module>
    from .model import Model
  File "/home/james/miniconda3/envs/pytorch_retinanet/lib/python3.7/site-packages/retinanet/model.py", line 8, in <module>
    from ._C import Engine
ImportError: /home/james/miniconda3/envs/pytorch_retinanet/lib/python3.7/site-packages/retinanet/_C.so: undefined symbol: _ZN2cv8fastFreeEPv
```

Can anyone advise as to how I can workaround this issue? My plan is to run my code within the provided container once it has been developed, but in the meantime using the container is problematic since it limits my ability to develop my code using PyCharm (although maybe that's easier to accomplish than fixing this issue). I have tried installing PyCharm into the Docker container with no success so far.  :(

BTW, in case it helps explain why I'm trying this: I want to use the model to perform inference on video streams rather than on a collection of images as is shown in the inference example. I'm cobbling together an application that loads a fine-tuned version of this project's model and performs inference on video frame images. Target platform is a Jetson Nano.

**Comment by monocongo** [comment]
Since nvidia-docker [is not supported on Jetson Nano](https://github.com/NVIDIA/nvidia-docker/issues/214) this appears to be a show stopper for inference using this project's code on that platform. Or am I missing something obvious? Maybe the workaround is to convert the model to a TensorRT engine and then inference using [this approach](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#perform_inference_python)?

**Comment by pkashinkunti** [comment]
Yes, containers are not currently available on the Jetson platforms. Also, not all of the project's dependencies are readily available for Jetson. This makes installing the full project on Jetson difficult, so an alternative workflow is needed. Thankfully, the [Jetpack SDK](https://developer.nvidia.com/embedded/jetpack) contains the basic dependencies that are needed to create/run TRT engines on Jetson like CUDA/cuDNN/TensorRT.

Check out the instructions for creating a TensorRT engine from your model and deploying into a deepstream application [here](https://github.com/NVIDIA/retinanet-examples/tree/master/extras/deepstream). We include instructions that have worked well on Jetson Xavier. Alternatively, you can use the generated TRT engine in your own custom application to perform inference. A basic example of this is provided [here](https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/infer.cpp).

I will mention that deploying on Jetson Nano may not yield great performance, as its Maxwell generation GPU architecture does not support fast FP16/INT8 like the Volta GPU included with Jetson Xavier. Also, support for DeepStream on Jetson Nano is still not available yet, it is expected Q2 2019.

**Comment by monocongo** [comment]
Thanks for the guidance and clarification, @pkashinkunti, very helpful!

**Comment by goktug97** [comment]
#64 Compiled outside of the container

**Comment by azuryl** [comment]
I had installed in in Ubuntu 16.04 outer docker not use Conda
Install opencv-3.4.0
python3 -m pip install opencv-python
python3 -m pip install opencv-contrib-python
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essential
sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get install libxvidcore-dev libx264-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install libatlas-base-dev gfortran pylint
sudo apt-get install python3.5-dev
wget -c https://github.com/opencv/opencv/archive/3.4.0.zip
unzip 3.4.0.zip
cd opencv-3.4.0/
wget https://github.com/opencv/opencv_contrib/archive/3.4.0.zip -O opencv_contrib-3.4.0.zip
unzip opencv_contrib-3.4.0.zip
cd opencv-3.4.0
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH= ../../opencv_contrib-3.4.0/modules -D OPENCV_GENERATE_PKGCONFIG=ON ..
make -j 32
sudo make install
sudo ldconfig

Instal pytorch
python3 -m pip install torch torchvision

Install cocoapi
git clone https://github.com/philferriere/cocoapi
cd cocoapi/PythonAPI/
python3 setup.py install

Install nvidia-dali
python3 -m pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali

upgrade numpy to 1.11.0
python3 -m pip install --upgrade pip
sudo apt-get remove --auto-remove python-numpy
python3 -m pip install -U numpy==1.17.2

Install retinanet-examples
cd retinanet-examples
python3 setup.py clean --all install

CUDA_VISIBLE_DEVICES=0 retinanet infer retinanet_rn50fpn/retinanet_rn50fpn.pth --images ../../coco/val2017/ --annotations ../../coco/annotations/instances_val2017.json --size=2

Loading model from retinanet_rn50fpn.pth...
model: RetinaNet
backbone: ResNet50FPN
classes: 80, anchors: 9
Preparing dataset...
loader: pytorch
resize: 800, max: 1333
backend: pytorch
device: 1 gpu
batch: 2, precision: mixed
Running inference...
[ 914/5000] 0.131s/2-batch (fw: 0.130s), 15.2 im/s
[1814/5000] 0.133s/2-batch (fw: 0.133s), 15.0 im/s
[2726/5000] 0.132s/2-batch (fw: 0.131s), 15.2 im/s
[3632/5000] 0.133s/2-batch (fw: 0.132s), 15.1 im/s
[4526/5000] 0.134s/2-batch (fw: 0.134s), 14.9 im/s
[5000/5000] 0.132s/2-batch (fw: 0.132s), 15.1 im/s
Gathering results...
Writing detections.json...
Evaluating model...
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.359
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.551
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.387
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.204
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.403
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.473
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.309
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.494
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.523
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.333
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.578
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.675
