### ISSUE TITLE
Export model with non-default input size

### ISSUE THREAD

**Issue by fungidick** [NVIDIA/retinanet-examples#41]
Hi all, hope you can help with this.

I successfully trained the network and deployed it to a Jetson Xavier. Here it succesfull runs at the default resolution (1280x1280). I would like to have it run at 720x720 however.

This is where my problem occurs: when I try to export my .pth to a .onnx file with a non-default resolution, I get the following error.

Command : `retinanet export model.pth model.onnx --size 720`
Output: 

> Loading model from model.pth...
>      model: RetinaNet
>   backbone: ResNet50FPN
>    classes: 1, anchors: 9
> Exporting to ONNX...
> Traceback (most recent call last):
>   File "/opt/conda/bin/retinanet", line 11, in <module>
>     load_entry_point('retinanet', 'console_scripts', 'retinanet')()
>   File "/workspace/retinanet/retinanet/main.py", line 181, in main
>     worker(0, args, 1, model, state)
>   File "/workspace/retinanet/retinanet/main.py", line 164, in worker
>     exported = model.export(input_size, args.batch, precision, calibration_files, args.calibration_table, args.verbose, onnx_only=onnx_only, opset=args.opset)
>   File "/workspace/retinanet/retinanet/model.py", line 226, in export
>     torch.onnx.export(self.cuda(), zero_input, onnx_bytes, *extra_args)
>   File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
>     return utils.export(*args, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 111, in export
>     _retain_param_name=_retain_param_name)
>   File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 313, in _export
>     _retain_param_name)
>   File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 237, in _model_to_graph
>     graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
>   File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 204, in _trace_and_get_graph_from_model
>     trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
>   File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 219, in get_trace_graph
>     return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 276, in forward
>     out = self.inner(*trace_inputs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self._slow_forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
>     result = self.forward(*input, **kwargs)
>   File "/workspace/retinanet/retinanet/model.py", line 104, in forward
>     features.extend(backbone(x))
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self._slow_forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
>     result = self.forward(*input, **kwargs)
>   File "/workspace/retinanet/retinanet/backbones/fpn.py", line 44, in forward
>     p4 = F.interpolate(p5, scale_factor=2) + p4
> RuntimeError: The size of tensor a (46) must match the size of tensor b (45) at non-singleton dimension 3

Does this mean I should define my input size correctly during training, or ?

Thanks!

**Comment by florischabert** [comment]
Export dimensions have to be a multiple of `model.stride`. For standard ResNet FPN it should be a multiple of 128.

**Comment by fungidick** [comment]
That did the trick, thanks!
