### ISSUE TITLE
Build/Run on Windows in Anaconda Python 3

### ISSUE THREAD

**Issue by catskillsresearch** [NVIDIA/retinanet-examples#49]
Would it be possible to get an installer for Anaconda Python 3 into the Conda channel, or at least get this GitHub in shape so that "python setup.py install" will work on a Windows 10 Conda installation provisioned with the following packages:

cudatoolkit               10.0.130                      0  
cupy-cuda101              6.0.0                    pypi_0    pypi
pytorch                   1.1.0           py3.7_cuda100_cudnn7_1    pytorch

I am running on core i9 processors, Windows 10 Home Edition, with an NVidia R2080ti GPU.

**Comment by james-nvidia** [comment]
Thank you for your suggestion. We don't have any immediate plans to support a Windows Conda install, but we will keep it on the feature request list.
