### ISSUE TITLE
Name of input and output layers

### ISSUE THREAD

**Issue by FamousDirector** [NVIDIA/retinanet-examples#5]
What are the names of the input and output layer nodes of the exported `.plan` model? Also what would the dimensions of the output be? Are they fixed?

**Comment by florischabert** [comment]
We don't explicitly set the input name (I think it defaults to "x").
The outputs are:
- "scores": the scores array of size `detections`
- "boxes": the boxes of size `detections * 4`
- "classes": the classes of the detections of size `detections`

`detections` is defined [here](https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/model.py#L33) and defaults to 100.
