### ISSUE TITLE
>>> from retinanet._C import Engine throws error

### ISSUE THREAD

**Issue by elyor-anyvision** [NVIDIA/retinanet-examples#51]
I can run training according to README.md -- all command lines work. 
However, it is not working when I use it in python as follows:
![image](https://user-images.githubusercontent.com/31479847/61176753-5500dd00-a5be-11e9-9f25-57725466e487.png)

My question is that why is it working with command line when I train a model, while NOT working inside python?

Thanks

**Comment by coolzhangfeng** [comment]
I have encountered the same mistake as you. Have you solved it?

**Comment by janBoucek** [comment]
`python3 setup.py install` solved it for me.

**Comment by elyor-anyvision** [comment]
Before importing, first import torch and other libraries and then ._C.

**Comment by coolzhangfeng** [comment]
I tried the method you said,  the same error.

**Comment by coolzhangfeng** [comment]
> Before importing, first import torch and other libraries and then ._C.
I tried the method you said, the same error.

**Comment by azuryl** [comment]
me too
