### ISSUE TITLE
Core Dumped

### ISSUE THREAD

**Issue by gosha20777** [NVIDIA/retinanet-examples#59]
```
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Bus error (core dumped)
```
nvidia 950m

**Comment by KNaudin** [comment]
This is caused by a shared_memory error.
If you are using the Docker version, make sure ton add the `--icp=host` option to the docker run command.
This will give the container enough shared memory to be able to run the training.

**Comment by gosha20777** [comment]
Thank you a lot!
