### ISSUE TITLE
Pre-trained COCO Model Weights

### ISSUE THREAD

**Issue by FamousDirector** [NVIDIA/retinanet-examples#6]
In your README it states that there are pretrained backbones for the COCO dataset. However I am not able to find where they are located. Where can I find them?

**Comment by florischabert** [comment]
We are initializing backbones using weights from pre-trained pytorch/vision models when doing full training, [see code](https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/backbones/resnet.py#L18).
You can find the url of these weights from pytorch/vision [here](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L9). I believe these were trained on ImageNet.

We are working on providing fully pre-trained models where the detection model has been trained on COCO, stay tuned.

**Comment by mbufi** [comment]
Hi @florischabert Thanks for providing such a good repo! Any potential dates for the release of the pretrained model?

**Comment by florischabert** [comment]
Sorry, it's not clear yet when it'll be available. I'll ping this thread when it is.

**Comment by chowkamlee81** [comment]
Any pretrained retinanet model available in this fork.

**Comment by EdwardYGLi** [comment]
up on pretrained weights
