### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.onnx.symbolic'

### ISSUE THREAD

**Issue by WillieMaddox** [NVIDIA/retinanet-examples#60]
Greetings,
I've been debugging a problem for a few hours and starting to run out of ideas.  Thought you guys might have some insight.  Here are my steps:

I installed the latest docker image with,
```
docker run --rm --ipc=host --gpus device=0 -it nvcr.io/nvidia/pytorch:19.08-py3
```
The device is a single 2080Ti.  From inside the container, installed retinanet-examples:
```
root@56055c8afabb:/workspace# pip install --no-cache-dir git+https://github.com/nvidia/retinanet-examples
```
Trained a coco model as per README and saved result to `retinanet_rn50fpn.pth`.  My problem is when I try to create the engine.plan:
```
root@56055c8afabb:/workspace# retinanet export retinanet_rn50fpn.pth engine.plan
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 182, in main
    worker(0, args, 1, model, state)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 165, in worker
    exported = model.export(input_size, args.batch, precision, calibration_files, args.calibration_table, args.verbose, onnx_only=onnx_only, opset=args.opset)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/model.py", line 207, in export
    import torch.onnx.symbolic
ModuleNotFoundError: No module named 'torch.onnx.symbolic'
```

Not much on the web about this one.  Any Ideas?

Thanks,

-Willie

My host machine:
Ubuntu-16.04
nvidia-418.87
cuda-10.1.243
cudnn-7.5.0.56
tensorrt-5.1.5.0

**Comment by balezz** [comment]
Have the same bug with nvcr.io/nvidia/pytorch:19.07-py3

**Comment by yashnv** [comment]
@balezz @WillieMaddox can you guys try out the [19.09](https://github.com/NVIDIA/retinanet-examples/tree/19.09) branch?

You'll need to pull nvcr.io/nvidia/pytorch:19.09-py3 container and checkout the 19.09 branch before using pip install.

**Comment by joskaaaa** [comment]
> @balezz @WillieMaddox can you guys try out the [19.09](https://github.com/NVIDIA/retinanet-examples/tree/19.09) branch?

Tested with both 19.09 and 19.10 branch, with the same result. 

Google Cloud with Debian 9 and CUDA 10.0.

**Comment by yashnv** [comment]
Did you change the branch from `master` to `19.09` before pip install step?

**Comment by joskaaaa** [comment]
> Did you change the branch from `master` to `19.09` before pip install step?

You're right, I realized as soon as I posted that.

Successfully converted to ONNX by building as such:

`docker build -t retinanet:19.09 retinanet-examples/`
`docker run --gpus all --rm  -v ~/Documents/docker:/docker  --ipc=host -it retinanet:19.09 `

**Comment by WillieMaddox** [comment]
I can also verify onnx conversion passes when using `19.09` branch in a `nvcr.io/nvidia/pytorch:19.10-py3` container.  Thanks for the updates.

**Comment by james-nvidia** [comment]
It looks like this issue has been solved. Thanks for trying the new branch.
