### ISSUE TITLE
Hardcoded Anchors in Model.py

### ISSUE THREAD

**Issue by Tys-Lowde** [NVIDIA/retinanet-examples#61]
I want to train a completely custom dataset, with classes that are completely random. I've converted the annotations to COCO format and retrained, but the results were...useless ahha.

The next thing i want to try is reduce the anchor size, ratio and strides, to those i use in the Keras-Retinanet repo. The anchors are hardset in models.py Will there be any problem if i edit both the ratios and strides? I don't see anywhere to change the actual size of the anchors though?

**Comment by yashnv** [comment]
@Tys-Lowde, if you look [here](https://github.com/NVIDIA/retinanet-examples/blob/59216e6aca730c705850586be9ee134009dd61e0/retinanet/model.py#L25), you can change the anchor ratio and scales which will be used to generate anchor boxes in `retinanet/box.py`.

**Comment by Tys-Lowde** [comment]
Hi Yashv,
Yep as i said i can see that in models.py the anchor ratio, stride and scales are all set there. But unlike other retinanet implementations i cant see a place to set the **size** of the anchors. 

The calculations to optimise the ratios and strides that ive used take into account size of the smallest anchor.

**Comment by yashnv** [comment]
The **size** is calculated from the ratio, stride and/or scale. The anchors are generated by defining aspect ratios and scales. Then those anchors are used to come up with predicted objects from the FPN.

In addition to this, I'd like to suggest that you check your ground truth boxes, and depending on what those are you need to tune the scales and ratios.

**Comment by Tys-Lowde** [comment]
Cheers Yashnv.

**Comment by Alloooshe** [comment]
how exactly we can choose raito and scale for boxes, for example I have objects of large aspect ratio, 20:1 30:1 and large scales 0.7 of the width of the image, my question is how to change the code accordingly, should I set ratios to [20,30] and scales to [0.7] ? I tried so but I am getting no detection suggesting that my choice is not correct
