### ISSUE TITLE
What does retinanet.model.Model.stride represent?

### ISSUE THREAD

**Issue by matthew-jurewicz** [NVIDIA/retinanet-examples#63]

**Comment by yashnv** [comment]
Strides is derived from the network backbone (ResNetFPN). Strides is used to define the inputs in FPN.
From the [RetinaNet](https://arxiv.org/pdf/1708.02002.pdf) paper:
```
RetinaNet uses feature pyramid levels P3 to P7, where P3 to P5 are computed 
from the output of the corresponding ResNet residual stage (C3 through C5) 
using top-down and lateral connections just as in [20], P6 is obtained via a 
3×3 stride-2 conv on C5, and P7 is computed by applying ReLU followed by 
a 3×3 stride-2 conv on P6. This differs slightly from [20]: 
(1) we don’t use the high-resolution pyramid level P2 for computational reasons, 
(2) P6 is computed by strided convolution instead of downsampling, and 
(3) we include P7 to improve large object detection. 
These minor modifications improve speed while maintaining accuracy.
```
[[20]](https://arxiv.org/pdf/1612.03144.pdf)
The number of sizes/strides/inputs = number of pyramids

**Comment by yashnv** [comment]
Hope your question has been answered. Closing this issue now.

**Comment by matthewjur1** [comment]
I'm still a little confused. What are "number of sizes" and "inputs"? I'm assuming "number of pyramids" means number of pyramid levels.

**Comment by yashnv** [comment]
Yes, you are correct. Number of sizes represents the dimensions of anchor boxes from pyramid levels P3 to P7. The pyramid levels are obtained by performing convolution on top of the feature map outputs of ResNet to construct rich multi-scale feature pyramid from one single resolution input image.
