### ISSUE TITLE
[Binaries] Jetson TX2 and Desktop

### ISSUE THREAD

**Issue by goktug97** [NVIDIA/retinanet-examples#64]
I've successfully compiled and used RetineNet on Jetson TX2 and Desktop

### Jetson Tx2
Python 3.6 RetinaNet:
https://drive.google.com/file/d/1zM_0ErGSCexyLZXTk9j4N2sjlwV2w7lD/view?usp=sharing

Python 3.6 Apex:
https://drive.google.com/file/d/1Yk9mHoT8MwYer41IbhLnIVw-oBzgS-iY/view?usp=sharing

Install all dependencies: Numpy, PyCocoTools, Enscons, Scons etc...
`python3 -m pip install retinanet-0.1-cp36-cp36m-linux_aarch64.whl --user --no-deps`
`python3 -m pip install apex-0.1-cp36-cp36m-linux_aarch64.whl --user`

Install Apex after RetinaNet. 

### Desktop 64bit Ubuntu 18.04 CUDA 10 Python 3.6
Install CUDA10 CUDNN and TensorRT and Retinanet dependencies.

Python 3.6 RetinaNet:
https://drive.google.com/file/d/1kgT9iQ1qLo9eOIh1fmjlbE1H0UsfuFfu/view?usp=sharing

Python 3.6 Apex:
https://drive.google.com/file/d/1xun25reQ2qHaAk2FlECSEaR2Edh3U4lt/view?usp=sharing

`python3 -m pip install retinanet-0.1-cp36-cp36m-linux_x86_64.whl --user --no-deps`
`python3 -m pip install apex-0.1-cp36-cp36m-linux_x86_64.whl--user`

**Comment by yashnv** [comment]
Did you mean to comment this on [#38](https://github.com/NVIDIA/retinanet-examples/issues/64)?. If so, then this doesn't need to be an issue.

**Comment by yashnv** [comment]
Thanks for the contribution. I am closing this issue now.

**Comment by aidonchuk** [comment]
@goktug97 Hi! Can describe your setup for building to Jetson TX2? Please.

**Comment by azuryl** [comment]
@goktug97 how to install use GPU,your guide is CPU

**Comment by azuryl** [comment]
@goktug97 Can describe your setup for building to Jetson TX2 too

**Comment by goktug97** [comment]
Jetpack 4.2
Python 3.6
Pytorch V1.1 from https://devtalk.nvidia.com/default/topic/1049071/pytorch-for-jetson-nano/

**Comment by azuryl** [comment]
I had installed in in Ubuntu 16.04 outer docker
Install opencv-3.4.0
python3 -m pip install opencv-python
python3 -m pip install opencv-contrib-python
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essential
 sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
 sudo apt-get install libxvidcore-dev libx264-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install libatlas-base-dev gfortran pylint
sudo apt-get install  python3.5-dev
wget -c https://github.com/opencv/opencv/archive/3.4.0.zip
unzip 3.4.0.zip
cd opencv-3.4.0/
wget https://github.com/opencv/opencv_contrib/archive/3.4.0.zip -O opencv_contrib-3.4.0.zip
unzip opencv_contrib-3.4.0.zip
cd  opencv-3.4.0
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH= ../../opencv_contrib-3.4.0/modules -D OPENCV_GENERATE_PKGCONFIG=ON   ..
make -j 32
sudo make install
sudo ldconfig

Instal pytorch
python3 -m pip install torch torchvision

Install  cocoapi
git clone https://github.com/philferriere/cocoapi
cd cocoapi/PythonAPI/
python3 setup.py install

Install nvidia-dali
 python3 -m pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali

upgrade numpy to 1.11.0
python3 -m pip install --upgrade pip
sudo apt-get remove --auto-remove python-numpy
 python3 -m pip install -U numpy==1.17.2

Install retinanet-examples
cd retinanet-examples
python3 setup.py clean --all install

CUDA_VISIBLE_DEVICES=0 retinanet infer retinanet_rn50fpn/retinanet_rn50fpn.pth --images ../../coco/val2017/   --annotations ../../coco/annotations/instances_val2017.json  --size=1

**Comment by aidonchuk** [comment]
Thanks a lot, I allready do the same)
