### ISSUE TITLE
Support for TensorRT 6

### ISSUE THREAD

**Issue by FamousDirector** [NVIDIA/retinanet-examples#67]
With the newly released `pytorch:19.09-py3` container, will there be support or an update for TensorRT 6?

**Comment by yashnv** [comment]
Thank you for your suggestion. We are working on upgrading to the latest version of TensorRT, meanwhile having backward compatibility, and hope to release a new version of this code soon.

**Comment by yashnv** [comment]
@FamousDirector can you please try out the [19.09 branch](https://github.com/NVIDIA/retinanet-examples/tree/19.09)?

**Comment by FamousDirector** [comment]
I'm not currently setup for training a new model but I have tested exporting a pre-existing `.pth`. The exported model works fine and is equivalent in terms of processing time and accuracy.
You may also want to consider making the exporting process less verbose, or print to a file. There is A LOT of output. Also please note the misspelled Docker repo path (I'm assuming the `nvidian` is an internal pointer vs the external `nvidia`).

**Comment by yashnv** [comment]
@FamousDirector thanks for pointing that out. The verbosity occurring from export is resulting from the changes in TensorRT 6 which is default. We have pushed the changes to suppress verbosity to false by default.

**Comment by yashnv** [comment]
Closing this, changes have been pushed to master.
