### ISSUE TITLE
Other result on TensorRT

### ISSUE THREAD

**Issue by kolyanchik** [NVIDIA/retinanet-examples#68]
Different results on the same tests in PyTorch and TensorRT. retinanet_rn50fpn.pth from 19.04
TensorRT version, this is the main use case any network in development. What could be a significant difference?

TRT:
retinanet export retinanet_rn50fpn.pth engine.plan --size 800 800 --batch 8
retinanet infer engine.plan --images  ./coco/images/val2017/ --annotations ./coco/annotations/instances_val2017.json
Loading CUDA engine from engine.plan...
Preparing dataset...
    loader: pytorch
    resize: 800, max: 800
   backend: tensorrt
    device: 1 gpu
     batch: 2, precision: unknown
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.29117

PyTorch
infer retinanet_rn50fpn.pth --resize 800 --max-size 800 --images  ./coco/images/val2017/ --annotations ./coco/annotations/instances_val2017.json
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Preparing dataset...
    loader: pytorch
    resize: 800, max: 800
   backend: pytorch
    device: 1 gpu
     batch: 2, precision: mixed
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.33720

**Comment by kolyanchik** [comment]
if you use size 640, the results are the same. Why?))

**Comment by yashnv** [comment]
It could be the batch size set during export, that can affect the inference in TensorRT engine. Having same batch size for larger size will affect the performance of the engine.
