### ISSUE TITLE
Custom datasets

### ISSUE THREAD

**Issue by MSJawad** [NVIDIA/retinanet-examples#69]
Are there any plans to be able to train on custom datasets? Currently using Yolov3 on a project. Am i right in assuming RetinaNet has a higher mAP on datasets like MSCOCO and Pascal VOC?

**Comment by yashnv** [comment]
Given you have the correct annotations (similar JSON format to MS COCO) for the corresponding training images, training on custom datasets is feasible.
Without any tests, there is no point in making such an assumption. Speed and accuracy are the factors that need to be taken into consideration. Having a bit higher mAP on similar IoU with loss in speed, or vice versa, is not the goal here.
