### ISSUE TITLE
How to create a model with lower input image resolution

### ISSUE THREAD

**Issue by neom89** [NVIDIA/retinanet-examples#71]
Hi, 

I can see in the release that all the models have an input image resolution of 1280x1280. This is making the inference very slow on my Jetson Nano. 
Is there a way to reduce the size of the input image to a customized value?

**Comment by yashnv** [comment]
There is `--resize` and `--max-size` flags in [infer](https://github.com/NVIDIA/retinanet-examples/blob/19.09/retinanet/main.py#L56), and `--size` in [export](https://github.com/NVIDIA/retinanet-examples/blob/19.09/retinanet/main.py#L64).

**Comment by neom89** [comment]
@yashnv Thanks for the reply.

For lower resolution image, what are the suggested values of the anchors given below 

https://github.com/NVIDIA/retinanet-examples/blob/07502b0b2f31c2e6b085e458d9b6c9d204b25c7b/extras/cppapi/export.cpp#L47

**Comment by yashnv** [comment]
There was a [similar issue](https://github.com/NVIDIA/retinanet-examples/issues/54). These values are not related to image input size.

**Comment by neom89** [comment]
Thanks for the reply.

I reduced the resolution of the input layer to 480x480. When I run the engine created for Jetson Nano on it, I get the following error : 
**Segmentation fault (core dumped)**

However, when I am running other models in the release with default input size, everything runs fine.

Can you suggest any solution or point to any documentation for solving this problem?

**Comment by yashnv** [comment]
Can you list the exact commands you used for export and inference.

**Comment by neom89** [comment]
For export of .pth model to onnx model:
` retinanet export model.pth model.onnx --size 480`
For generating engine (.plan) file from onnx model:
`./export model.onnx model.plan`
For inference using deepstream:
deepstream-app -c config.txt

I used sample.mp4 as file source in deepstream config file, and output.mp4 as file sink.

**Comment by yashnv** [comment]
Is the error given from export or infer?

**Comment by neom89** [comment]
From infer.

**Comment by yashnv** [comment]
Can you try out the retinanet python interface for export, and depending on the onnx version, I would suggest you try `--opset 8` flag during export

**Comment by neom89** [comment]
I am a little confused. I have used two export commands, one to export model.pth to model.onnx and the other for exporting model.onnx to model.plan. 

I had exported the model.pth file to model.onnx file using the retinanet python interface. I can not use the export command using retinanet python interface to generate model.plan file because it needs to be run on Jetson Nano and Pytorch can not be installed on an arm-based device.

Are you suggesting to add `--opset 8` argument to the export command for creating model.onnx?

**Comment by yashnv** [comment]
Yeah, to make sure onnx runtime is compatible. `--opset 8` only for python interface for export to model.onnx, you can't use opset flag on cppapi.

**Comment by neom89** [comment]
After looking at the readme file, I can see the `--opset 8` is used if the version of TensorRT is older than 5.1. In my Jetson Nano setup I am using TensorRT 5.1.6 and CUDA 10.0. (installed from Jetpack)

However, I can see that in the docker image, the version of TensorRT is 5.1.5 and version of CUDA is 10.1. Do you think the version mismatch could be an issue?

**Comment by neom89** [comment]
Update:
I generated model.onnx using `--opset 9` then ran following commands on the Jetson Nano

`./export model.onnx mode.plan`

`deepstream-app -c config.txt`

I got the following error in the  the application was killed :

```Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:175>: Pipeline running

Creating LL OSD context new
NvMMLiteOpen : Block : BlockType = 4 
===== NVMEDIA: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4 
ERROR from qtdemux0: Internal data stream error.
Debug info: qtdemux.c(6073): gst_qtdemux_loop (): /GstPipeline:pipeline/GstBin:multi_src_bin/GstBin:src_sub_bin0/GstURIDecodeBin:src_elem/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason error (-5)
Quitting
App run failed
```

**Comment by james-nvidia** [comment]
Can you share your `config.txt` file with us?

**Comment by neom89** [comment]
Following are the contents of config.txt file which I am using : 

`[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=0
rows=2
columns=4
width=1920
height=1080
gpu-id=0
#(0): nvbuf-mem-default - Default memory allocated, specific to particular platform
#(1): nvbuf-mem-cuda-pinned - Allocate Pinned/Host cuda memory, applicable for Tesla
#(2): nvbuf-mem-cuda-device - Allocate Device cuda memory, applicable for Tesla
#(3): nvbuf-mem-cuda-unified - Allocate Unified cuda memory, applicable for Tesla
#(4): nvbuf-mem-surface-array - Allocate Surface Array memory, applicable for Jetson
nvbuf-memory-type=0

[source0]
enable=1
#Type - 1=CameraV4L2 2=URI 3=MultiURI 4=RTSP
type=3
num-sources=1
uri=file://./videos/sample_video.mp4
gpu-id=0
# (0): memtype_device   - Memory type Device
# (1): memtype_pinned   - Memory type Host Pinned
# (2): memtype_unified  - Memory type Unified
cudadec-memtype=0

[source1]
enable=0
#Type - 1=CameraV4L2 2=URI 3=MultiURI 4=RTSP
type=3
num-sources=4
uri=file://./videos/drones_0%d.mp4
gpu-id=0
# (0): memtype_device   - Memory type Device
# (1): memtype_pinned   - Memory type Host Pinned
# (2): memtype_unified  - Memory type Unified
cudadec-memtype=0

[streammux]
gpu-id=0
##Boolean property to inform muxer that sources are live
live-source=0
batch-size=1
##time out in usec, to wait after the first buffer is available
##to push the batch even if the complete batch is not formed
batched-push-timeout=400000
## Set muxer output width and height
width=512
height=512
##Enable to maintain aspect ratio wrt source, and allow black borders, works
##along with width, height properties
enable-padding=1
nvbuf-memory-type=0


# config-file property is mandatory for any gie section.
# Other properties are optional and if set will override the properties set in
# the infer config file.
[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=infer_config.txt

[tracker]
enable=1
tracker-width=512
tracker-height=512
ll-lib-file=/opt/nvidia/deepstream/deepstream-4.0/lib/libnvds_mot_iou.so
#ll-config-file required for IOU only
ll-config-file=iou_config.txt
gpu-id=0
enable-batch-process=1


[osd]
enable=1
gpu-id=0
border-width=1
text-size=12
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Arial
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0


[sink0]
enable=0
#Type - 1=FakeSink 2=EglSink 3=File
type=2
sync=1
source-id=0
gpu-id=0
nvbuf-memory-type=0

[sink1]
enable=1
type=3
#1=mp4 2=mkv
container=1
#1=h264 2=h265
codec=1
sync=0
#iframeinterval=10
bitrate=8000000
output-file=out.mp4
source-id=0

[sink2]
enable=0
#Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming
type=4
#1=h264 2=h265
codec=1
sync=0
bitrate=4000000
# set below properties in case of RTSPStreaming
rtsp-port=8554
udp-port=5400



[tests]
file-loop=1
`

**Comment by james-nvidia** [comment]
What's happening in `infer_config.txt`? Is the custom parser being called?

**Comment by james-nvidia** [comment]
Did you manage to solve this problem?

**Comment by james-nvidia** [comment]
Closed, as problem appears to be solved. Please re-open if there is still a problem.
