### ISSUE TITLE
trying to remove p6 and p7 layers from the model structure

### ISSUE THREAD

**Issue by anjalinagel12** [NVIDIA/retinanet-examples#73]
I am getting this error:

RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "backbones.ResNet18FPN.pyramid6.weight", "backbones.ResNet18FPN.pyramid6.bias", "backbones.ResNet18FPN.pyramid7.weight", "backbones.ResNet18FPN.pyramid7.bias". 

Any help will be highly appreciated.

**Comment by james-nvidia** [comment]
Could you please explain which command caused that error?
Have you changed the code at all?

That error is trying to load weights for p6 and p7 into a model that has no space for them.
`model.py` contains an example of ignoring some layers when loading in weights. Have you tried something similar?
```
ignored = ['cls_head.8.bias', 'cls_head.8.weight']
weights = { k: v for k, v in chk['state_dict'].items() if k not in ignored }
```

**Comment by yashnv** [comment]
Closing this issue, will keep answering questions related to architecture changes.
