### ISSUE TITLE
Inference issue (Python API vs C++ API)

### ISSUE THREAD

**Issue by KerwinSkyRec** [NVIDIA/retinanet-examples#75]
Hi everyone,

I'm trying to inference image by using retinanet model in [Python API](https://github.com/NVIDIA/retinanet-examples/tree/master/retinanet) and [C++ API](https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi)
 Here is my step:
1. I get a `model.pth` after I training.
2. transfer `model.pth` using `retinanet export model.pth model.onnx` into onnx model
3. export `model.onnx` using C++ API `export{.exe} model.onnx model.plan` to plan file
4. Inference the same picture using `retinanet infer .... (with dali)` and `infer{.exe} ....`

I expected the same results, but I got slight difference between using Python API and C++ API
So I'm trying to compare the difference between [Python](https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/infer.py) and [C++](https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/infer.cpp)
And I print the input array after normalization, I realized the input in Python API and C++ API are different.
Is there something wrong?

Does anyone get the same result by using Python API and C++ API?

**Comment by yashnv** [comment]
@KerwinSkyRec can you please provide the exact commands you used? Also please post the results you found out.

**Comment by KerwinSkyRec** [comment]
> @KerwinSkyRec can you please provide the exact commands you used? Also please post the results you found out.

Here are my command:
1. `retinanet export model.pth model.onnx --size 768 768` <- I train my model with size (768, 768), and export model using this command
2. `export{.exe} model.onnx model.plan` <- I use this command to generate plan file.
3. `retinanet infer model.pth --images /path/to/images/ --batch 8 --resize 768 --max-size 768 --with-dali` <- I use this command to inference a picture with Python API
4. `infer{.exe} model.plan /path/to/image.jpg` <- I use this command to inference a picture with C++ API

I inference the same picture by using C++ and Python, and I didn't change any logic in both codes.
But having a bounding box detected in Python API is not detected by C++ API.
I only write some code to help myself print some information into file, like image's matrix, image after normalization... etc.
And I found the same image after normalization having lots different value in each element.

For example:
```
## Final 10 elements in image after normalization (Python API)
.
.
.
-1.8044
-1.8044
-1.8044
-1.8044
-1.8044
-1.8044
-1.8044
-1.8044
-1.8044
-1.8044
``` 
```
## Final 10 elements in image after normalization (C++ API)
.
.
.
-0.39268
-0.444967
-0.427538
-0.427538
-0.427538
-0.479826
-0.514684
-0.497255
-0.514684
-0.514684
```  

Is there something different way to do image preprocess between C++ and Python?

**Comment by KerwinSkyRec** [comment]
> @KerwinSkyRec can you please provide the exact commands you used? Also please post the results you found out.

Here are my command:

1. `retinanet export model.pth model.onnx` --size 768 768 <- I train my model with size (768, 768), and export model using this command
2. `export{.exe} model.onnx model.plan` <- I use this command to generate plan file.
3. `retinanet infer model.pth --images /path/to/images/ --batch 8 --resize 768 --max-size 768 --with-dali` <- I use this command to inference a picture with Python API
4. `infer{.exe} model.plan /path/to/image.jpg` <- I use this command to inference a picture with C++ API

I inference the same picture by using C++ and Python, and I didn't change any logic in both codes.
But having a bounding box detected in Python API is not detected by C++ API.
I only write some code to help myself print some information into file, like image's matrix, image after normalization... etc.
And I found the same image after normalization having lots different value in each element.

For example:

```
## 8 elements in image after normalization (Python API)
.
.
.
-2.1179
-2.0323
-2.1179
-2.1008
-2.1179
-2.1008
-2.1008
-2.0837
.
.
.
.
```
```
## 8 elements in image after normalization (C++ API) (the same index in Python)
.
.
.
-2.08365
-1.98091
-2.03228
-2.01516
-2.08365
-1.98091
-1.98091
-1.98091
.
.
.
.
```
Is there something different way to do image preprocess between C++ and Python?

**Comment by james-nvidia** [comment]
@KerwinSkyRec , the python and C++ versions handle images slightly differently. The C++ API is intended to be an example of how to use retinanet for inference, rather than a full solution.

The python API preserves the aspect ratio of the images, and then pads to make all images in the batch the same size. By contrast the C++ API resizes and stretches to match the input dimensions of the TRT engine -- it does not use padding to preserve the aspect ratio.

Does this explain the differences you observed? You could replace the resize part of the C++ API to replicate the behaviour of the python version.
https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/infer.cpp#L31

Are you using video data? If so the NVIDIA DeepStream SDK will handle the resizing for you.

**Comment by KerwinSkyRec** [comment]
> @KerwinSkyRec , the python and C++ versions handle images slightly differently. The C++ API is intended to be an example of how to use retinanet for inference, rather than a full solution.
> 
> The python API preserves the aspect ratio of the images, and then pads to make all images in the batch the same size. By contrast the C++ API resizes and stretches to match the input dimensions of the TRT engine -- it does not use padding to preserve the aspect ratio.
> 
> Does this explain the differences you observed? You could replace the resize part of the C++ API to replicate the behaviour of the python version.
> https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/infer.cpp#L31
> 
> Are you using video data? If so the NVIDIA DeepStream SDK will handle the resizing for you.

Thanks for your reply.
I understand only Python version using padding, so the input previously  i mentioned already rule out this possibility, cause I trained my model with size of (768, 768) and so does my input image.

I was wondering if precision cause this issue becasue defult precision of float using in Python version and C++ version are different.

But I think this issue would not be a critical problem, and I will trying to trace this issue later

Thanks for everyone's help.

**Comment by RituYadav92** [comment]
Hi @KerwinSkyRec,

Have you fixed this issue? If you found any workaround, then please share.

Thanks
