### ISSUE TITLE
Inference on 960X540 image on Jetson Xavier - custom resolution

### ISSUE THREAD

**Issue by rnekk2** [NVIDIA/retinanet-examples#76]
I trained a ResNet 50 FPN model using my custom data. The training finished successfully. I was able to convert the .pth file to onnx using the custom size 960 540 without any issues

retinanet export resnet50fpn.pth resnet50fpn_960x540.onnx --size 960 540

I copied the model to Xavier and exported the onnx file to plan successfully.

./export resnet50fpn_960x540.onnx resnet50fpn_960x540.plan
Building engine...
Building FP16 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Writing to resnet50fpn_960x540.plan...

When I run infer it does not give any results.

./infer resnet50fpn_960x540.onnx.plan ~/image2.jpg
Loading engine...
Preparing data...
image dimensions960540
Running inference...
Took 0.0366519 seconds per inference.

When I convert without giving the size parameter while converting to onnx, I am getting the results.

retinanet export resnet50fpn.pth resnet50fpn.onnx

./export resnet50fpn.onnx resnet50fpn.plan
Building engine...
Building FP16 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Writing to resnet50fpn.plan...

./infer resnet50fpn.plan ~/image2.jpg
Loading engine...
Preparing data...
image dimensions12801280
Running inference...
Took 0.103153 seconds per inference.
Found box {172.82, 717.462, 302.18, 844.987} with score 0.779297 and class 1
Found box {194.969, 706.128, 375.584, 840.411} with score 0.424316 and class 1
Found box {114.109, 704.306, 273.932, 867.068} with score 0.406494 and class 1
Found box {67.8826, 714.315, 182.079, 913.265} with score 0.398926 and class 1
Found box {283.829, 725.115, 417.894, 830.538} with score 0.380299 and class 1
Found box {624.384, 370.998, 1146.1, 1191.19} with score 0.36377 and class 4
Found box {637.548, 318.723, 1224.6, 1073.07} with score 0.347656 and class 5
Found box {34.2521, 634.291, 194.894, 906.538} with score 0.312256 and class 5
Found box {17.6555, 562.042, 274.671, 865.375} with score 0.301568 and class 5

Do we need to make changes to the sample inference code for different resolutions to work ?

**Comment by yashnv** [comment]
@rnekk2 can you please share the image so I can look into this?

**Comment by rnekk2** [comment]
@yashnv Unfortunately I cannot share the trained model as I am not allowed to share it. Below is the image I am running inference on. It is a 1280x720 image

![image2](https://user-images.githubusercontent.com/32535842/67259313-c3edac00-f4b2-11e9-8f32-292452564d91.jpg)

nvidia@nvidia-desktop:/media/nvidia/Xavier/retinanet-examples/extras/cppapi/build$ identify ~/image2.jpg
/home/nvidia/image2.jpg JPEG 1280x720 1280x720+0+0 8-bit sRGB 32.7KB 0.000u 0:00.000

Below is the output image after running inference.

nvidia@nvidia-desktop:/media/nvidia/Xavier/retinanet-examples/extras/cppapi/build$ ./infer resnet50fpn_960x540.plan ~/image2.jpg
Loading engine...
Preparing data...
image dimensions960540
Running inference...
Took 0.0370928 seconds per inference.
![detections](https://user-images.githubusercontent.com/32535842/67259401-38284f80-f4b3-11e9-9684-e1284b4aae8d.png)
As expected the result image is a 960x540 image. 

nvidia@nvidia-desktop:/media/nvidia/Xavier/retinanet-examples/extras/cppapi/build$ identify detections.png 
detections.png PNG 960x540 960x540+0+0 8-bit sRGB 482KB 0.000u 0:00.000

Inference using default plan 
nvidia@nvidia-desktop:/media/nvidia/Xavier/retinanet-examples/extras/cppapi/build$ ./infer resnet50fpn.plan ~/image2.jpg
Loading engine...
Preparing data...
image dimensions12801280
Running inference...
Took 0.126715 seconds per inference.
Found box {172.82, 717.462, 302.18, 844.987} with score 0.779297 and class 1
Found box {194.969, 706.128, 375.584, 840.411} with score 0.424316 and class 1
Found box {114.109, 704.306, 273.932, 867.068} with score 0.406494 and class 1
Found box {67.8826, 714.315, 182.079, 913.265} with score 0.398926 and class 1
Found box {283.829, 725.115, 417.894, 830.538} with score 0.380299 and class 1
Found box {624.384, 370.998, 1146.1, 1191.19} with score 0.36377 and class 4
Found box {637.548, 318.723, 1224.6, 1073.07} with score 0.347656 and class 5
Found box {34.2521, 634.291, 194.894, 906.538} with score 0.312256 and class 5
Found box {17.6555, 562.042, 274.671, 865.375} with score 0.301568 and class 5

nvidia@nvidia-desktop:/media/nvidia/Xavier/retinanet-examples/extras/cppapi/build$ identify detections_new.png 
detections_new.png PNG 1280x1280 1280x1280+0+0 8-bit sRGB 1.439MB 0.000u 0:00.000
nvidia@nvidia-desktop:/media/nvidia/Xavier/retinanet-examples/extras/cppapi/build$ 

![detections_new](https://user-images.githubusercontent.com/32535842/67260141-55f7b380-f4b7-11e9-897a-3a9ecfca8a51.png)

**Comment by rnekk2** [comment]
All my images are 720x720 resolution images. I used the following command to do the training.

retinanet train resnet50fpn.pth --backbone ResNet50FPN --classes 7 --iters 1500000 --val-iters 150000 --lr 0.0005 --resize 720 --jitter 720 720 --max-size 720 --val-images /data/main_dataset/val_images/ --val-annotations /data/main_dataset/main_val.json  --images /data/main_dataset/train_images/ --annotations /data/main_dataset/main_train.json

I used the following command to use generate a 960x540 custom size onnx model without any issues. I was able to convert to a plan model on Xavier.
root@9387a7c33708:/data/retinanet# retinanet export resnet50fpn.pth resnet50fpn_960x540.onnx --size 540 960
Loading model from resnet50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 7, anchors: 9
Exporting to ONNX...

Here it generated the default onnx model. Its input size is 1200x1200. I was able to create the plan model on Xavier without any issues.
retinanet export resnet50fpn.pth resnet50fpn.onnx
Loading model from resnet50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 7, anchors: 9
Exporting to ONNX...

But while running inference the default model is giving the bounding boxes but the model with the custom size 960x540 is not giving any results. L

Let me know if I need to make any changes to the training job parameters or anywhere else.

**Comment by yashnv** [comment]
@rnekk2 from this information I can only suggest that you try different sizes for exporting like try 960x960 and 540x540, and exchanged sizes. By the way, please pull from the 19.09 branch too. Make sure that you have this [change](https://github.com/NVIDIA/retinanet-examples/commit/af80ef40bf915a145baeaa35174d1b4c6b0ad48d) in the repo.

**Comment by rnekk2** [comment]
@yashnv  I need a model that can run on a 16:9 aspect ratio image. I am able to get it to work on a squared image.

**Comment by rnekk2** [comment]
@rnekk2 The issue is fixed after changing the resize parameters. I am able to run inference on 960x540 image. Thanks for assisting me on this.
