### ISSUE TITLE
error of calibrator.h

### ISSUE THREAD

**Issue by YanhuaCheng** [NVIDIA/retinanet-examples#78]
cv::resize(image, image, Size(_inputDims.d[1], _inputDims.d[2]));  -->
cv::resize(image, image, Size(_inputDims.d[2], _inputDims.d[1]));

Size(w, h)

**Comment by yashnv** [comment]
@YanhuaCheng can you provide the error too?

**Comment by YanhuaCheng** [comment]
@yashnv Origin code will face problems for non-squared resizing

**Comment by yashnv** [comment]
@YanhuaCheng thanks for pointing out the correct order of dimensions for `cv::resize`. We have pushed the changes.
But there was no issue with either of those orders, as the images gets flattened later, to see if the next stream for the batch exists or not. Closing this now.
