### ISSUE TITLE
Error: Output is uniformly zero; network calibration failed.

### ISSUE THREAD

**Issue by adithya-p** [NVIDIA/retinanet-examples#79]
When trying to generate INT8 Calibration file with the following command -  
`retinanet export main_resnet50fpn.pth engine.plan --batch 1 --int8 --calibration-table 960x540_retinanet_calib_table_new --calibration-images /data/main_dataset/val_images/ --calibration-batches 500 --size 540 960`

It fails with the following error:

```
633:Conv -> (36, 5, 8)
634:Sigmoid -> (63, 68, 120)
635:Sigmoid -> (63, 34, 60)
636:Sigmoid -> (63, 17, 30)
637:Sigmoid -> (63, 9, 15)
638:Sigmoid -> (63, 5, 8)
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Tensor (Unnamed Layer* 281) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 281) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 280) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 282) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 282) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 281) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 282) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 280) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 280) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 281) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 282) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 280) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
```
Even though it clearly shows network calibration failed, It still generates the Calibration table file. When I plugin the Calibration table during inference, the inference removes the entire content in Calibration table file and replaces it with "1" and resulting in a segfault.

@florischabert  @pkashinkunti Can you please take a look into this and tell me if I am missing something?

**Comment by yashnv** [comment]
@adithya-p can you try out the [19.09 branch](https://github.com/NVIDIA/retinanet-examples/tree/19.09)?

**Comment by adithya-p** [comment]
I tried the 19.09 branch for calibration, When I try plugging the calibration table to export the model using the master branch, It generates the following error:
```
Building engine...
Building INT8 core model...
Building accelerated plugins...
Applying optimizations and building TRT CUDA engine...
Calibration failure occured with no scaling factors detected. This could be due to no int8 calibrator or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.
Segmentation fault (core dumped)
```
I see that you have used an upgraded version of TensorRT in 19.09, Is that a mandatory requirement during inference also? or Can I stick to the same TRT version(used in the master)?

**Comment by yashnv** [comment]
@adithya-p, I see this error only when the calibration images flag is incorrectly specified. Can you check if the path `/data/main_dataset/val_images/` is correct?

**Comment by adithya-p** [comment]
@yashnv Correct me if I’m wrong, I already have the CalibrationTable file generated, So When I run the inference since `readCache` is enabled It will read the calibration table file and skip the calibration process. So images path shouldn't come into the picture, right?

**Comment by yashnv** [comment]
Calibration table is only successfully created after a successful export. You need to export again, with correct images path.

**Comment by adithya-p** [comment]
@yashnv I have this [CalibrationTable File](http://txt.do/1kw6m) If I pass this CalibrationTable as a parameter to export engine plan, It should skip performing Calibration(and It shouldn't check) and make use of the file I am passing, right? Let me know If I am missing something here?

**Comment by yashnv** [comment]
@adithya-p if you changed your environment, then you will need to re-calibrate the table for Xavier. Engine plans are device and environment specific, so are the calibration tables.

**Comment by adithya-p** [comment]
@yashnv I know that Engine plans are device and environment-specific but didn't know that same applies for calibration tables. Thank you.
