### ISSUE TITLE
    csrc/engine.h:28:21: fatal error: NvInfer.h: No such file or directory

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/retinanet-examples#80]
My TensorRT has been added into LD_LIBRARY_PATH, why still can not found it?

**Comment by yashnv** [comment]
How did you install tensorrt? This should be pre-configured if are using Nvidia's pytorch container.
The include directory for TRT is `/usr/include/x86_64-linux-gnu/`

**Comment by jinfagang** [comment]
Thanks for reply. Yeah, problem solved after I copy into /usr/include
and also lib.

But, I am install all TensorrRT into ~/TensorRT so that I can found it in CMake and easily switch between different version of TensorRT, but how to make python found them in setup.py any way?
