### ISSUE TITLE
export onnx to tensorrt engine failed.

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/retinanet-examples#84]
I logged the output, the error is:

```
Building engine...
Building FP32 core model...
Building accelerated plugins...
we got nbOutputs: 0
Parameter check failed at: ../builder/Network.cpp::addConcatenation::308, condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS
[1]    10006 segmentation fault  ./export ../../weights/retinanet_rn50fpn_fix.onnx retinanet.trt

```

**Comment by jinfagang** [comment]
Why the nbOutputs is 0 I logged out?

**Comment by yashnv** [comment]
Please don't open muliple issues for one problem.

**Comment by JimKlingshirn** [comment]
I've found that in the TensorRT 5 binary release, when the onnx-tensorrt parser fails for any reason, it doesn't report the error. Instead it silently returns without output tensors (nbOutputs: 0).  

To diagnose why the parser fails, I build the onnx-tensorrt github repository and run onnx2trt.   onnx2trt displays  parser error messages that help to debug the problem.

**Comment by jinfagang** [comment]
@yashnv  Sorry for this, but since I found onnx nbOutputs it's not right I suppose this is not related to previous one.

**Comment by jinfagang** [comment]
@JimKlingshirn  You were right, actually I have using onnx2trt convert onnx to a trt engine. It works without any error, this essential of this repo does, is it extended the model and add nms plugin support which is not all same in onnx2trt. But it fails and I don't know why.....
