### ISSUE TITLE
pytorch 1.3 model exported onnx model to trt engine

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/retinanet-examples#85]
Hi, I have trained the model and exported to onnx.

the model is here: https://drive.google.com/open?id=1ivfjK75Y8ax_Z_i945HULUtsxC3iR6aI

It can predict right with the model, but this model seems weired, and when export to trt engine, I got error like this:

```
Building engine...
Building FP32 core model...
Building accelerated plugins...
we got nbOutputs: 0
Parameter check failed at: ../builder/Network.cpp::addConcatenation::308, condition: nbInputs > 0 && nbInputs < MAX_CONCAT_INPUTS
[1]    8827 segmentation fault  ./export ../../weights/retinanet_rn50fpn_fix.onnx retinanet.trt
```

Could anybody have another try to help me debug this bug?

It seems related with onnx it generated, or kindly anyone shared a onnx model to differ with mine? It's really difference behaviour in different version of pytorch

**Comment by yashnv** [comment]
This is the same as #83. Closing this. Write the exact command you are using to generate `retinanet_rn50fpn_fix.onnx`.

**Comment by jinfagang** [comment]
@yashnv  I given it up, I already using another repo retinanet generated onnx and inference via tensorrt.

It's much cleaner and fast without "Nvidia docker".

**Comment by dataplayer12** [comment]
@jinfagang What is the other repo that you are using?

**Comment by jinfagang** [comment]
@dataplayer12  It's private, changed from one.

**Comment by dataplayer12** [comment]
Got it. Thanks.

**Comment by azuryl** [comment]
@jinfagang What is the other repo that you are using?
