### ISSUE TITLE
Parsing output tensors to scores, boxes and classes

### ISSUE THREAD

**Issue by dataplayer12** [NVIDIA/retinanet-examples#86]
I downloaded a retinanet ONNX model from one of NVIDIA's webcasts on DeepStream SDK which was trained on [Stanford](http://cvgl.stanford.edu/projects/uav_data/) drone dataset. The model takes in a 1280x1280 image and outputs 10 tensors of sizes:
- 1x54x160x160
- 1x36x160x160
- 1x54x80x80
- 1x54x10x10
- 1x36x80x80
- 1x54x40x40
- 1x36x10x10
- 1x54x20x20
- 1x36x40x40
- 1x36x20x20

Here is how the outputs of the network look like when visualized with netron:
![Imgur](https://i.imgur.com/rjBs9iY.png)

I am at a loss on how to parse these outputs to get confidence scores, bounding boxes and object classes. I would like to deploy the model on a Jetson Xavier, but due to problems with building the deepstream docker image and installing DALI on my Xavier, I am unable to use either the docker image or the retinanet python library. I have converted the onnx model into a plan file and can run inference with it with a TensorRT engine, but I don't know how to use the outputs returned by the graph. The inference example in [python](https://github.com/NVIDIA/retinanet-examples/blob/07502b0b2f31c2e6b085e458d9b6c9d204b25c7b/retinanet/infer.py#L66) in `retinanet` dir get the scores, boxes and classes from the `model` object. I would like to be able to do the same starting from these 10 outputs.

**Comment by james-nvidia** [comment]
Hello @dataplayer12,

What issues did you have with this?
>  I would like to deploy the model on a Jetson Xavier, but due to problems with building the deepstream docker image and installing DALI on my Xavier

By far the easiest and fastest option for inference on the Xavier is to get DeepStream working. I have recently installed DeepStream on my Xavier: When you install the latest JetPack there is an option that allows you to install DeepStream at the same time.

Can you try the above, or do you need to understand those 10 tensors?

**Comment by dataplayer12** [comment]
Thank you for the quick response. Deep stream is installed on my xavier, but I have not been able to compile [`libnvdsparsebbox_retinanet.so`](https://github.com/NVIDIA/retinanet-examples/blob/master/extras/deepstream/deepstream-sample/nvdsparsebbox_retinanet.cpp) (necessary for inference with deepstream) on the xavier because `retinanet` does not work as `dali` is missing on my xavier and can apparently be only [installed](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/installation.html) on x64 systems. I think it might be just easier to write my own parser after understanding the 10 outputs, but I am open to all suggestions.

**Comment by james-nvidia** [comment]
I'm in the process of updating the instructions for getting RetinaNet working in DeepStream on Xavier -- I hope to finish by next week.
It should be something like this:
```
RUN apt-get update && apt-get install -y libssl1.0.0  libgstreamer1.0-0    gstreamer1.0-tools   gstreamer1.0-plugins-good  gstreamer1.0-plugins-bad     gstreamer1.0-plugins-ugly  gstreamer1.0-libav   libgstrtspserver-1.0-0   libjansson4 ffmpeg libjson-glib-1.0 libgles2-mesa
```

```
RUN mkdir extras/deepstream/deepstream-sample/build && \
cd extras/deepstream/deepstream-sample/build && \
cmake -DDeepStream_DIR=<path to your DeepStream install> .. && make -j
```
You don't need to install `retinanet` on the Xavier, just clone the repo and make the `.so` file.

Please let me know if this doesn't work and I'll boot up my Xavier and check the exact instructions.

**Comment by dataplayer12** [comment]
Hi @james-nvidia 
I did as you instructed. The `.so` file compiles, but deepstream is unable to find `boxes`, `classes` and `scores` in the engine file (which was created on the xavier with the onnx file supplied in the webinar). I guess now this is not an issue related to this repository as the webinar is independent from the repo. Do you provide models trained on Stanford drone dataset which I could try out? I have a feeling that the `onnx` file provided in Nvidia's webinar was not trained on this model in spite of what the README says. I will get in touch with Mr. Jason Tichy who gave the webinar and hopefully he will respond. I am posting the error log below, in case it gives you some clues.

```Shell

Using winsys: x11 
0:00:02.258914706 [335m12928[00m     0x2c8cd180 [33;01mWARN   [00m [00m             nvinfer gstnvinfer.cpp:515:gst_nvinfer_logger:<primary_gie_classifier>[00m NvDsInferContext[UID 1]:log(): Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
0:00:04.321250614 [335m12928[00m     0x2c8cd180 [33;01mWARN   [00m [00m             nvinfer gstnvinfer.cpp:515:gst_nvinfer_logger:<primary_gie_classifier>[00m NvDsInferContext[UID 1]:checkEngineParams(): Could not find output layer 'boxes' in engine
0:00:04.321367707 [335m12928[00m     0x2c8cd180 [33;01mWARN   [00m [00m             nvinfer gstnvinfer.cpp:515:gst_nvinfer_logger:<primary_gie_classifier>[00m NvDsInferContext[UID 1]:checkEngineParams(): Could not find output layer 'scores' in engine
0:00:04.321418045 [335m12928[00m     0x2c8cd180 [33;01mWARN   [00m [00m             nvinfer gstnvinfer.cpp:515:gst_nvinfer_logger:<primary_gie_classifier>[00m NvDsInferContext[UID 1]:checkEngineParams(): Could not find output layer 'classes' in engine
Creating LL OSD context new
gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream-4.0/lib/libnvds_mot_iou.so
gstnvtracker: Optional NvMOT_RemoveStreams not implemented
gstnvtracker: Batch processing is OFF

Runtime commands:
	h: Print this help
	q: Quit

	p: Pause
	r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.

** INFO: <bus_callback:189>: Pipeline ready

** INFO: <bus_callback:175>: Pipeline running

Creating LL OSD context new
Could not find bbox layer buffer while parsing
0:00:04.913934061 [335m12928[00m     0x2c3eb0a0 [31;01mERROR  [00m [00m             nvinfer gstnvinfer.cpp:511:gst_nvinfer_logger:<primary_gie_classifier>[00m NvDsInferContext[UID 1]:fillDetectionOutput(): Failed to parse bboxes using custom parse function
```

**Comment by james-nvidia** [comment]
I'm glad we're getting closer!
Does you primary inference config (not the one that you call with `deepstream-app -c`) contain these lines?
```
output-blob-names=boxes;scores;classes
parse-bbox-func-name=NvDsInferParseRetinaNet
custom-lib-path=build/libnvdsparsebbox_retinanet.so
```

**Comment by dataplayer12** [comment]
The config file itself does not have these lines, but it defines another config file `config-file=infer_config.txt`, which does have these lines in it.

**Comment by james-nvidia** [comment]
I think there's a minor issue in one of those files. Could you share them with me?

**Comment by dataplayer12** [comment]
Thank you for taking the time to solve this.
The config file called with `deepstream-app` is:

```Text
# Copyright (c) 2018 NVIDIA Corporation.  All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.

[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=1920
height=1080
gpu-id=0
#(0): nvbuf-mem-default - Default memory allocated, specific to particular platform
#(1): nvbuf-mem-cuda-pinned - Allocate Pinned/Host cuda memory, applicable for Tesla
#(2): nvbuf-mem-cuda-device - Allocate Device cuda memory, applicable for Tesla
#(3): nvbuf-mem-cuda-unified - Allocate Unified cuda memory, applicable for Tesla
#(4): nvbuf-mem-surface-array - Allocate Surface Array memory, applicable for Jetson
nvbuf-memory-type=0

[source0]
enable=1
#Type - 1=CameraV4L2 2=URI 3=MultiURI 4=RTSP
type=2
num-sources=1
uri=file://./videos/video.mov
gpu-id=0
# (0): memtype_device   - Memory type Device
# (1): memtype_pinned   - Memory type Host Pinned
# (2): memtype_unified  - Memory type Unified
cudadec-memtype=0


[streammux]
gpu-id=0
##Boolean property to inform muxer that sources are live
live-source=0
batch-size=1
##time out in usec, to wait after the first buffer is available
##to push the batch even if the complete batch is not formed
batched-push-timeout=400000
## Set muxer output width and height
width=1920
height=1080
##Enable to maintain aspect ratio wrt source, and allow black borders, works
##along with width, height properties
enable-padding=0
nvbuf-memory-type=0


# config-file property is mandatory for any gie section.
# Other properties are optional and if set will override the properties set in
# the infer config file.
[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=infer_config.txt

[tracker]
enable=1
tracker-width=1920
tracker-height=1080
ll-lib-file=/opt/nvidia/deepstream/deepstream-4.0/lib/libnvds_mot_iou.so
#ll-config-file required for IOU only
ll-config-file=iou_config.txt
gpu-id=0
enable-batch-process=1


[osd]
enable=1
gpu-id=0
border-width=1
text-size=12
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Arial
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0


[sink0]
enable=1
#Type - 1=FakeSink 2=EglSink 3=File
type=2
sync=1
source-id=0
gpu-id=0
nvbuf-memory-type=0

[sink1]
enable=0
type=3
#1=mp4 2=mkv
container=1
#1=h264 2=h265
codec=1
sync=0
#iframeinterval=10
bitrate=2000000
output-file=out.mp4
source-id=0

[sink2]
enable=0
#Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming
type=4
#1=h264 2=h265
codec=1
sync=0
bitrate=4000000
# set below properties in case of RTSPStreaming
rtsp-port=8554
udp-port=5400



[tests]
file-loop=1
```

The `infer_config.txt` file is:
```Text
# Copyright (c) 2018 NVIDIA Corporation.  All rights reserved.
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.

# Following properties are mandatory when engine files are not specified:
#   int8-calib-file(Only in INT8)
#   Caffemodel mandatory properties: model-file, proto-file, output-blob-names
#   UFF: uff-file, input-dims, uff-input-blob-name, output-blob-names
#   ONNX: onnx-file
#
# Mandatory properties for detectors:
#   parse-func, num-detected-classes,
#   custom-lib-path (when parse-func=0 i.e. custom),
#   parse-bbox-func-name (when parse-func=0)
#
# Optional properties for detectors:
#   enable-dbscan(Default=false), interval(Primary mode only, Default=0)
#
# Mandatory properties for classifiers:
#   classifier-threshold, is-classifier
#
# Optional properties for classifiers:
#   classifier-async-mode(Secondary mode only, Default=false)
#
# Optional properties in secondary mode:
#   operate-on-gie-id(Default=0), operate-on-class-ids(Defaults to all classes),
#   input-object-min-width, input-object-min-height, input-object-max-width,
#   input-object-max-height
#
# Following properties are always recommended:
#   batch-size(Default=1)
#
# Other optional properties:
#   net-scale-factor(Default=1), network-mode(Default=0 i.e FP32),
#   model-color-format(Default=0 i.e. RGB) model-engine-file, labelfile-path,
#   mean-file, gie-unique-id(Default=0), offsets, gie-mode (Default=1 i.e. primary),
#   custom-lib-path, network-mode(Default=0 i.e FP32)
#
# The values in the config file are overridden by values set through GObject
# properties.

[property]
gpu-id=0
net-scale-factor=0.017352074
offsets=123.675;116.28;103.53
model-engine-file=./resnext50batch4.plan
labelfile-path=./stanford.names
batch-size=1
## 0=FP32, 1=INT8, 2=FP16 mode
network-mode=2
num-detected-classes=80
interval=5
gie-unique-id=1
#parse-func=0
is-classifier=0
output-blob-names=boxes;scores;classes
parse-bbox-func-name=NvDsInferParseRetinaNet
custom-lib-path=./libnvdsparsebbox_retinanet.so
#enable-dbscan=1


[class-attrs-all]
threshold=0.3
group-threshold=0
## Set eps=0.7 and minBoxes for enable-dbscan=1
#eps=0.2
#minBoxes=3
#roi-top-offset=0
#roi-bottom-offset=0
detected-min-w=4
detected-min-h=4
#detected-max-w=0
#detected-max-h=0

## Per class configuration
#[class-attrs-2]
#threshold=0.6
#eps=0.5
#group-threshold=3
#roi-top-offset=20
#roi-bottom-offset=10
#detected-min-w=40
#detected-min-h=40
#detected-max-w=400
#detected-max-h=800
```

**Comment by james-nvidia** [comment]
Two possible things to try:
1. Replace the `custom-lib-path` to an absolute path so that `.so` file.
2. Are you preloading the `.so` with
`LD_PRELOAD=<your_local_path>/retinanet-examples/extras/deepstream/build/libnvdsparsebbox_retinanet.so deepstream-app -c <path to your first config file>`?

**Comment by dataplayer12** [comment]
I have tried out both these things and they do not make a difference. If you scroll to the right in the deepstream error log I posted, you will see the following errors:

```Shell
checkEngineParams(): Could not find output layer 'boxes' in engine
checkEngineParams(): Could not find output layer 'scores' in engine
checkEngineParams(): Could not find output layer 'classes' in engine
```
I think the problem is that the output tensors of the engine are not named correctly which is why deepstream cannot identify them. The netron visualization I posted in my first comment shows that the tensors are named as numbers `634` etc. which is causing the problem. Also, I found that there is virtually no way to contact the person (Mr. Jason Tichy) who spoke at the webinar. It seems like there is no way for me to reproduce the results shown in the webinar on a xavier.

**Comment by james-nvidia** [comment]
I am sorry, I didn't see those errors. Could you post the exact command(s) you used to convert the ONNX model into a TensorRT engine?

**Comment by dataplayer12** [comment]
I used the `trtexec` utility from tensorRT to convert the onnx file to plan file.

```Shell
/usr/src/tensorrt/bin/trtexec --onnx=./stanford_resnext50.onnx --batch=1 --fp16 --saveEngine=resnext50.plan
```
I have used this python script to load the engine and run inference without any errors, so the plan file seems to be working fine. Here is the link to the [webinar](http://go.nvidianews.com/dc/Ty58ol2Ube3I8pgmu_WArvStj6XbWRGXWkAZY1LzhWTzLXNHPKS0BV7BGSc_UfLnrsN9qjvyMiH8wtAcnwkDDFhf65REN7qhIZDTPZHoMdmGxzwGGPr7l-zysQq6xmLAbcs84_0Q4Bf6aa9jge1FX0qOVqI71plWvsc13G6SusnN_kbGc0qq7rJXpy2d9tWjLXELID3wYEHRZoNdEA8P42FfKySP092XdQni3ZHH-b8=/s0bif6s0UFMC0O31wc00E0N) from where I downloaded the onnx model.

```Python
import tensorrt as trt
import time
import os
import pycuda.driver as cuda
import common
import numpy as np
TRT_LOGGER=trt.Logger(trt.Logger.WARNING)

#with trt.Runtime(TRT_LOGGER) as runtime:
#	engine=runtime.deserialize_cuda_engine('./resnext50.plan')

def get_random_input(engine,inputs):
	random_inputs=[]
	for _input_ in inputs:
		arr=np.random.random(_input_.shape).astype(_input_.dtype)
		random_inputs.append(arr)
	return random_inputs

print('Importing engine')
with open('./resnext50.plan','rb') as f:
	with trt.Runtime(TRT_LOGGER) as runtime:
		engine=runtime.deserialize_cuda_engine(f.read())
print('Engine imported successfully')


inputs,outputs,bindings,stream=common.allocate_buffers(engine)
print('Buffers allocated')

context=engine.create_execution_context()
print('Execution context defined')

for i in range(10):
	inputs[0].host=get_random_input(engine,inputs)[0]
	start=time.time()
	results=common.do_inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream, batch_size=1)
	print('Time taken={} ms'.format(np.round((time.time()-start)*1000)))
```

**Comment by james-nvidia** [comment]
Have you tried using the C++ API that we provide in this repo? It should make an engine with the correct node names.
https://github.com/NVIDIA/retinanet-examples/tree/master/extras/cppapi

**Comment by dataplayer12** [comment]
Wow, that worked!! The engine file generated form the `export` utility created by the C++ API works correctly with deepstream. Thank you very much for taking the time out to solve this problem. I really appreciate it!

**Comment by james-nvidia** [comment]
You are welcome. Please let us know how your video analytics projects go.

**Comment by dataplayer12** [comment]
Hi @james-nvidia 
Thanks to your efforts yesterday, once I got the inference examples working, I used the C++ API to extend the `infer` example to videos and wrote a [blog](https://medium.com/@jaiyamsharma/detecting-pedestrians-and-bikers-on-a-drone-with-jetson-xavier-93ce92e2c597) about it with an accompanying [video](https://www.youtube.com/watch?v=Iq2PYcmr5WA&feature=emb_title). If I create a pull request with the script that performs inference on video, would you be open to reviewing/accepting it? I hope that the blog, along with this script will help ease the pain of folks who just want to get inference working on a Xavier.

**Comment by eliabruni** [comment]
> I'm in the process of updating the instructions for getting RetinaNet working in DeepStream on Xavier -- I hope to finish by next week.
> It should be something like this:
> 
> ```
> RUN apt-get update && apt-get install -y libssl1.0.0  libgstreamer1.0-0    gstreamer1.0-tools   gstreamer1.0-plugins-good  gstreamer1.0-plugins-bad     gstreamer1.0-plugins-ugly  gstreamer1.0-libav   libgstrtspserver-1.0-0   libjansson4 ffmpeg libjson-glib-1.0 libgles2-mesa
> ```
> 
> ```
> RUN mkdir extras/deepstream/deepstream-sample/build && \
> cd extras/deepstream/deepstream-sample/build && \
> cmake -DDeepStream_DIR=<path to your DeepStream install> .. && make -j
> ```
> 
> You don't need to install `retinanet` on the Xavier, just clone the repo and make the `.so` file.
> 
> Please let me know if this doesn't work and I'll boot up my Xavier and check the exact instructions.

Hey @james-nvidia, any progress on the instruction update for Xavier? It'd be very useful I think!

**Comment by jsn5** [comment]
Hi @james-nvidia, if running inference on tensorrt model how can I get the bounding boxes in python? I'm running on a jetson nano.

**Comment by james-nvidia** [comment]
Does this work?
`retinanet infer engine.plan --images /coco/images/val2017 --output detections.json`
