### ISSUE TITLE
[Performance question] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.

### ISSUE THREAD

**Issue by KNaudin** [NVIDIA/retinanet-examples#87]
Hello, I had a question about performances. I have two computers, each using a GTX 1050ti graphic card but they don't have the same GPU BIOS version.

When exporting an engine file on one computer and using it on the other, I get the warning `Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.` as if I were using different GPUs.

Here's my question: is it normal for the inference program to think that it's dealing with 2 GPUs and if yes will it really result in a loss of performance since both graphic cards are 1050ti ?

Complementary information:
Graphic card 1:
```
    NVIDIA-SMI 410.79
    Driver Version: 410.79
    CUDA Version: 10.0
    nvidia-smi --query-gpu=gpu_name,vbios_version --format=csv : GeForce GTX 1050 Ti, 86.07.42.00.88
```
Graphic card 2:
```
    NVIDIA-SMI 410.79
    Driver Version: 410.79
    CUDA Version: 10.0
    nvidia-smi --query-gpu=gpu_name,vbios_version --format=csv : GeForce GTX 1050 Ti, 86.07.59.00.53
```

**Comment by yashnv** [comment]
The answer to all TRT engine plan problems is to generate the plan on the GPU which you want to run inference on.

Using the same plan file across multiple GPUs of the same type (1050ti in your case) is fine. That WARNING is just a catch-all to warn users not to use the same plan file on a 1050, a 1080, a T4, a V100, etc. and expect it work the same. However, TensorRT models even take into account the current available memory on the device at the time of creating the plan file. So even if you're using the same GPU (1050ti) but the one you used to create the plan file had background processes taking up half of the GPUs memory, you could see different performance than if the memory was all free at the time of creating the plan file.

**Comment by KNaudin** [comment]
Thank you. I knew what the warning meant but I was unsure as to why it would appear here since both cards are the same and only their BIOS version is different.
I am closing this since it confirmed my first thoughts.
