### ISSUE TITLE
For anyone using pytorch1.3

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/retinanet-examples#88]
I previously not using nvidia docker and comment out dali related code to train and export.

onnx can be generated but can not build to engine in the end, so that can not run on tensorrt backend.

when convert to docker, it can exported to engine.plan and inference, inside docker using pytorch 1.2

So, i think pytorch1.3 doesn't fit the style of this repo. using pytorch1.3 can exported to onnx but just can not work well with tensorrt engine.

**Comment by james-nvidia** [comment]
The easiest way to use PyTorch is to download the latest container from ngc.nvidia.com. The NGC containers have been optimised to run very quickly on NVIDIA GPUs, and remove many issues related to version matching.
