### ISSUE TITLE
why onnx input size fixed convert to engine, results worse

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/retinanet-examples#90]
![image](https://user-images.githubusercontent.com/21303438/68931852-5a6c6f00-07cc-11ea-98e1-09e5aa7abb24.png)

![image](https://user-images.githubusercontent.com/21303438/68931890-753ee380-07cc-11ea-8a28-f5348a3ba175.png)
![image](https://user-images.githubusercontent.com/21303438/68931995-a9b29f80-07cc-11ea-9c55-d380ac051ac9.png)

![image](https://user-images.githubusercontent.com/21303438/68932015-b8995200-07cc-11ea-8b3f-5e00caf67ffa.png)
![image](https://user-images.githubusercontent.com/21303438/68932039-c3ec7d80-07cc-11ea-9230-92c00ad3d336.png)

**Comment by james-nvidia** [comment]
Sorry @jinfagang , I don't fully understand the problem. Remember that the C++ API is just an example -- you may need to alter it to get the best possible performance.

**Comment by jinfagang** [comment]
@james-nvidia  The python input is dynamic, while onnx exported fixed input size. As I calculated, coco evaluation mAP is 13% less than original pytorch model. I resize model to 1280x1280 when convert to trt.

**Comment by james-nvidia** [comment]
Are you using the C++ API to infer your examples? Or `retinanet`?
If `retinanet`, are you using the `--with-dali` flag?

**Comment by jinfagang** [comment]
using c++

**Comment by jinfagang** [comment]
I convert input image to RGB (cv default is BGR), then feed into tensorrt, result seems better.

**Comment by james-nvidia** [comment]
The C++ API is just an example, to show you how to infer on your images. It does not load data in the same way as PyTorch (eg it does not maintain the aspect ratio). If you are processing IVA data, then you should use DeepStream. Otherwise either adapt the C++ API to your needs, or infer using `retinanet infer engine.plan`
