### ISSUE TITLE
Why the batch size does not affect the latency as expected?

### ISSUE THREAD

**Issue by kurff** [NVIDIA/retinanet-examples#92]
We use P40 with nvidia-driver vision: 384.145, CUDA 9.0, CUDNN 7.6.4, TensorRT 6.0.1.5
When We export model to tensorrt plan file with different batch_size = 1, 4, 32,
the engine toke 0.0237492, 0.0761483, 0.513337 Seconds respectively.
However, the Volatile GPU-Util is about 35% 40% 100% respectively.
Why increase the batch size can not reduce the latency significantly?

**Comment by james-nvidia** [comment]
Hello. I see that the time per image decreases with batch size, which is as expected. Were you hoping for a faster inference rate? What happens at about batch_size 12?

**Comment by james-nvidia** [comment]
Please reopen if that didn't answer your question.
