### ISSUE TITLE
Does it support rotation ?

### ISSUE THREAD

**Issue by dexception** [NVIDIA/retinanet-examples#94]
Looking for support for rotated boxes...

**Comment by james-nvidia** [comment]
We are working on this. I'll message this issue when we have something to share.

**Comment by jamessmith90** [comment]
@james-nvidia Any timeline you can share ?

**Comment by james-nvidia** [comment]
Not at the moment, but we are actively working on it. Do you have any use cases planned?

**Comment by jamessmith90** [comment]
Yes we already have a client on board. The sooner you implement the sooner we will be able to put this in production.

**Comment by james-nvidia** [comment]
@jamessmith90 and @dexception 

We have just pushed rotated bounding box detections. We will improve the inference speed over the next few weeks.
