### ISSUE TITLE
low mAP on custom dataset

### ISSUE THREAD

**Issue by humengdoudou** [NVIDIA/retinanet-examples#96]
I install the whole project successfully, and train it on Pascal VOC dataset with provided pascal_train2007.json / pascal_val2007.json labels, it works very well with high mAP like 77%, which is consistent with official RetinaNet paper;

However, when I turn to train on custom dataset, I get very low mAP compared with other framework(like mAP(IoU = 0.5): 65% vs. 85%(mxnet_ssd)), I double checked the converted custom .json labels, and confirmed its accuracy;

My custom dataset has 6 classes, and I show the predicted bboxes in image with low-mAP trained model(convert .pth to .plan, and inference with command like: ./infer ./xxx.plan, /yyy.jpg). What makes me confused is, the bbox location is right, while class_id all goes wrong, and the predicted class_id wrong format works like: .plan predict all vehicle class into person class, all bicycle class into person class, etc. ---- As I can trained with high-mAP on VOC dataset, and do infer with converted VOC .plan with right predict class id, so I exclude the possibility of causing such wrong label problem during model conversion.

So if the model predict all bboxed with wrong class_id, how can it get mAP like 65% during training, since I already confirmed the effectness of converted .json labels, so I just doubt, are there some codes I ignored in data.py / dali.py, which default setting params stay unchange with voc / coco format ?

**Comment by james-nvidia** [comment]
Can you test your model using the pytorch `retinanet infer` rather than `./infer` on the TensorRT engine? The C++ API is an example, not a finished product. It handles image loading differently than the pytorch data loader.
Did you label your dataset with class IDs starting at 0 or 1? If class 0, then the issue might be with how pycocotools is scoring the results.

**Comment by james-nvidia** [comment]
Any update @humengdoudou ?

**Comment by james-nvidia** [comment]
Closing this issue. Please reopen if this is still a problem.
