### ISSUE TITLE
 module 'nvidia.dali.ops' has no attribute 'nvJPEGDecoderSlice'

### ISSUE THREAD

**Issue by chowkamlee81** [NVIDIA/retinanet-examples#97]
when i try to run inference part iam getting error below:
  File "/home/ubuntu/Analysis/retinanet-examples-master/retinanet/infer.py", line 153, in <module>
    infer(model, images, detections_file, resize, max_size, batch_size, mixed_precision,annotations)
  File "/home/ubuntu/Analysis/retinanet-examples-master/retinanet/infer.py", line 36, in infer
    world, annotations, training=False)
  File "/home/ubuntu/Analysis/retinanet-examples-master/retinanet/dali.py", line 96, in __init__
    device_id = torch.cuda.current_device(), mean=self.mean, std=self.std, resize=resize, max_size=max_size, stride=self.stride)
  File "/home/ubuntu/Analysis/retinanet-examples-master/retinanet/dali.py", line 26, in __init__
    self.decode_train = ops.nvJPEGDecoderSlice(device="mixed", output_type=types.RGB)
AttributeError: module 'nvidia.dali.ops' has no attribute 'nvJPEGDecoderSlice'
terminate called without an active exception

**Kindly help**

**Comment by james-nvidia** [comment]
Are you running in to docker container? If so, which container?
Can you give a minimal reproducible example?

**Comment by chowkamlee81** [comment]
Iam using anaconda environment but not using docker containers.
As per https://github.com/NVIDIA/DALI/issues/1550
nvJPEGDecoderSlice as been replaced by  ImageDecoderSlice with device='mixed'. Hence closing the issue

**Comment by yashnv** [comment]
@chowkamlee81 We have reflected those changes in [19.09 branch](https://github.com/NVIDIA/retinanet-examples/tree/19.09).
